### ISSUE TITLE
Preview markdown on upload/edit

### ISSUE THREAD

**Issue by TheAMM** [nyaadevs/nyaa#10]
As we're doing the render client-side, this should be fairly easy to implement.

**Comment by nathancyam** [comment]
Quick mockup, using Github's presentation as a base.

![nyaa-description-markdown](https://cloud.githubusercontent.com/assets/2491442/26030995/da515f56-38a7-11e7-8f1d-4629b60564a8.png)

How do we want to do this? I can try integrating some NPM packages into this using something like this [https://github.com/chjj/marked](https://github.com/chjj/marked), but don't particular want to add overhead during the build/deploy process.

**Comment by Sn0wCrack** [comment]
Marked is actually already used on the site for processing descriptions on torrent views.

**Comment by TheAMM** [comment]
We already have the library, all we need is to tag the field with an attr like `enable-markdown-preview` and have an onload setup required elements and callbacks for the edit/preview tabs (ala [the age thing I added](https://github.com/nyaadevs/nyaa/blob/39230e1f399f3f2b9432a724e4e7b93eb3d6b497/nyaa/static/js/main.js#L69)). Should be easy to keep small and tidy.

**Comment by nathancyam** [comment]
Thanks. I'll take a look and see what I can whip up.

**Comment by sharkykh** [comment]
This was implemented in #46 (can now be closed)
