### ISSUE TITLE
Can't line break

### ISSUE THREAD

**Issue by Darkmeep** [nyaadevs/nyaa#100]
For some reason you can't line break like this I mean
Title moo moo moo

Description blah blah blah blah

website website website

Its all bunched together into an ugly

Title moo moo moo description blah blah nlah website website website

**Comment by sharkykh** [comment]
Use an empty line between line breaks
```
Description blah blah blah blah

website website website
```

@Nazonaze

There seems to be an issue with CommonMark, I guess?
This error pops up on the dev console when you preview a text like:
```
Description blah blah blah blah
website website website
```
(no empty line between lines)

![image](https://cloud.githubusercontent.com/assets/10238474/26155855/340a044a-3b1d-11e7-8af0-4038f5230995.png)

Error happend on `commonmark.min.js`, I just changed to the full version to see if I could find the issue.

**Comment by FichteFoll** [comment]
Can't say anything about the error in console, by markdown usually collapses simple line breaks. If you want an explicit line break, you need to end the line with **two** spaces.

**Comment by Darkmeep** [comment]
Can you link a torrent that has a line break working in the description please.

**Comment by Nazonaze** [comment]
Hmm, that's odd. I followed [the documentation](https://github.com/jgm/commonmark.js#usage) on how to make softbreaks into hard breaks with `writer.softbreak = '<br />';` (as can be seen in the relevant [PR](https://github.com/nyaadevs/nyaa/pull/88/files) but for some reason it doesn't appear to be working. I'll look into it.

**Comment by Nazonaze** [comment]
Fixed. Turns out commonmark documentation wasn't up to date on how to handle custom softbreak formatting.
