### ISSUE TITLE
[FeatureReq] Move searchbar out of menu in Mobile view

### ISSUE THREAD

**Issue by hohoaisan** [nyaadevs/nyaa#102]
In mobile view, before searching anything, i must touch the Menu to show the searchbar, very tired when i do it for times. Can you move it out of that menu please? (Sorry my English is not good)

**Comment by UnKnoWn-Consortium** [comment]
FYI, here is a demo of such a relocation from #35

![](https://cloud.githubusercontent.com/assets/9733856/26130123/d8eaf2d8-3ac5-11e7-93bf-9c37c551aee0.png)
