### ISSUE TITLE
Ability to mark and/or claim outdated Nyaa torrents

### ISSUE THREAD

**Issue by toynbeeidea** [nyaadevs/nyaa#105]
I have remade most of my old torrents with an updated tracker list.  I would like to request a way to flag old torrents as being deprecated so that I can submit updated versions.

**Comment by TheAMM** [comment]
You can hide or delete your torrents if you have merged the torrents with your (presumably new) account. See the IRC for details on the latter.

**Comment by toynbeeidea** [comment]
I have to log into IRC for details?  Thanks but not thanks.  How about somebody write the procedure down somewhere, yes?

**Comment by TheAMM** [comment]
You contact the person handling the account reclaims on IRC. Cut it with the attitude.

**Comment by sharkykh** [comment]
Just use Kiwi...
http://kiwiirc.com/client/irc.rizon.net/#nyaa-dev
