### ISSUE TITLE
RSS page description and title

### ISSUE THREAD

**Issue by BostAxola** [nyaadevs/nyaa#11]
Hi,

Is not a big deal, and I would fix it myself if I knew Phyton.

In **nyaa/nyaa/templates/rss.xml** <title> and <description> shows always the same, no matter whose user's or query's RSS is.

What is shows is:
> Nyaa Torrent File RSS (No magnets)
> RSS Feed for /

Thanks for bringing back Nyaa^^

**Comment by TheAMM** [comment]
Pointed out in #4 (although, yes, in comments) - it is known.
We'll get on it when the others wake up; it's an easy fix (but I've got to enjoy some of this weekend as well!)

**Comment by JSFernandes** [comment]
I'm thinking of tackling, but I'm not entirely sure what would be the preferable solution.

Am I correct in assuming that we have to change the `label` passed to `render_rss` in https://github.com/nyaadevs/nyaa/blob/master/nyaa/routes.py#L258 ? If so, what do we want to present? The username? Build a string depending on the `query_args`?

**Comment by devocalypse** [comment]
I'd say the uploader username is the top contender for that field. This makes filtering on "from" field possible.
