### ISSUE TITLE
Place "Dark Mode: Toggle" inside the navbar

### ISSUE THREAD

**Issue by HitmanJ** [nyaadevs/nyaa#110]
Instead of having to go all the way down to change the website's color scheme, it'd be better if there was a logo or something else inside the navbar to activate it. Or just have both.

**Comment by phuongtailtranminh** [comment]
+1

**Comment by ReimuHakurei** [comment]
The issue here is that we are already constrained for navbar space as-is, so we really don't have any room to add new things to it without breaking the layout on small screens.

However, we may put the Dark Mode toggle in a more prominent location in the future.
