### ISSUE TITLE
The Upload feature adds sukebei tracker automatically

### ISSUE THREAD

**Issue by phuongtailtranminh** [nyaadevs/nyaa#113]
Hi,

I think it would be better if the upload features can check & add the sukebei tracker automatically without the need of doing it manually

**Comment by aldacron** [comment]
The goal here is that when people upload to other sites, they will also have our tracker as well amongst the others.

**Comment by TheAMM** [comment]
This made me come up with #117, since I consider modifying torrents a pain as well. The trackers live outside `info` so this (117) is very possible to do.
