### ISSUE TITLE
Rearranging the search area

### ISSUE THREAD

**Issue by DahhSC** [nyaadevs/nyaa#116]
Hi, this might be something trivial but I'll ask anyway.
Any thoughts of rearranging the search toolbar similar to the .se version?

The styling stays of course, just swapping the position of the search bar and the categories

**Comment by ReimuHakurei** [comment]
The reasoning for the current positioning of the search box and the categories is that we can't get consistent rounded corners on these UI elements with them in the same order as Nyaa.se had. Even making the current one look proper required a bit of hacking of the library we use.

**Comment by DahhSC** [comment]
So you picked rounded corners over of ease-of-access/intuitivity. That's just css, I don't get how it would require hacking of your library if at all.
