### ISSUE TITLE
Subscribe to users

### ISSUE THREAD

**Issue by PannenkoekenNL** [nyaadevs/nyaa#118]
Please make it possible to subscribe to users, so that you will automatically get a message when the user posts a new torrent.

**Comment by sharkykh** [comment]
You can use an RSS feed, for example https://nyaa.si/?page=rss&u=HorribleSubs

**Comment by TheAMM** [comment]
We're closing some issues that would otherwise linger for ages. We may do this, but for now, RSS works and future-feature requests will soon clutter our issues.
