### ISSUE TITLE
Can Nyaa open on ZeroNet ?

### ISSUE THREAD

**Issue by funny110** [nyaadevs/nyaa#122]
ZeroNet is a p2p network, it can host sites by peers, if nyaa open on it, do not worry about it can be shutdown. ZeroNet has a similar to ThePirateBay site on it, and it works well, 
its name is Play: http://127.0.0.1:43110/0play.bit
#ZeroNet
https://zeronet.io
https://github.com/HelloZeroNet/ZeroNet
![play](https://cloud.githubusercontent.com/assets/28748344/26205664/01032510-3c15-11e7-8fcb-aec3389cc34e.png)

**Comment by TheAMM** [comment]
No. This is *waaaay* out of scope for this project, and from what I can see ZeroNet is for mostly static content with some hacks to kinda get user submitted content allowed.
Nyaa requires a real server for the database holding hundreds of thousands of torrents, the search engine, and the torrent tracker. Besides, we're a public site, requiring users to install a program to view (and host!) the site isn't really our thing.
A torrent index in the blockchain would be neat, but that's entirely another project and I'm pretty sure one should already exist.
