### ISSUE TITLE
magnet link in RSS

### ISSUE THREAD

**Issue by Himeko7** [nyaadevs/nyaa#124]
Can you add magnet links to the RSS feeds?

**Comment by dr-katz** [comment]
Indeed, would be great to have magnet links in the RSS independent of the links to torrent files. As I understand it right now `link` contains a magnet URI only when an RSS item has no torrent file associated with it. In cases when one would like to avoid using torrent files altogether this does not help. If not in the default output then at least via an additional argument...

**Comment by TheAMM** [comment]
Added in (the mess that is) 68b5bc045b0c911198f836038735990c688a9baa.

Use `m` or `magnets` in your RSS, ala `/?page=rss&q=frame&c=0_0&f=0&magnets` when the commit is live.

**Comment by dr-katz** [comment]
Thanks a bunch!
