### ISSUE TITLE
[Feature-Collaboration] qBittorrent search plugin for Nyaa

### ISSUE THREAD

**Issue by phuongtailtranminh** [nyaadevs/nyaa#125]
I've done qBittorrent search plugin for Nyaa. You can check out at here: [https://github.com/phuongtailtranminh/qBittorrent-Nyaa-Search-Plugin](https://github.com/phuongtailtranminh/qBittorrent-Nyaa-Search-Plugin)

I published it in here [https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins](https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins)

This version uses parse mechanism to get the information from Nyaa. I think it would be better if Nyaa developer provides an API to access to information instead of parsing it.

**Comment by ReimuHakurei** [comment]
An API is in the plans for the future, but right now we are more concerned about other, more essential features.
