### ISSUE TITLE
403 Forbidden for default Python urllib

### ISSUE THREAD

**Issue by Khold6458** [nyaadevs/nyaa#126]
I get this request by default using Python, which results in a 403 Forbidden.

```
GET / HTTP/1.1
Accept-Encoding: identity
Host: nyaa.si
User-Agent: Python-urllib/3.6
Connection: close
```

This was working previously. It broke within the past week. I don't know if there are good technical reasons for this to not work, but it would be nice if it did.

Additional Info:
My use case for this is accessing the RSS feed.
I then tried the requests library which worked with default settings, sending this:

```
GET / HTTP/1.1
Host: nyaa.si
User-Agent: python-requests/2.14.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
```

**Comment by TheAMM** [comment]
Include the server responses instead of request headers.

**Comment by Khold6458** [comment]
Sorry, I clearly don't have much experience in this area, and made a completely wrong guess as to what might be useful information. (It seems like Python gave me an unhelpful error message, but that is irrelevant here.)

The server response in the error case says `Please enable cookies.` and gives me details about an `Error 1010`. Please tell me if you need more info for this.

Since this was working at some point, my question becomes whether or not this new behavior is necessary. Either way, I will be using the third-party library which I assume nicely handles and hides away some details.

**Comment by TheAMM** [comment]
CF requires cookies to function, I suppose. Nothing to do with our code. You should be using `requests` anyway.
