### ISSUE TITLE
Reliance on bootstrapcdn.com

### ISSUE THREAD

**Issue by CounterPillow** [nyaadevs/nyaa#133]
Having JS loaded from a third party is not the hottest thing, since it would allow that third party to essentially XSS the site. While I'm sure bootstrapcdn would never intentionally do this, a malicious attacker that gains control over that domain through nefarious means will have different ideas. jquery.com has been hacked before and attackers could've potentially compromised the CDN, so this isn't as unlikely as it seems.

Additionally, I don't really see the reason for using a third-party CDN domain when the entire thing is behind cloudflare anyway. While people may have cached the file from other websites that also use bootstrapcdn, it seems like a silly trade-off considering bootstrapcdn may gather site visitor analytics.

**EDIT**: Alright I just saw that bootstrapcdn does SRI now, so essentially just add the integrity attribute to prevent XSS please [(something that happened in the past with that CDN)](https://www.maxcdn.com/blog/bootstrapcdn-security-post-mortem/) and the only remaining issues are the potential tracking and me being a lazy fuck when it comes to whitelisting shit in uMatrix.

**Comment by Hamuko** [comment]
Shouldn't the site use the Subresource Integrity hash for the JS? It's what BootstrapCDN recommends and they have a copy-pasteable line straight on the homepage.

```html
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

[Why BootstrapCDN Believes in SRI and You Should Too](https://www.maxcdn.com/blog/bootstrapcdn-subresource-integrity/)

**Comment by CounterPillow** [comment]
And while we're at it, the cloudflare cdnjs scripts allow for SRI too:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/commonmark/0.27.0/commonmark.min.js" integrity="sha256-10JreQhQG80GtKuzsioj0K46DlaB/CK/EG+NuG0q97E=" crossorigin="anonymous"></script>
```

On the cdnjs site, click on the little arrow next to "Copy" and choose "Copy Script Tag with SRI" to get these.
