### ISSUE TITLE
Custom RSS Creation Through User Page No Longer Working!

### ISSUE THREAD

**Issue by JLChamberlain** [nyaadevs/nyaa#139]
If you go to a users page then put in a search term and then press the RSS button it doesn't bring up a RSS feed for only that term for the user, it brings up a RSS Feed for the whole site using the search term. This was working the last time i was on the site but now it isn't!, why?

Example: https://nyaa.si/user/HorribleSubs?q=Berserk&f=0&c=0_0

**Comment by TheAMM** [comment]
Fixed in 68b5bc045b0c911198f836038735990c688a9baa.
