### ISSUE TITLE
RSS Updating Slow

### ISSUE THREAD

**Issue by JLChamberlain** [nyaadevs/nyaa#141]
So Hero Academia Ep 21 [1080p] came out this morning at 10:38 but it wasn't applied to the RSS until 11:43. This also seems to be happening for other series. It appears on the site on time but their is some time delay for it appearing in the RSS.

**Comment by ImperatorPrime** [comment]
This appears to be a more general search issue, as I notice it as well when searching for Hero Academia. It looks like the search index hasn't been updated over the past hour. 

Based on my reading of the search merge, the search should be updated on each torrent submission, but could also be a cron job. Thus, I'm not sure if this is a bug or not.

**Comment by aldacron** [comment]
I think that's because sync_es.py isn't very optimized. Sometimes it keeps up, sometimes it doesn't... We need to investigate a better solution.

**Comment by aldacron** [comment]
Fixed thanks to @qqueue
