### ISSUE TITLE
Submitting ticket for torrent migration

### ISSUE THREAD

**Issue by toynbeeidea** [nyaadevs/nyaa#144]
I've jumped through the stupid IRC hoops to get to http://migrate.nyaarchive.moe (not https, shame on you) and claim my old torrents.  The process ends with the message:

"Your ticket number is 1495293647 -- Please give this to ReimuHakurei in #nyaa-dev on irc.rizon.net for processing."

There is no "ReimuHakurei" in #nyaa-dev to submit to.  So I'm submitting it here.

This system is stupid, BTW.  I don't want anything to do with IRC, and I'm not going to sit there all day and wait for this person to show up.

**Comment by TheAMM** [comment]
ReimuHakurei *is* in the channel, but everyone has to sleep sometimes. Doesn't mean you can't message them.

How would you do it?

**Comment by motbob** [comment]
You may have been thrown off by the fact that ReimuHakurei was at the top of the channel's userlist, since he's an op.

**Comment by HitmanJ** [comment]
You can just leave him a message via PM and leave the channel/IRC. "/msg ReimuHakurei Your message"
