### ISSUE TITLE
[Bug] It's a visual bug with the search bar styling again.

### ISSUE THREAD

**Issue by muizzsiddique** [nyaadevs/nyaa#147]
There is a region between short-width windows (mobile browser dimension) and the regular-width desktop interface where the search widget get's all screwed up.

The maximum mobile width of 783px:
![_01_783_mobile](https://cloud.githubusercontent.com/assets/23620568/26278637/7fafc69c-3d97-11e7-976f-9d2b279f601b.png)

The **broken** range between 784-1006px:
![_02_784_broken](https://cloud.githubusercontent.com/assets/23620568/26278639/7fb43222-3d97-11e7-9f21-a1fdb5b0f446.png)
![_03_1006_broken](https://cloud.githubusercontent.com/assets/23620568/26278638/7fb42886-3d97-11e7-8033-aefafc9d56e6.png)

The **one** pixel it looks fine, at 1007px wide:
![_04_1007_perfect](https://cloud.githubusercontent.com/assets/23620568/26278640/7fb4eda2-3d97-11e7-85c7-e2be3b95f534.png)

And the beginning of the desktop interface, from 1008px wide and up:
![_05_1008_desktop](https://cloud.githubusercontent.com/assets/23620568/26278641/7fb84cae-3d97-11e7-915d-d38cb9074a0a.png)

And those widths are from a Windows 7 PC with a resolution of 1920x1080 at default scaling and default ppi.

**Comment by UnKnoWn-Consortium** [comment]
It seems to be related to the dark-mode theme. I have failed to replicate this on the light-mode theme. The exact range should be from 768px to 990px.

**Comment by Arylide** [comment]
Unless I'm mistaken it seems fine now. Reopen if I'm wrong.
