### ISSUE TITLE
Search broke

### ISSUE THREAD

**Issue by motbob** [nyaadevs/nyaa#150]
Searching for "clockwork planet -horrible" serves no results. This wasn't always the case. There was some speculation in IRC that this could be due to the ES index being rebuilt. If that's the case, it's still bad that search is broken during that time.

Issue 1: searching for "horrible" doesn't serve HorribleSubs' torrents, so partial terms don't return results where the partial search term was the beginning of the full sought-after term. This also wasn't always the case.
Issue 2: "clockwork planet -horriblesubs" returns Horriblesubs' Clockwork Planet releases. So, search seems to just be disregarding "-". Searching for k-on is also broken again.

**Comment by snowfag** [comment]
the new search was disabled for a bit due to being way behind
