### ISSUE TITLE
Include magnet link in RSS feed entries

### ISSUE THREAD

**Issue by rhaeth** [nyaadevs/nyaa#155]
Feature request - in the RSS entries, please include links for both the Torrent download, and the Magnet download.

**Comment by TheAMM** [comment]
Everyone keeps asking for this, but there's only one `<link>`.
Just use `&magnets` if you want a magnet only feed.

**Comment by My1** [comment]
wh not add a droptdown to the RSS to get a link for magnet stuff?

**Comment by ReimuHakurei** [comment]
Because then you'd need two clicks to get to either RSS feed, making the site clunkier to add something of questionable value.

**Comment by My1** [comment]
there's something called split dropdown. in bootstrap click on RSS and you get the normal one. click on the arrow and then the other link to the magnet.

http://getbootstrap.com/components/#btn-dropdowns-split this is an example with buttons but basically works similar in the navbar

**Comment by FichteFoll** [comment]
Note also that you can have multiple &lt;link&gt; tags to feeds in the head, iirc.
