### ISSUE TITLE
[Request] Public Developer API

### ISSUE THREAD

**Issue by yonson2** [nyaadevs/nyaa#161]
Related to #125 and #18.
Are there any plans on publishing a developer API? 
Scraping websites suck and is a waste of resources. I feel like a read-only api (no torrent creation, user registration, etc...) that had just the basics of search and listing torrents would benefit a lot of people.

**Comment by sharkykh** [comment]
#18 is already in the works over at #108.
AFAIK there's no time frame

**Comment by Arylide** [comment]
It sorta exists at the moment, you need an account but you can do what you need to.
