### ISSUE TITLE
Stop adding additional trackers

### ISSUE THREAD

**Issue by anonymlol** [nyaadevs/nyaa#164]
I only added the first 3 trackers, yet there are lots of additional trackers in my torrents. It seems you're adding trackers from [trackers.txt](https://github.com/nyaadevs/nyaa/blob/2147c6e2877b243f2fc821afa21bd257f4c3ea9a/trackers.txt). Is this really necessary?

![image](http://i.imgur.com/fYJJF8w.png)

**Comment by TheAMM** [comment]
We add trackers for the doomsday, in case shit happens, torrents people download won't all rely on a single dead tracker. However, there should not be that many at all, it should max out at 5 trackers (and I mean it was coded like that last I saw).
