### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by TheCastleKeeper** [nyaadevs/nyaa#166]
Hi.  The RSS Feed will not load in FeedReader 3.14.  It does work in uTorrent 2.1.1 and FeedReader Online, but it will not load in FeedReader 3.14 for some reason.  Any idea what is wrong?  I have tried this on multiple machines and installs.   Thanks, TCK.

**Comment by timothy-hanson** [comment]
I'm also having problems with certain feeds. For example: https://nyaa.si/?q=danmachi&f=2&c=1_2 I get this error: 

`LibXML error 68 at line 16 (column 458): xmlParseEntityRef: no name`

**Comment by timothy-hanson** [comment]
Ah, I BELIEVE it's because the description looks like this:

<description>RSS Feed for &#34;danmachi&#34;</description>

and the & characters are messing things up.

**Comment by Sn0wCrack** [comment]
According to your error, it seems to be happening on line 16, the description element is on line 4 of the RSS feed.

Also that is how & work in both XML and HTML, they're used to place their character representations into the XML.

Also if that link is what you're trying to parse, then you should be using: https://nyaa.si/?page=rss&q=danmachi&c=1_2&f=2 

I can also confirm the RSS feed works on numerous applications, it seems this FeedReader may just be out of date or broken, as it passes the w3 Atom and RSS validator with flying colours.

**Comment by timothy-hanson** [comment]
There's sort of inconsistent behavior it seems like, and yes, seems like maybe client side. However when I take another working feed the description looks like

`<description>RSS Feed for "No Game Life"</description>` where the `&#34;` seems to be rendering as double quotes. Maybe it would be nice to see consistency where it's rendered as that throws some RSS readers for a loop it seems like.
