### ISSUE TITLE
Upload API V2 Not working properly

### ISSUE THREAD

**Issue by SaikyoKid** [nyaadevs/nyaa#168]
I tried to upload via the API V2 today and couldn't understand how it works.

So, I tried to post my torrents from POSTMAN to see things. It posted the torrent just fine. But the torrent is being marked as Hidden, Anonymous, Remake and complete.

Although, it did appear under my account. But, it was marked with all these fields i have mentioned above.
why is this happening?

my postman data : 

```
torrent_data:{↵	"name": "",↵	"category": "1_2",↵	"information": "",↵	"description": "",↵	"anonymous": "False",↵	"hidden": "False",↵	"complete": "False",↵	"remake": "False",↵	"trusted": "False"↵}

torrent = torrentFile
```

**Comment by Sn0wCrack** [comment]
The issue is you're passing the data in as strings rather than booleans by the looks of it

**Comment by SaikyoKid** [comment]
I tried sending those in Boolean. But, the page then returned nyaa's homepage and had this line "An error occurred! Debug information has been logged.".

**Comment by SaikyoKid** [comment]
So, I tried this as well : 

```
torrent_data:{↵	"name": "",↵	"category": "1_2",↵	"information": "",↵	"description": "",↵	"anonymous": False,↵	"hidden": False,↵	"complete": False,↵	"remake": False,↵	"trusted": False↵}

torrent = torrentFile
```

Still the same problem.

**Comment by Sn0wCrack** [comment]
JSON booleans are formatted as lower case, where as you seem to be using the Python Syntax for True and False which begin with an upper case.

**Comment by SaikyoKid** [comment]
In python, there is no such thing as "true" or "false". If I have to send these values, they'll have to be sent as strings. And according to your previous comment, strings might not work.

I used their api_uploaderV2 https://github.com/nyaadevs/nyaa/blob/master/utils/api_uploader_v2.py and ran it with the command line arguments, as mentioned in it and got the same error **"An error occurred! Debug information has been logged.".**.

So, I guess their API is not working or both the scripts are wrong. The previous one worked like a charm, the V1 api_upload.

**Comment by katnyaa** [comment]
https://github.com/nyaadevs/nyaa/commit/aa0d7f702f5bdb9c8a1a1e3782e8b362a9b40c8b makes malformed JSON a 400 error, when it is deployed in the next batch it should help you debug.

**Comment by Mause** [comment]
> In python, there is no such thing as "true" or "false"

sorry what? As @Sn0wCrack mentioned, there are, you just format them differently in json, like so
```json
{"value": true, "otherValue": false}
```
did you try it like that?
python does like so
```python
value = True
otherValue = False
```

**Comment by SaikyoKid** [comment]
@Mause In python, `true`, `false` are treated like a variable rather than a boolean value and when you execute the python program, you will see the errors. And yes I have tried both the ways. The older API V1 was working just fine.

**Comment by Sn0wCrack** [comment]
You were saying you tried to execute this in Postman however, which sends raw JSON, as does the API example uploader, it takes a Python Dict and turns it into JSON before sending it
