### ISSUE TITLE
Don't use gravatar

### ISSUE THREAD

**Issue by CounterPillow** [nyaadevs/nyaa#170]
Just do the fucking same thing that nyaa did, which is allowing people to use imgur URLs.
Gravatar requires you to make a wordpress account, which is retarded just for an avatar. They also scale images in strange ways for no reason, so they look like shit.

**Comment by GiacomoLaw** [comment]
Would like to see this!

**Comment by CounterPillow** [comment]
Thanks for giving me a useless notification for this very important comment, @GiacomoLaw

**Comment by GiacomoLaw** [comment]
Wow...

**Comment by ReimuHakurei** [comment]
Gravatar is fine and we won't be changing to anything else any time soon.
