### ISSUE TITLE
Old comments from nyaa.se

### ISSUE THREAD

**Issue by Rick-74** [nyaadevs/nyaa#171]
99% of the comments were utter trash, I know. But sometimes they actually contained really useful things like DL links, patches for the release, comparisons, ...
So, is it possible to have them imported back or it's too much work/they're gone forever?

**Comment by ReimuHakurei** [comment]
We have the comments, but with how our database is currently structured, adding them would be difficult.

The most likely solution would be a read-only comment archive sometime in the future.
