### ISSUE TITLE
Allow search by infohash

### ISSUE THREAD

**Issue by moxian** [nyaadevs/nyaa#174]
Currently it is only possible to search by torrent name.

Just now I've found myself in a situation where I need to search by info hash (I have an old magnet link lingering in torrent client, that is definitely anime, but I have no idea what anime that is, since I've never found a peer via dht).

As a data point, you can search by infohash at acgnx.se.

**Comment by mreweilk** [comment]
This functionality will be included in the api soon, pull request here: https://github.com/nyaadevs/nyaa/pull/157

**Comment by moxian** [comment]
I'm not sure how exposed the API is/would be, but I'd say just in case that I would appreciate if this functionality was available via the web browser, and not only programmatically.
