### ISSUE TITLE
Suggestion: BBCode Support

### ISSUE THREAD

**Issue by ShardM** [nyaadevs/nyaa#177]
BBCode support as it is more versatile than markdown and already known by Nyaa users. It allows better formatting of description.

Related: https://github.com/NyaaPantsu/nyaa/issues/687

**Comment by sharkykh** [comment]
1. Why would you link a competing site/repo? Nyaa.si **is not related** to NyaaPantsu in any way...
2. In my opinion, WYSIWYG (what-you-see-is-what-you-get) editors like [TinyMCE](https://www.tinymce.com/) are better than either BBCode or Markdown.

**Comment by Sn0wCrack** [comment]
I don't really a reason to go so far as to add a fully featured text input, it's a simply comments section.

We didn't really need more than text and links in the end, and that's what's supported and then some, don't really see a reason to change from Markdown, it's simplistic and support what's needed.

I would reserve something bigger for a forum or community area.
