### ISSUE TITLE
Suggestions for the site

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#179]
So I have few suggestions, so of them may or already were suggested but I think I should take the opportunity to put them all in one place.

1. Change the site's background colors (one for normal version and one for sukebei) and by sure to add color in the commit's window since all of this white background get mixed with the commit's window (Honestly all of this white make my eyes burn... it may be the default color of github but just white and black feel too poor and lifeless compared to the old nyaa (just make sure that sukebei and nyaa have different colors and backgrounds so they won't look identical if you going to do it). 

2. Add subscribe system, it was really useful in old nyaa.

**Comment by TheAMM** [comment]
#75 & #118.
I'm not really sure how Github is relevant here?
