### ISSUE TITLE
Allow users to modify/add/remove trackers of their existing torrents

### ISSUE THREAD

**Issue by nyaadev** [nyaadevs/nyaa#19]
Since we are already storing trackers in the database this should be relatively straight-forward to implement.
I'm thinking of a table where the rows have the tracker urls in them and an X for delete.
User can delete rows, modify them and move them around to change the priority.
Adding new rows should also be possible.
User trackers should be limited to 10 to avoid spam, and a captcha should probably also be present to avoid spammers inserting trash into our database.
Simple url validation should also be added (urllib.parse?)

HTML mockups very much welcome!

**Comment by EduenSarceno** [comment]
I agree, some clients doesn't let change the order priority of the trackers, some users doesn't know how put nyaa tracker as first option in their torrents.

I know that the trackers list is inside of .torrent file, why not only parse de binary format  y change it?, we don't expose de database.

**Comment by ryanolee** [comment]
How about something like this?
[https://mega.nz/#!yp4EnIDK!lMYEecBTsqM7zPLvBPQzsNInqHkEo3VjcY4l2zHc9MQ](url)

**Comment by HitmanJ** [comment]
Why don't you try that here, @ryanolee https://codepen.io/

**Comment by ryanolee** [comment]
[Like this](https://codepen.io/anon/pen/NjzKGZ)

**Comment by TheAMM** [comment]
Linking this to #117 which would validate and allow the user to adjust trackers on upload.
