### ISSUE TITLE
Two issues still existing...

### ISSUE THREAD

**Issue by catshitz** [nyaadevs/nyaa#190]
1. Too many random Error 502 (Bad gateway), especially when searching and opening the torrent pages;
![image](https://cloud.githubusercontent.com/assets/18102209/26458918/4f96292e-41a7-11e7-9e0c-249b7b9fa677.png)
2. Missing a lot of old sources, such as Maho.sub ones.

**Comment by aldacron** [comment]
Hmm, what times were you hitting those 502 errors? Are you _still_ seeing them or just randomly during a period of time?

**Comment by ReimuHakurei** [comment]
We have everything that exists in any of the available data dumps. 

The 502s should be mostly solved. Forcing a refresh (Ctrl F5) should normally fix those.
