### ISSUE TITLE
Category parameter is doubled when searching

### ISSUE THREAD

**Issue by Nath789** [nyaadevs/nyaa#193]
When searching, an extra parameter c=0_0 (all categories) always appear first so whenever searching for a different category, it stays at all categories.
For example: [?q=&f=0&c=0_0&c=2_0](https://nyaa.si/?q=&f=0&c=0_0&c=2_0)

**Comment by TheAMM** [comment]
3bd4898 above is quick fix  but a better solution is being worked on.

**Comment by ReimuHakurei** [comment]
This was fixed ages ago, so closing this issue.
