### ISSUE TITLE
Trying to log in with my email and i can't log in.

### ISSUE THREAD

**Issue by Shirokishi** [nyaadevs/nyaa#198]
So i have registered my username and i am always entering here at nyaa.si with my email but now i can't log in with my email i am always taking an error message "Your username must only consist of alphanumerics and _- (a-zA-Z0-9_-)"

I have an hour or so that i can't log in. I cleared all my cache memory i did a hard refresh on the page but nothing! 

I hope that you will able to fix this problem. 

Thank you!

**Comment by TheAMM** [comment]
Try logging in with your username, or contact us on `#nyaa-dev@irc.rizon.net`. We fixed a thing earlier but apparently nobody continued with the followup of fixing the login form.

**Comment by sharkykh** [comment]
@TheAMM 
Looks simple... [forms.py#45](https://github.com/nyaadevs/nyaa/blob/b6ecad898d57213c53034d399cd8e75423d9dd02/nyaa/forms.py#L45) should include `Email()`

**Comment by Shirokishi** [comment]
People help me out i don't know those codes...

I am just trying to log in via email (that i registered) and nothing!
I am trying to enter with my username and with the password of the email that i registred with and also nothing!

**Comment by Shirokishi** [comment]
hmm.... i thing that the email isn't able to connect i just cleared once again cache of chrome and ad a hard refresh ctrl+f5 and i add my username and the password and it seems that i logged in...

**Comment by TheAMM** [comment]
An email has characters outside the specified (`a-zA-Z0-9_-`) - `@`. The login field validator will be fixed soon-ish.

**Comment by TheAMM** [comment]
This was fixed in d89f74893ba48a8a3415ab7d3a4a3273031df917
