### ISSUE TITLE
[Feature request] Filterable RSS Feed

### ISSUE THREAD

**Issue by KibaNoOu** [nyaadevs/nyaa#200]
Hi, would be awesome to have **filterable RSS feed** like the one that once was on nyaa.se, cause trying to use the old parameters on actual RSS feed doesn't work well.

For example:
http://www.nyaa.se/?page=rss**&cats=**1_37&filter=1**&term=**[HorribleSubs] Hunter X Hunter 720p

**Comment by sharkykh** [comment]
Category IDs are different from NyaaTorrents.
Just search normally on the site, filter however you like, then click on the RSS button. You will get the correct link.

**Comment by KibaNoOu** [comment]
Ok thanks, didn't see that.
I'll check if in Synology Download Station the RSS is read correctly.
