### ISSUE TITLE
Unable to load feeds in RSSOwl

### ISSUE THREAD

**Issue by CubeTheThird** [nyaadevs/nyaa#202]
I use the feed client RSSOwl, and for some reason the feeds generated by nyaa.si aren't able to be read there. The client points to a [validator site](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fnyaa.si%2F%3Fpage%3Drss%26q%3Dberserk%26c%3D0_0%26f%3D0%26u%3DHorribleSubs) (pretty outdated) in regards to the error. The message it generates is:

> Server returned [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

While checking similar sites to validate RSS feeds, I found a [similar one](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnyaa.si%2F%3Fpage%3Drss%26q%3Dberserk%26c%3D0_0%26f%3D0%26u%3DHorribleSubs) which has some recommendations for general compatibility (though I don't know if this will correct the issue).

The feed URL that I'm testing against is https://nyaa.si/?page=rss&q=berserk&c=0_0&f=0&u=HorribleSubs, though the result is the same regardless which variant I have attempted to use.
I use [RSSOwl](http://www.rssowl.org/) as it's the only client I've used on Linux that actually works well (despite it not having been updated in years). It's been able to handle every feed I've thrown at it thus far.

**Comment by ReimuHakurei** [comment]
That particular error means that your RSS client doesn't support TLS, only SSLv3. For security reasons, SSLv3 is disabled on most modern websites due to being ancient. 

The creator of your RSS client will need to update it.

**Comment by ReimuHakurei** [comment]
It is also of note that our HTTPS configuration is handled by CloudFlare so it is impossible for us to fix this.

**Comment by sharkykh** [comment]
@CubeTheThird 
Seeing how RSSOwl is almost 3.5 years old, I'd say the client is outdated and that's probably the reason,
so you should use another, sorry.

P.S
I just downloaded it myself and got the same error.
It's also worth mentioning that I tried ShowRSS.info's feed, and got the exact same error.
http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fshowrss.info%2Fother%2Fall.rss

**Comment by CubeTheThird** [comment]
That seems very strange. While checking all of my existing feeds, I have confirmed that I do have some that connect using https, however upon further inspection it seems they are not in fact using TLS, so the diagnosis appears to be correct. I'm all ears for a client on Linux that supports it. Thanks for the feedback though.
