### ISSUE TITLE
[Request] Dark Mode for the site

### ISSUE THREAD

**Issue by BiddinWar** [nyaadevs/nyaa#203]
Would it be possible for you to introduce a button of sorts to enable a darker layout of the page?

**Comment by TheAMM** [comment]
Are you serious?
![image](https://cloud.githubusercontent.com/assets/6820963/26524925/f9a7cfb4-434e-11e7-8520-48a1923a2aeb.png)

**Comment by BiddinWar** [comment]
Yes.. I am since its not there for me...

**Comment by TheAMM** [comment]
The link exists in [the htnl.](https://github.com/nyaadevs/nyaa/blob/master/nyaa/templates/layout.html#L300). Verify you're on the correct site and paste a picture.
