### ISSUE TITLE
Cannot search result not found

### ISSUE THREAD

**Issue by dvdvideo1234** [nyaadevs/nyaa#205]
__Steps to reproduce__
1. Go to [Nyaa](https://nyaa.si/?q=&f=0&c=1_2)
2. Search for [Busou Shoujo Machiavellianism](https://nyaa.si/?q=Busou+Shoujo+Machiavellianism&f=0&c=1_2) (Displaying results 0-0 out of 0 results.)
3. Seach for [Busou Shoujo](https://nyaa.si/?q=Busou+Shoujo&f=0&c=1_2) (Displaying results 1-56 out of 56 results.)
4. Search only  [Machiavellianism](https://nyaa.si/?q=Machiavellianism&f=0&c=1_2) (Displaying results 0-0 out of 0 results.)
5. Probably pattern related bug in
https://github.com/nyaadevs/nyaa/blob/d89f74893ba48a8a3415ab7d3a4a3273031df917/nyaa/search.py

**Comment by TheAMM** [comment]
"Machiavellianism" is 16 letters, going over the ngram limit of 15 (see es_mappings.yml"). We'll look into it, for now you can do "Machiavellianis".

**Comment by aldacron** [comment]
what the fuck fucking elasticsearch >:(

**Comment by aldacron** [comment]
seems like there's no easy way out, but to use multi-field mappings:

https://discuss.elastic.co/t/edgengram-filter-not-keeping-the-whole-words/12951/2

**Comment by TheAMM** [comment]
I fixed this locally ages ago but other stuff popped up. Multi-field is the way to go.
