### ISSUE TITLE
getting a 403 triying to query website.

### ISSUE THREAD

**Issue by yonson2** [nyaadevs/nyaa#207]
When I try to `curl` your website I'm stumbled with a 403 error returned by cloudflare.

```ssh
 ~ curl -I http://nyaa.si
HTTP/1.1 301 Moved Permanently
Date: Sun, 28 May 2017 20:08:07 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d6f2d0ddc47297c2d5fdf2b3147630ad81496002087; expires=Mon, 28-May-18 20:08:07 GMT; path=/; domain=.nyaa.si; HttpOnly
Location: https://nyaa.si/
Server: cloudflare-nginx
CF-RAY: 3663d815118d547a-MAD

```
Maybe you could lower the spam protection level?

**Comment by yonson2** [comment]
More specifically, I'm getting a Cloudflare captcha, which I can't solve as I'm on console.

**Comment by TheAMM** [comment]
That `curl -I` doesn't tell anything other than you being redirected to `https://nyaa.si/`.
We don't have IMUA active, so it seems like your IP got flagged.

**Comment by CounterPillow** [comment]
```
$ curl -I https://nyaa.si 2>/dev/null | head -n 1                        
HTTP/2 200
```

works fine for me too. I don't even get a CAPTCHA when using Tor, so it seems like cloudflare flagged your IP for a good reason.

**Comment by yonson2** [comment]
Thats unfortunate then, I'll look further into the issue within my machine then, thanks for the info.
