### ISSUE TITLE
RSS feed redownload after update

### ISSUE THREAD

**Issue by Goten87** [nyaadevs/nyaa#209]
i think when u guys push a update the RSS feed will get screwed up i have had a lot of time the RSS links not working correct and redownloading all the anime on it 

`https://nyaa.si/?page=rss&q=[HorribleSubs]+Eromanga-sensei+-+*+[720p].mkv` is 1 of the links that i use for downloading but as of 29-05-2017 14:45 its showing other shows like koro-sensei quest and 100% pascal-sensei

is there somthing u can do about it :(

**Comment by TheAMM** [comment]
Use a plainer search: `https://nyaa.si/?page=rss&q=Eromanga+sensei+720p&c=0_0&f=0&u=HorribleSubs` and read the [Elasticsearch query syntax docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#_simple_query_string_syntax) to know how to use the search better in the future.
