### ISSUE TITLE
Reclaiming torrents

### ISSUE THREAD

**Issue by Bl4Cc4t** [nyaadevs/nyaa#21]
It may be a large request, but editing stuff you previously uploaded would be superb.
Nearly all descriptions (if not all) are messed up and not even up to date.
Verifying the identity would be a major problem though.

**Comment by nyaadev** [comment]
We will upload the old uploader names to the torrents later.
From there on it will be a manual verify and update process through IRC.
It will take a few days time.

**Comment by HitmanJ** [comment]
Would it be possible to rename those old users to an existing account/user? My current username is different than my Nyaa username, but I'd like to take control of my old torrents/account. That's why I'm asking.

**Comment by prnceichiro** [comment]
Yeah I agree with @HitmanJ. I've changed my username. I wonder how will be the process of validation will be.

**Comment by Nazonaze** [comment]
You can now handle torrent reclamation by joining the project IRC channel (#nyaa-dev @ irc.rizon.net) and checking the instructions in the topic.

**Comment by marconii2002** [comment]
Can you add opion to reclaim torrents also on sukebei ?

**Comment by aldacron** [comment]
As Nazo mentioned, please join #nyaa-dev@irc.rizon.net to reclaim your torrents. I think Sukebei support is being added as well.
