### ISSUE TITLE
List external torrents

### ISSUE THREAD

**Issue by basvdelsen** [nyaadevs/nyaa#210]
Thought it would be convenient if torrents from other sites are also shown and downloadable in the search results. animetosho.org does this too but their search filters are crap. This would mean you'd have all available torrents in nyaa.si and no longer need to check other torrent sites in case you can't find it. 

Added to that, maybe you can also include streaming sites results like 9anime.is and instead of torrent or magnet link add the direct download links. This is convenient for when you're looking for old unseeded anime and the streaming sites are your only option.

**Comment by wiiaboo** [comment]
You're thinking of an indexing site, not a tracker.

**Comment by TheAMM** [comment]
I get the idea you're after but like wiiaboo said, we're more about being *us* and not trying to index everything.

*Streaming...*

**Comment by basvdelsen** [comment]
Okay, got it, just thought I'd throw it out there.
