### ISSUE TITLE
[Feature] Register as seeder and request seed

### ISSUE THREAD

**Issue by AkatsukiNin** [nyaadevs/nyaa#213]
As the title suggest registered users can register themselves as a seed on any specific torrent by clicking a button.
And there would be another button which would send some kinda notification to all users who are registered as seed on that torrent. Used by someone trying to download an inactive torrent.
Reason : People can't be seeding all their anime all the time.
I guess most users only seed popular ones thus leaving a lot of torrents of 0 or few seeds.
This feature will give a way to let users know when someone is trying to download a torrent they have already downloaded but it's stopped in their torrent client.

**Comment by CounterPillow** [comment]
Or just don't stop torrents in your torrent client? What's the point of disabling an automatic mechanism and then adding a manual mechanism to half-arsedly replicate that?

**Comment by Hamuko** [comment]
If you are not seeding a torrent, you are not a seed. Just don't stop the torrent and people can actually know that you are a seed who is actually seeding.

**Comment by AkatsukiNin** [comment]
Leaving all torrent seeding will
1. hog all the bandwidth
2. require them all to be present of laptop/desktop HD
I have most of animes in external and I surely don't wanna seed from there 18h a day.

**Comment by Hamuko** [comment]
You can't seed without using bandwidth and you can't seed without the files. If you can't seed, you shouldn't be listed as a seed.

**Comment by CounterPillow** [comment]
>hog all the bandwidth

If they're not well-seeded, then they're not going to hog "all the bandwidth". If you're really concerned about that, you can use a client that lets you enable torrent queueing.

>require them all to be present of laptop/desktop HD

so instead of fixing your storage setup to something more sane, either by having networked storage or just getting larger internal storage, you ask for a completely redundant feature that probably only you will ever use?

**Comment by TheAMM** [comment]
I get the idea and seed requests would be a neat feature (neat techwise, neat to implement, like we could use an optional passkey on announce to connect peers to accounts etc) - but the thing is we're not a private tracker.

And like it's been said here, if you can't seed then you can't seed. How torrents usually work is that someone will grab the seedless torrent, keep it in their client and hope that a seed will eventually appear.
What reason does a user have to check for seed requests? This really works better on sites with enforced ratio or some other reward for seeding; but Nyaa here is public.

What you can do @AkatsukiNin is keep the torrent in your client and refresh the announce. Your client should show seeds/leeches for the torrent (even when stopped!), and if it's 0/1 you'll know it's time to go and save the day.
