### ISSUE TITLE
GFM Markdown Tables are not working in torrent descriptions

### ISSUE THREAD

**Issue by CounterPillow** [nyaadevs/nyaa#215]
Github-flavoured Markdown tables are not being rendered in torrent descriptions.

Here's an example:

```
| No. | Title                             | Length |
| ---:|:--------------------------------- | ------:|
|  1  | Foo                               | 3:25   |  
|  2  | Bar                               | 3:35   |  
```

Should render as 

| No. | Title                             | Length |
| ---:|:--------------------------------- | ------:|
|  1  | Foo                               | 3:25   |  
|  2  | Bar                               | 3:35   |  

It does, however, result in plain-text output instead.

**Comment by sharkykh** [comment]
The reason it doesn't work is because the site uses pure Markdown (CommonMark), and not GFM which is based on the CommonMark Markdown specification.

**Comment by CounterPillow** [comment]
Yeah, but it would be nice if it did. I know this is non-trivial since it would require changing the markdown renderer.

**Comment by sharkykh** [comment]
[Markdown-it](https://markdown-it.github.io/) supports it. But I don't know if the team wants to switch from pure CommonMark.
