### ISSUE TITLE
Any chance that you can add the category tag to the torrent page as well?

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#228]
Any chance that you can add the category tag to the torrent page as well? I think it was like that in old nyaa and even if wasn't there's one rule my eyes keep follow: "One picture worth thousand of words"

When everything is in pale words and in big resolution it look so god dam small to the point the eye can miss it  or mistake it to something else easliy unless if there's proper location and color to it.

Adding the tags will give people easy time noticing what kind if category they currently watching

So any chance you will consider it?

![0](https://cloud.githubusercontent.com/assets/14190834/26644327/08d0f380-463d-11e7-8aee-e41ff4046c91.PNG)

![1](https://cloud.githubusercontent.com/assets/14190834/26644336/0be5913e-463d-11e7-9104-f700046e2aab.PNG)

(Also talking about colors... will it hurt somebody to add porper background to both sukebei and the normal site? :0 they both can have different backgrounds so we won't mistake the two even by small chances, only white and black is so pale >.> )

**Comment by sharkykh** [comment]
I personally don't see a _nice_ way for it to fit in the current style
![image](https://cloud.githubusercontent.com/assets/10238474/26645222/086dc870-4640-11e7-9d34-7630801c46e2.png)

> (Also talking about colors... will it hurt somebody to add porper background to both sukebei and the normal site? :0 they both can have different backgrounds so we won't mistake the two even by small chances, only white and black is so pale >.> )

This was suggested in #75, and is now a WIP over at #206

**Comment by egozi44** [comment]
Still better than nothing if you ask me, you won't mistake it to other category thanks to the fact each catergory icon have differnt color and different drawing on it

**Comment by egozi44** [comment]
Btw, adding color to differnt section can also help things get less mixed, similar to old nyaa
![torr1](https://cloud.githubusercontent.com/assets/14190834/26646190/649eb6e2-4643-11e7-99dc-be94656b2dd7.jpg)

**Comment by Cloudef** [comment]
@sharkykh how about the left or right side of the torrent title bar?

**Comment by sharkykh** [comment]
Tried that. It's too big and doesn't look right to me.

**Comment by Cloudef** [comment]
Probably the design of those buttons could be changed to be bit smaller and maybe less round / better borders, to fit with different elements better. That's some work though.

**Comment by ScreamingHawk** [comment]
Would really like this to added. 

What about this? 

![image](https://cloud.githubusercontent.com/assets/1460552/26817281/11ad7b98-4aea-11e7-995c-adc67fc28aef.png)

Also as per @Cloudef, @sharkykh didn't like it but I think this looks good

![image](https://cloud.githubusercontent.com/assets/1460552/26817347/5063b316-4aea-11e7-9fbb-ec6e7907e33f.png)

**Comment by egozi44** [comment]
yea imo it look good too

**Comment by TheAMM** [comment]
I don't like either of those, the icon seems tacked on in both of them. The latter is better of the two, but no, not like this.

**Comment by Arylide** [comment]
This looks bad no matter how you do it.

**Comment by egozi44** [comment]
Alright~
