### ISSUE TITLE
Date、Size、page filter in RSS

### ISSUE THREAD

**Issue by vi000246** [nyaadevs/nyaa#232]
Origin Nyaa have date and size filter.
usage:
   date filter :    search between 1day and 7days old record
       https://sukebei.nyaa.si/?page=rss&minage=1&maxage=7
   
   size filter :    search between 100MB and 500 MB record
       https://sukebei.nyaa.si/?page=rss&minsize=100&maxsize=500

And I found RSS cannot jump to another page.
Hope can add querystring to search page in RSS
ex.
       ?page=rss&p=3
jump to third page.

**Comment by aldacron** [comment]
RSS is not meant to be a search API. We limited it to the latest X releases. We'll be planning on adding a search and size filter... sometime soon.

**Comment by Tsubasaza** [comment]
Would be great if you could add "type of file" in the RSS. I've been automatically downloading .malicious files that's labelled as "[xxx]okoak_episode_52.mkv.exe" and I wish to avoid it.

**Comment by CounterPillow** [comment]
@Tsubasaza restrict your RSS filter to only apply to a certain user instead of every torrent with that group's tag. That being said, this is unrelated to this issue.
