### ISSUE TITLE
Uploading torrents lack some options

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#233]
1. You can't delete torrent you uploaded
2. You can't edit your own torrents
3. You should add tags info so people will know what tags they can use

**Comment by TheAMM** [comment]
1. You can delete a torrent you uploaded, if you uploaded it while logged in. (However, this is not a real nuke-from-db yet.)
2. You can edit a torrent you uploaded, if you uploaded it while logged in.
3. Tags info? If you mean the torrent flags, hover your mouse over them and keep an eye out for the help page when it'll get some updates.

**Comment by egozi44** [comment]
then how come I can't find these options?

and I meant the tags/flags you add when you want to add let say image or link, I tried the normal [img][/img] and it didn't worked, in old nyaa they said what tags they support on the torrent upload page, you may want to do the same

**Comment by sharkykh** [comment]
> then how come I can't find these options?

Edit button is a pencil to the left of the torrents name. It should show up if the torrent is yours.

> and I meant the tags/flags you add when you want to add let say image or link, I tried the normal [img][/img] and it didn't worked, in old nyaa they said what tags they support on the torrent upload page, you may want to do the same

That is called BB-Code. The site uses Markdown (just like Github)

The help page on the site will have more info about it as soon as it gets updated to latest version.
***

### Styling Descriptions and Comments
<p>You can style your comments and your torrent's description using	<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown	</a>. This includes adding images or linking to external websites.</p><p>	To link to an external site, use <kbd>[label of link](https://example.com)</kbd>	where the text in the <kbd>[]</kbd> square brackets is the shown text of your	link, and the URL in the <kbd>()</kbd> parentheses is the URL your link will	point to.</p><p>	Embedding an image is similar. Use <kbd>![alt text](https://example.com/image.jpg)</kbd>	to have an image embedded in your comment or description. Note the <kbd>!</kbd>	exclamation mark at the beginning, denoting that this link is an image.</p>

**Comment by egozi44** [comment]
I see, thanks.

maybe you should consider add buttons so we could use the BB-codes more easily

**Comment by TheAMM** [comment]
We *do not* support bbcode, @egozi44. You can google what `markdown` in the `Description (markdown supported)` means while waiting for the site to be updated to the latest commits, which includes a link above the editor.

**Comment by egozi44** [comment]
either way you can add buttons to make our lifes easier, some other sites already done it >.>

**Comment by egozi44** [comment]
I think you should moved the codes back to how they were casue now 99% of the site don't display image previews anymore and just links.

**Comment by TheAMM** [comment]
I'm going to need some actual data on that, @egozi44. Markdown images work just fine on the live site.

**Comment by sharkykh** [comment]
@egozi44 
Are you talking about the BB-code tags (like [img], [url=]) that don't work?

**Comment by egozi44** [comment]
> I'm going to need some actual data on that, @egozi44. Markdown images work just fine on the live site.
Seem like that issue is only for IE, yet there some random links (that probably relate to old nyaa) that won't show up.
![hgfhgf](https://cloud.githubusercontent.com/assets/14190834/26757718/f7e19d92-48ce-11e7-8ddb-410fb577756a.PNG)

And yea conversion will probably fix these rare random links, in IE however nothing works at all (and worked just fine few days ago)

I personally still not used to Markdown and don't sure how their code work compared to BB-codes

**Comment by egozi44** [comment]
no plan to fix the IE support?

**Comment by sharkykh** [comment]
What IE version are you using?

**Comment by egozi44** [comment]
10 cause 11 sort of have random bugs on my os

**Comment by sharkykh** [comment]
For reference:
![image](https://cloud.githubusercontent.com/assets/10238474/26804132/95faf5ec-4a4f-11e7-8b93-c1ae93a620e4.png)

Working on it. But I really don't want to install IE...

**Comment by egozi44** [comment]
anything I can help with?

(ps love ZnT)

**Comment by sharkykh** [comment]
@egozi44 Nah it's okay. I have MS Edge 38 on my laptop, that's close enough, I hope.
@TheAMM (Since it's your code) Apparently, `for (var val of iterable )` is only supported in chrome/firefox.

**Comment by sharkykh** [comment]
I opened #246

**Comment by TheAMM** [comment]
2017 and **still the damn IE just when I'm thinking I vould just for...of for once**

**Comment by sharkykh** [comment]
I concur...

**Comment by egozi44** [comment]
I blame MS for not giving us proper successor for win7 xD
