### ISSUE TITLE
Suggestion: Disable/change cloudflare protection on RSS page

### ISSUE THREAD

**Issue by throwaway7** [nyaadevs/nyaa#234]
Hello,

I'm using Taiga to automate my downloads for airing shows, but It's incompatible, as it required JS validation.

Given that you guys were the only ones providing actual torrent files instead of magnet links, this breaks any existing automation setups with Taiga.

I suggest working together with the developer: https://github.com/erengy/taiga

Thanks.

**Comment by TheAMM** [comment]
Add `&m` or `&magnets` to your RSS feed. The RSS feed should (as in "I am pretty sure it is") be excluded from CF's IMUA already.

**Comment by CounterPillow** [comment]
Is there any particular reason as to why "I'm under attack"-mode applies to the torrent file links? Torrent files could/should just be served by a static server and ideally be cached by cloudflare.

**Comment by TheAMM** [comment]
Out of my hands.

**Comment by snowfag** [comment]
The rss page and torrent links are excluded from IUAM and have been for some time (they weren't for a bit due to the url changing and no one mentioning it to the people that could update the page rule)
