### ISSUE TITLE
[Feature Request] Remember last search category used and auto-select it

### ISSUE THREAD

**Issue by lubien** [nyaadevs/nyaa#242]
I don't know if this cenario represents what other users face but in my case, everytime I open Nyaa my first move is to change category to `Anime - English Translated`. To lessen the boilerplate I made a hacky userscript that fits my need as simple as:

```js
(function() {
    document.querySelector('#navFilter-category li:nth-child(4) a').click()
})();
```

Where the category 4 is the desired one.

With that in mind I tought this could be useful for more users if done right like remember the last clicked category and auto select it (instead of mine that always select the fourth).

This could be easily handled in the front-end using localstorage API to set/get the category, a listener to category clicks and a DOMContentLoaded listener to set the category after the DOM is ready.

Let me know if you think this could be an useful user experience feature :D

**Comment by Arylide** [comment]
I know your issue was first, but it looks like people are using #343 for this, and it seems to be the same issue.
