### ISSUE TITLE
About the search results RSS feed get number.

### ISSUE THREAD

**Issue by phase-eight-corvenik** [nyaadevs/nyaa#245]
Hello!
I can acquire only the first page when I display the RSS of search results.
I cannot acquire the second page, the third page result.
Unable to retrieve all of the results?

**Comment by sharkykh** [comment]
Did a quick search for `rss page`:
https://github.com/nyaadevs/nyaa/issues/232#issuecomment-306108879

**Comment by aldacron** [comment]
what is the use case for having a 2nd page or a 3rd page result? RSS isn't meant to be a search API

**Comment by phase-eight-corvenik** [comment]
I searched it in "month" not a title in Audio category.
Like "[1704".
And I was going to download a result using RSS in a mass.
However, because more than 75 search results existed in  a month.
The contents after the 2nd page were not able to be downloaded from RSS. 
Therefore it allows you to choose the number of the RSS feeding.
Like　50,100…300(MAX).
