### ISSUE TITLE
Commit's window 

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#252]
Comment's window can't be dragged (so you can increase it's size)  in IE 
If you don't going to fix it or IE too old to support it I suggest to at least make the comment window bigger by default,

And the comment length limit user allow to write is too short (Had to split my to three parts cause 225 latters is the limit...)

**Comment by sharkykh** [comment]
You mean comment?

**Comment by egozi44** [comment]
opps, yup

**Comment by nyaazi** [comment]
I agree for the text area height, a quick fix: https://github.com/nyaadevs/nyaa/pull/253

Not so sure about the comment length, but I guess it can be bumped to 500 for example.

**Comment by egozi44** [comment]
I don't recall I ever reach the limit in old nyaa at all,  unless it didn't had limit (which I don't think is possible) the limit was very big, 500 and 200 sound like something that should fit to tweeter
