### ISSUE TITLE
RSS Feed - Error Downloading - (Nyaa Feed Example) - server replied (299)

### ISSUE THREAD

**Issue by JLChamberlain** [nyaadevs/nyaa#256]
Over the past couple of days my RSS reader has been bringing up these messages in the status saying that there was a error downloading the content. The issue goes away after a second refresh but then occurs on another feed. Any idea what could be causing this?, here is a few screenshots of RSS feeds bring up the error downloading message: 

Screenshots: https://imgur.com/a/UNUE5

**Comment by sharkykh** [comment]
Weird, 299 response code...
I still think the client is wrong, though.

https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
> 2xx: Success - The action was successfully received, understood, and accepted

Yet...
> 227-299	Unassigned

**Comment by JLChamberlain** [comment]
It only appears on Nyaa feeds. All my other feeds are working perfectly.

**Comment by sharkykh** [comment]
That's why I said "Weird, 299 response code...", since this response code is...
Rare, for the lack of a better term.

Nonetheless, it is **acceptable**,
meaning your client **should** accept it as a success.

**Comment by JLChamberlain** [comment]
It's strange because it has only been doing it this past week!, before that it had no status errors.

**Comment by TheAMM** [comment]
@JLChamberlain There's been some changes to the torrent download endpoint - is this issue still existing?

**Comment by sharkykh** [comment]
@TheAMM 
[This is about the RSS endpoint](https://i.imgur.com/FIOR2Zm.png).

**Comment by TheAMM** [comment]
See, unhibernating is a gradual progress. Question still stands, because nothing on our end would nor should result in `299`.

**Comment by sharkykh** [comment]
Oh, so maybe it's from a VPN or a proxy of some kind.
@JLChamberlain ?

**Comment by JLChamberlain** [comment]
I'm not using any VPN's or Proxy. This issue only appears with Nyaa Feeds, I do have a lot of Nyaa feeds in my RSS reader so could that cause an issue?

**Comment by sharkykh** [comment]
@JLChamberlain You mean like "Too many requests"?

**Comment by JLChamberlain** [comment]
I mean I have lots of individual Nyaa Feeds in my reader. Even though the reader retries multiple times of failure status the Nyaa Feeds now & then bring up that error in status.

**Comment by TheAMM** [comment]
I managed to replicate this in QuiteRSS just now. It may be a ratelimit on our nginx setup, but I can't verify that myself.

**Comment by sharkykh** [comment]
@TheAMM 
According to IANA, HTTP 299 is a valid success response. I still think QuiteRSS is doing something wrong.

**Comment by TheAMM** [comment]
True, QuiteRSS is handling the 299 wrong but there isn't any reason for the server to return 299 either.

**Comment by TheAMM** [comment]
Having a look into QuiteRSS code, this coooould be thanks to [QT itself](http://doc.qt.io/qt-4.8/qnetworkreply.html)? It may not be a HTTP status code which leads more credence to it being our ratelimit (I'm very sure it's configured to return 4XX or 5XX, *not* 299).

**Comment by sharkykh** [comment]
Nice catch!

**Comment by Hardantheweeb** [comment]
I don't know if this is related or not, but very often I get errors like this in qbittorrent: 
![rsserror](https://user-images.githubusercontent.com/3051951/28494169-744dd144-6f2f-11e7-8cbe-be2566f43bf4.png)

Can't find anything about in execution log, and to fix them I have to refresh the feed, sometimes several times until it works again.

**Comment by CatPlanet** [comment]
And here is my contribution: [http://i.imgur.com/gm7gIbd.png](http://i.imgur.com/gm7gIbd.png) from RSSOwl (java).

"Find out more goes stright" to [http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fnyaa.si%2F%3Fpage%3Drss%26c%3D1_2%26f%3D0](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fnyaa.si%2F%3Fpage%3Drss%26c%3D1_2%26f%3D0) which, for me, is [this](http://i.imgur.com/4loboI2.png)

**Comment by TheAMM** [comment]
Good info @CatPlanet - does that occur every time? RSSOwl seems to be using outdated SSL methods, and that validator seems to fail every time on the handshake as well. If possible, update or at worst, change your client. Outdated SSL isn't good.
The QuiteRSS/Qt error doesn't happen every time; it could be the SSL, but I don't know enough of SSL procedures to confirm that requesting multiple times would do this and that and so.
Anyhow, our code nor our site does nothing *wrong*, so not sure how to proceed with this. It's something that I'd like to solve but for now I'll just have to shrug until we know even more.

**Comment by JLChamberlain** [comment]
@CatPlanet - Just Change over to QuiteRSS. I was using RSSOwl before but it's support is out of date & cant support certain feeds.

**Comment by JLChamberlain** [comment]
I might forward this issue to the main staff working on QuiteRSS so if they can give some insight.

**Comment by CatPlanet** [comment]
@TheAMM every time. I've tried to poke RSSOwl's sourc code and update it to newest HttpClient library (possible culprit) but after 1.2k+ compilation errors I've given up. Every other feed (about 1k) are working flawless.

I'm not nay SSL expert but this seems like cause and might be worth investigating.

**Comment by TheAMM** [comment]
It's out of my hands, @CatPlanet, I've nothing to do with hosting.

**Comment by JLChamberlain** [comment]
One of the QuiteRSS contributors is going to look into this issue. I gave him the debug.log & hopefully he can explain why this is happening with Nyaa. Link to page: https://github.com/QuiteRSS/quiterss/issues/1001

**Comment by Hardantheweeb** [comment]
Seems like this only happens when you have more than five individual feeds. While keeping the feeds to five or under it works as intended, but when you add the sixth feed you start seeing the timeouts.

**Comment by TheAMM** [comment]
We did some prodding around, and have confirmed it's the ratelimit which will result in a [HTTP 429](https://httpstatuses.com/429). QuiteRSS and other clients do not seem comply with it. We may tinker with things a bit, but 429s are not some arcane magic anymore - they should be supported by clients, especially ones that fetch dozens of resources in one go.

**Comment by CatPlanet** [comment]
More insight. This is how main site looks in firefox's (newest version) MORE INFO tab:
http://i.imgur.com/U4rWA75.png

And this is when you visit whatever rss feed you use:
http://i.imgur.com/imKFWb1.png

(Sorry for browser not being in English but it should be self-explanatory)

Thing is that both use https protocol but, for some reason, there is no security attached to it.
Even more insight: I've crawled through nyaa and happened to notice that RSS page is ONLY one without security. Furthermore this is the ONLY page using _good_ old `?page=` syntax in it's url. I assume it's because faulty nginx route/rewrite/location/whatever-it-happens-to-actually-be configuration. Nyaa code is A-OK, server configuration is main culptit now. Maybe some magic cloudflare configuration but I'm willing to put all my chips on nginx.

**Comment by CatPlanet** [comment]
This would explain all those handshake failures along some applications - there couldn't be any handshake when SSL is basically absent. Java applications are quite sensitive in this regard because good old SDK is more than just eager to throw a tantrum if just one single thing is somehow oddish to it.

**Comment by CatPlanet** [comment]
And, of course http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fnyaa.si%2F%3Fpage%3Drss%26c%3D1_2%26f%3D0 with `GET_SERVER_HELLO` stating there was attempt to make secure connection with handshake from client but server has no hands.
