### ISSUE TITLE
Sonarr can't search on Nyaa.si

### ISSUE THREAD

**Issue by RacerBas** [nyaadevs/nyaa#262]
When the site just launched Sonarr saw the torrents but wasn't able to grab them.
At this moment it's completely unable to find any torrents at all

**Comment by sharkykh** [comment]
That's best directed to  [Sonarr](https://github.com/Sonarr/Sonarr/issues), so open an issue there...

**Comment by TheAMM** [comment]
Yeah, I haven't used Sonarr nor do I know how it grabbed torrents from our site before, so mention it to them.
