### ISSUE TITLE
Nyaa.se torrent uploads

### ISSUE THREAD

**Issue by xspitfire911** [nyaadevs/nyaa#268]
Hi people,

I was uploader on nyaa.se (rip) and now i want get back my torrents if possible ?

Thanks :3 and long life for nyaa.si <3

**Comment by sharkykh** [comment]
https://github.com/nyaadevs/nyaa/issues/21#issuecomment-301294864

**Comment by xspitfire911** [comment]
But their is no body in chat :'(

**Comment by sharkykh** [comment]
@xspitfire911 
Maybe you went into the wrong one?
Try https://kiwiirc.com/client/irc.rizon.net#nyaa-dev
