### ISSUE TITLE
Torrent Filtering (Outside Search)

### ISSUE THREAD

**Issue by cublikefoot** [nyaadevs/nyaa#272]
Hello,

One feature that the old Nyaa had was the ability to disable certain categories from appearing at all anywhere on the site. It was configurable from one's profile page (a series of checkboxes). I had used this to filter out non-english translated anime, raw literature, software, etc. It was really helpful in cutting down on the clutter while browsing.

**Comment by sharkykh** [comment]
I think this was suggested in #27.
