### ISSUE TITLE
Search field has an ungodly right padding

### ISSUE THREAD

**Issue by corbynj** [nyaadevs/nyaa#273]
![Screenshot](http://puu.sh/wu7hP/8310a39c5f.png)

.form-control.search-bar {
    -moz-box-ordinal-group: 4;
    border-left: 0 none;
    order: 3;
    padding-right: 4em;
    width: 99%;
}

Looks like this is built into bootstrap. Override this so the padding doesn't look awful.
![Screenshot-fixed](http://puu.sh/wu7DS/7fbbfb978e.png)

**Comment by sharkykh** [comment]
@CounterPillow 
That's correct, there's a commit that changes this in https://github.com/nyaadevs/nyaa/pull/241/commits/062d4ce9ea53e6514cc6935b7e68c906a703365e#diff-ccf45d2b7c2e00904639b9e6993ff642L163

**Comment by sharkykh** [comment]
Should be fixed by the next site update.
