### ISSUE TITLE
Feature Req - Add subscription feature to subscribe user

### ISSUE THREAD

**Issue by ahmeed-dhon** [nyaadevs/nyaa#281]
This is an old feature from old nyaa  
With this user can subscribe another user and got notification when the subscribed user post new torrent  
I really miss this feature

**Comment by sharkykh** [comment]
It's been discussed https://github.com/nyaadevs/nyaa/issues/118 & https://github.com/nyaadevs/nyaa/issues/244#issuecomment-306217430

> maybe perhaps someday, but not now.
