### ISSUE TITLE
[Suggestion] English translations must have the English track first.

### ISSUE THREAD

**Issue by such-doge** [nyaadevs/nyaa#282]
The current rules don't say that English-translated uploads have to have the English subtitle track as the primary track. I just came across an upload in which it wasn't. The uploader was clearly (though unsuccessfully) using this technicality to give his torrent more exposure. I don't know how common this is, but making this a reportable offense would help make the feed of English-translated uploads less cancerous.

**Comment by CounterPillow** [comment]
If it has an English track it's English translated, I don't see the issue? Any decent media player should allow you to default to a track based on the language of the track.

Rules like this will just mean that releases can't be posted in their original form over technicalities, which is stupid.

**Comment by FichteFoll** [comment]
Ideally, it would be possible to have a "category" (more like a multi-field) for every language, similar to what anidex is doing. "Non-english" is still pretty broad for a category when there are so many languages on this planet.

**Comment by mreweilk** [comment]
Guys this doesn't really go here, if you have suggestions for rules bring them to IRC and talk to us directly.
