### ISSUE TITLE
[Feature Request] Focus on search box upon loading

### ISSUE THREAD

**Issue by duyatran** [nyaadevs/nyaa#286]
As the title suggests, just a small convenient thing. After the page loads, cursor could be auto-focused in search box, and one can just start typing to search.

**Comment by CounterPillow** [comment]
I've been thinking of adding hotkeys to the site, which with a text box focused by default would be a little awkward. Instead, it could have a hotkey like `s` to focus the search box, would that be acceptable? This means you also won't have to use the mouse to begin searching, it simply adds another keypress.

**Comment by sharkykh** [comment]
@CounterPillow :+1: Hotkeys are cool. Especially for people who use the site a lot.

**Comment by duyatran** [comment]
Ah I see, that is more general a solution and also more convenient. Thanks a lot!

**Comment by mreweilk** [comment]
I think hotkeys might be a little much. 

I do like the idea of having the search box auto-focused though.

**Comment by mreweilk** [comment]
https://github.com/nyaadevs/nyaa/commit/c9389cb888c6924c4b180905c9061d2fc1ffcd76

Added autofocus. If you wanna do anything fancy like hotkeys make a pull request and we can discuss it there.

**Comment by mreweilk** [comment]
Actually nevermind seems like we aren't gonna go with this or hotkeys.
