### ISSUE TITLE
Getting "http error 0: No Response" error when adding torrents in Transmission

### ISSUE THREAD

**Issue by edwardz** [nyaadevs/nyaa#288]
When I try to add a torrent via URL in Transmission (Ubuntu 14.04) I get the error:
`Error: gotMetadataFromURL: http error 0: No Response`

**Comment by CounterPillow** [comment]
What happens if you try to run curl on the url you tried to add?

**Comment by edwardz** [comment]
Interestingly enough, curl had no issues.
```
$ curl --head https://nyaa.si/download/937524.torrent
HTTP/1.1 200 OK
Date: Mon, 10 Jul 2017 18:43:05 GMT
Content-Type: application/x-bittorrent
Connection: keep-alive
Set-Cookie: __cfduid=dc68d3c8c5a14a3b3e7a6632f3aeb5c3b1499712184; expires=Tue, 10-Jul-18 18:43:04 GMT; path=/; domain=.nyaa.si; HttpOnly
Content-Disposition: inline; filename="Isekai.Shokudou.S01E02.VOSTFR.720p.WEB-DL.H264-CR.torrent"; filename*=UTF-8''Isekai.Shokudou.S01E02.VOSTFR.720p.WEB-DL.H264-CR.torrent
X-Proxy-Cache: EXPIRED
CF-Cache-Status: MISS
Expires: Tue, 11 Jul 2017 02:43:05 GMT
Cache-Control: public, max-age=28800
Server: cloudflare-nginx
CF-RAY: 37c5aaa03f886c10-SJC
```

**Comment by ReimuHakurei** [comment]
What system are you running Transmission on? What OS and version of Transmission, etc.

**Comment by edwardz** [comment]
Ubuntu 14.04 (as stated in my original post) with Transmission 2.82. Happens both at home and at my work. Both machines use the same Ubuntu version.

**Comment by mreweilk** [comment]
Perhaps you're getting a cloudlare error?

**Comment by edwardz** [comment]
I can download the torrent just fine via browser. It's odd because this happens both at work and at home (different IP addresses).

**Comment by mreweilk** [comment]
Maybe someone else with 14.04 can chime in and test it. I'm on 16.04. 

Even so if the problem exists it's probably with Transmission 2.82.

**Comment by edwardz** [comment]
Do you guys happen to have a magnet feed? It will probably fix my issue since Transmission won't have to try downloading any torrents.

**Comment by ReimuHakurei** [comment]
I'll spin up an Ubuntu 14.04 box later tonight and give it a whirl.

**Comment by sharkykh** [comment]
@edwardz Add `&magnets` to the RSS url.

**Comment by pathsny** [comment]
Hi, just jumping in to say that I see the exact same error. Running Transmission on freebsd. The error is always "gotMetadataFromURL: http error 0: No Response"

**Comment by sharkykh** [comment]
>perhaps something to do with the http headers on the response?

Even if it isn't, [I think `inline;` isn't the right call](https://github.com/nyaadevs/nyaa/blob/2e8e5480676976af861e9e0e5a352a25355dd858/nyaa/routes.py#L820), but rather `attachment;`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body

**Comment by pathsny** [comment]
I just compared the headers with a couple of other sites and I notice two main differences
1) Content-Length is missing as a response header from nyaa.si
2) Content-Disposition is usually "attachment" as @sharkykh just mentioned.

**Comment by pathsny** [comment]
Just ran a test and noticed that some torrents on another tracker which use the "inline" Content-Disposition but do have Content-Length work fine. So perhaps the main problem is that Content-Length is missing?

**Comment by sharkykh** [comment]
@pathsny Thanks for testing.
I'll open a PR for it so it can be discussed.

**Comment by pathsny** [comment]
thanks. If you happen to have a publicly accessible test instance you can
spin up, do let me know. I can test it with both transmission and utorrent
and let you know if everything works correctly.

**Comment by sharkykh** [comment]
@pathsny I only have my local server.
I'm not a part of the nyaadevs team, but I don't think they have such a thing either.

**Comment by edwardz** [comment]
Thanks for helping confirm the issue @pathsny!

**Comment by pathsny** [comment]
Hi @sharkykh, I tested it and it works. Thanks for fixing it! Do you know when it goes live?

**Comment by TheAMM** [comment]
Whenever our server people get to it. Keep an eye out on the commit hash on the page bottom to see the current version:
![image](https://user-images.githubusercontent.com/6820963/28453943-f9c93630-6e01-11e7-90a3-f9a5592a472e.png)

**Comment by pathsny** [comment]
I'm sorry to report that this problem is still being reported by transmission (I see now that the updated prod version returns Content-Length). I guess our diagnosis was not correct. How hard would it be to also add the magnet url to the payload?

**Comment by sharkykh** [comment]
@pathsny 
That's too bad... Maybe this has something to do with Cloudflare.

> How hard would it be to also add the magnet url to the payload?

As I've previously said here, you can append `&magnets` to the generated RSS url to get all download links as magnet URIs.

**Comment by pathsny** [comment]
oh hah I missed that. thanks, let me see if that solves my problem for now. I'm very curious why this solution did not work though.

**Comment by sharkykh** [comment]
My Heroku test server didn't have Cloudflare and it worked for you...
That's why I'm leaning towards Cloudflare..

**Comment by pathsny** [comment]
that makes sense.

**Comment by sharkykh** [comment]
@TheAMM you might want to reopen this until we find the culprit.

**Comment by Arylide** [comment]
Try to upgrade your transmission version by using the PPA available from ubuntu. Supposedly 2.92(latest) works fine.
https://help.ubuntu.com/community/TransmissionHowTo#Add_Transmission_PPA_Repository

**Comment by Vulcannis** [comment]
Since this didn't fix the original issue, any chance to revert back to inline? Firefox forces a save dialog for attachments, which is annoying.

**Comment by TheAMM** [comment]
@Vulcannis Does it? I tested FF 54.0.1 (Windows) on the live site and my local dev with both `inline` and `attachment` - they both open the *Open in program/Save file (Set default...)* dialog for me. (Saving the file doesn't ask for a filename).
If the save dialog does happen then I'm all for going back to `inline`, but if it's not the cause it's an unnecessary change (and *downloads* should be `attachment`).

**Comment by Vulcannis** [comment]
Yes. https://bugzilla.mozilla.org/show_bug.cgi?id=453455
To be fair this is a problem with the FF browser, and one that can kind of be worked around with an extension. On the other hand, going back to inline would make us FF users happier. :)

**Comment by TheAMM** [comment]
@Vulcannis I can't replicate it on my laptop either (Ubuntu, FF 54). What configuration are you on?

**Comment by Vulcannis** [comment]
@TheAMM FF 54.0.1 Windows. I didn't explain completely and the bugzilla isn't immediately clear, but this is not for plain download but when you've set up the file type to open in an external application every time (via checkbox on download dialog or mime type.) `inline` will then do so, while `attachment` will force the dialog to open every time. I also tried following a simple anchor link (official ubuntu iso download) which didn't send a content-disposition and it worked as expected (didn't show dialog.)

As for whether downloads should be attachments, there's a lot of arguments for and against that in the bugzilla, but when I download a torrent I'm not looking to save it somewhere. I want it opened in my torrent client, and FF prevents that when using `attachment`.

**Comment by edwardz** [comment]
@Arylide I just tried to update my Transmission to 2.92 by adding the PPA and it's still having issues:
`** Message: Couldn't read "https://nyaa.si/download/945422.torrent": SSL handshake failed`

**Comment by TheAMM** [comment]
@Vulcannis Replicated and reverted in the above commit.

**Comment by Arylide** [comment]
Afraid I don't know then, I'd suggest upgrading to the newer Ubuntu LTS version if you are able, as far as I've seen it works there.

**Comment by CounterPillow** [comment]
fwiw, I've seen this error message with transmission when adding a torrent from a URL as well, on an up-to-date Arch Linux system. Trying it again usually resolves the issue for me, so I'm not sure if this is the same issue or just a hiccup that leads to a timeout. Never experienced this in qBitTorrent.

**Comment by doreenhui** [comment]
I also encountered the same problem, when pulling a seed to download no problem, and then when pulling will encounter such a problem, how to solve it?
