### ISSUE TITLE
Add I18n (Multi-Language support)

### ISSUE THREAD

**Issue by wenketel** [nyaadevs/nyaa#289]

**Comment by CounterPillow** [comment]
I'm against this, it's useless development effort that needs to be constantly updated by translators and just results in people submitting more reports and leaving more comments in languages that none of the moderators can understand. Essentially, it means every new feature needs to be translated into all languages.

**Comment by sharkykh** [comment]
While I think [i18n](https://blog.mozilla.org/l10n/2011/12/14/i18n-vs-l10n-whats-the-diff/) is cool, I agree with @CounterPillow .
More so, who would benefit from it? I mean, the vast majority of content is in English (plus Japanese).
Having the site in different languages when this is the case isn't that useful... just an opinion.

**Comment by Arylide** [comment]
CounterPillow said what needed to be said already. It isn't something we are considering for now. We may come back this another time.
