### ISSUE TITLE
No password reset funtcion

### ISSUE THREAD

**Issue by MarkJeronimus** [nyaadevs/nyaa#291]
I can't log in, and I can't find a password reset/recover function. That's an issue.

(offtopic: I could log in in februari)

**Comment by CounterPillow** [comment]
This site didn't even exist in February.

**Comment by sharkykh** [comment]
@MarkJeronimus Are you confusing Nyaa.se (the original NyaaTorrents) with Nyaa.si (this site)?
If so, you need to open a new account.

**Comment by TheAMM** [comment]
Although @MarkJeronimus may have confused .se and .si, issue is still valid - although a duplicate of #44.
