### ISSUE TITLE
Add Original Tracker to Magnet Links

### ISSUE THREAD

**Issue by ShardM** [nyaadevs/nyaa#293]
Magnet links do not add the original tracker, which makes it pointless if you are using for e-hentai torrent as the ehtracker is need to monitor download rate for credits. Also what happens if the original torrent uploader only uses the original tracker without the magnets trackers.

**Comment by FichteFoll** [comment]
You are not supposed to upload your "specialized torrents" of sites where rate monitoring is done. They specifically state that they are not for share. No idea if this is a general report or these are specifically stripped.

**Comment by TheAMM** [comment]
We don't store trackers in ElasticSearch (why would we?), so search listing can't use them. Fetching them from the database for ES results would be idiotic; having different magnet links depending on the page would be stupid; implementing user trackers in the magnets simply doesn't have anything going for us.

> Also what happens if the original torrent uploader only uses the original tracker without the magnets trackers.

The original torrent uploader will report to the site's main tracker, and everyone who adds the torrent from the site will have those added extra trackers - the original uploader can feel free to stay with their specialized trackers, but as we require the main tracker, that means the first one to finish their copy can share it to the extra trackers. They get used and the original seed is no longer really required.
