### ISSUE TITLE
Can't add torrent error: trackers not in torrent

### ISSUE THREAD

**Issue by checksum64** [nyaadevs/nyaa#294]
Trying to upload to Sukebei but can't seem to upload torrent. Error says:
"Please include http://sukebei.tracker.wf:8888/announce in the trackers of the torrent"
Can't seem to upload despite the torrent being created with the above tracker address. 

![capture](https://user-images.githubusercontent.com/30210020/28246458-7fd99950-6a6e-11e7-9a68-1b36f5be769a.PNG)

**Comment by CounterPillow** [comment]
The problem is that you have all of your trackers in the first tier.

**Comment by checksum64** [comment]
Thanks, sorted now. Cheers!

**Comment by TheAMM** [comment]
Linking this to #117
