### ISSUE TITLE
DB Create with utf8mb4 Charset

### ISSUE THREAD

**Issue by ghosotte** [nyaadevs/nyaa#296]
Hello,
I have a little problem when i try to run python db_create.py.

File "/root/.pyenv/versions/nyaa/lib/python3.6/site-packages/MySQLdb/connections.py", line 357, in set_character_set
    super(Connection, self).set_character_set(charset)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2019, "Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)")

I have the following version :
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for Linux (x86_64) using readline 5.1

I don't know how to install this charset.
Have you an idea ?

**Comment by sharkykh** [comment]
What charset did you set up the database with?

**Comment by ghosotte** [comment]
I did nothing for the charset.

I have modified the my.cnf.
I add :
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
init-connect='SET NAMES utf8mb4'
collation_server=utf8mb4_unicode_ci
character_set_server=utf8mb4
skip-character-set-client-handshake

----
I check :

MariaDB [(none)]> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |

I drop & recreate the database (like described in README.md)

But I have the same problem :/

**Comment by sharkykh** [comment]
[Do you actually have the character sets?](https://dev.mysql.com/doc/refman/5.7/en/cannot-initialize-character-set.html)
```bash
ls /usr/share/mysql/charsets | grep utf8mb4
```

**Comment by ghosotte** [comment]
Indeed, the files are missing.

ll /usr/share/mysql/charsets
total 236
-rw-r--r-- 1 root root 23500 Jul 10 06:53 Index.xml
-rw-r--r-- 1 root root  1749 Jul 10 06:53 README
-rw-r--r-- 1 root root  5526 Jul 10 06:53 armscii8.xml
-rw-r--r-- 1 root root  5512 Jul 10 06:53 ascii.xml
-rw-r--r-- 1 root root  8241 Jul 10 06:53 cp1250.xml
-rw-r--r-- 1 root root  8365 Jul 10 06:53 cp1251.xml
-rw-r--r-- 1 root root  5569 Jul 10 06:53 cp1256.xml
-rw-r--r-- 1 root root  8902 Jul 10 06:53 cp1257.xml
-rw-r--r-- 1 root root  5506 Jul 10 06:53 cp850.xml
-rw-r--r-- 1 root root  5528 Jul 10 06:53 cp852.xml
-rw-r--r-- 1 root root  5613 Jul 10 06:53 cp866.xml
-rw-r--r-- 1 root root  6529 Jul 10 06:53 dec8.xml
-rw-r--r-- 1 root root  5516 Jul 10 06:53 geostd8.xml
-rw-r--r-- 1 root root  5728 Jul 10 06:53 greek.xml
-rw-r--r-- 1 root root  5517 Jul 10 06:53 hebrew.xml
-rw-r--r-- 1 root root  5502 Jul 10 06:53 hp8.xml
-rw-r--r-- 1 root root  5529 Jul 10 06:53 keybcs2.xml
-rw-r--r-- 1 root root  5510 Jul 10 06:53 koi8r.xml
-rw-r--r-- 1 root root  6532 Jul 10 06:53 koi8u.xml
-rw-r--r-- 1 root root  9816 Jul 10 06:53 latin1.xml
-rw-r--r-- 1 root root  7238 Jul 10 06:53 latin2.xml
-rw-r--r-- 1 root root  5515 Jul 10 06:53 latin5.xml
-rw-r--r-- 1 root root  7438 Jul 10 06:53 latin7.xml
-rw-r--r-- 1 root root  8047 Jul 10 06:53 macce.xml
-rw-r--r-- 1 root root  8058 Jul 10 06:53 macroman.xml
-rw-r--r-- 1 root root  6530 Jul 10 06:53 swe7.xml

date
Tue Jul 18 14:40:03 EDT 2017

I installed mysql then mariadb only today :D

**Comment by sharkykh** [comment]
@ghosotte I might be wrong, sorry, I'm no expert. This could mean nothing...

**Comment by ghosotte** [comment]
No problem ! Thank you for you time :)
I will update my post when i will find.

**Comment by sharkykh** [comment]
Sure.
Could you try using `utf8mb4_bin` like me?

**Comment by ghosotte** [comment]
So, a sysadmin helped me quickly.
He has modified the config.py (change the encoding to utf8)  and reverted the my.cnf file.
The install is OK.
It seems a quickfix, but for now it is working.
