### ISSUE TITLE
Add more information to rss feed description field?

### ISSUE THREAD

**Issue by Hampster82** [nyaadevs/nyaa#299]
Would it be possible to add some torrent info in the "description" field for those of us who don't use the rss feeds in torrent clients?

For example, this is what waffles has on theirs for music. Obviously not all of it would be relevant for nyaa, but it would certainly be nice to have a bunch of info at a glance and a quick way to get back to the site from the rss client, for example.

Link: Description/Comments Page
Genre: Video Game Music
Year: 2002
Size: 472125366
Link: Download Torrent
Seeders: 10
Leechers: 1
Format: FLAC
Link: *Anonymous* (Uploader)
Comments: 0
Files: 41
Bitrate: Lossless

**Comment by sharkykh** [comment]
I can maybe see reason for adding:
* `<nyaa:files>` (as in file count)
* `<nyaa:uploader>` (as in uploader username)
* `<nyaa:comments>` (as in comment count)

Other than that, at least from the example you provided,
it's either already available or not applicable (like Bitrate and Format)

**Comment by Hampster82** [comment]
I'm not talking about adding more <nyaa:blaa> fields, but rather using the standard <description> field for plaintext info and a few hyperlinks.

**Comment by sharkykh** [comment]
Oh, okay.
Description tag isn't being utilized ATM, so it can be done.
About the links, there's already a download link in `<link>` and an info link in `<guid>`.

**Comment by Hampster82** [comment]
The problem with the guid permalink is that as far as I have seen, rss readers don't generally expose that field to the user. So it's there but I can't do anything on the client end to display it anywhere. At least this seems to be true in QuiteRSS and RSS Guard, can't name any others off the top of my head.

**Comment by TheAMM** [comment]
7a27acb adds some info to the `<description>` field:
![image](https://user-images.githubusercontent.com/6820963/28493681-b9d12b8c-6f23-11e7-835c-e21ff116d608.png)
Seeds/leeches/comment counts are volatile information and we can't show file counts or much of any other information as we have to keep [ElasticSearch in mind](https://github.com/nyaadevs/nyaa/blob/master/es_mapping.yml#L73-L123).

**Comment by Hampster82** [comment]
That's more than enough for what my biggest issue was, which was the lack of accessible direct link to the torrent page. Thanks.
👍
