### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by gearan** [nyaadevs/nyaa#3]
There doesn't seem to be a way to add comments. Having a comment section would help greatly so we can share the quality of torrents and know which ones are worth downloading, and of course report if there is anything wrong with something in them.

**Comment by shubhank008** [comment]
The better and easier way to add comments would be just to use disqus, as many groups/sites use that on their site too so it becomes easier to track and be notified of torrents and replies on your comments.

**Comment by stvkno** [comment]
+1 for disqus. they do have a free version too

**Comment by TheAMM** [comment]
Disqus may have features, but it's also disqus. My main gripe is the slooow load times; I'm also not aware of a way to link the site accounts with Disqus. Comments are in the works, [this branch](https://github.com/nyaadevs/nyaa/tree/comments) has early crude progress.

**Comment by Nazonaze** [comment]
[Disqus is pretty awful.](http://donw.io/post/github-comments/)

There will probably just be internal comments eventually.

**Comment by Nazonaze** [comment]
On comments:

- Moderators should by default post comments appearing like a normal account. Have a separate checkbox for "post as a moderator" that would enable mod highlighting on a comment (so comments should have individual "by moderator" flags).
- Moderators should also be able to post as a moderator anonymously to protect their identity if they desire so (maybe have an user setting for mods so that they always post anonymously when using "post as a moderator").

**Comment by stvkno** [comment]
hmm that makes sense @Nazonaze . how should reply nesting be handled? stopping at certain depth or doesn't exist at all?

**Comment by TheAMM** [comment]
No nesting, just a flat list like NT had.

**Comment by Sn0wCrack** [comment]
Should the ability to make an Anonymous comment be given to all users, or be reserved only for Mod/Admin usage?

**Comment by TheAMM** [comment]
I'd say all - they'd only have to log out for an anonymous comment otherwise, and we're allowing anonymous torrents.

**Comment by Sn0wCrack** [comment]
Alright, that'll probably the next thing on the feature list then

**Comment by TheAMM** [comment]
Not done yet!

**Comment by OZBloodyBlackRabbit** [comment]
just need to be a line or two, or even last 5 and drop list to expand
more imiportantly (or useful i should say) is a moderator to steps in if things get out-of-hand and it actually goes back to the original uploader to reads it.

**Comment by Arylide** [comment]
Anonymous comments aren't going to fly on a public tracker. Especially not for mods where accountability is required. If you don't want to be associated to something you say make a throwaway account.

**Comment by katnyaa** [comment]
Closed in https://github.com/nyaadevs/nyaa/pull/165
