### ISSUE TITLE
WebSeeds removed when uploading torrents

### ISSUE THREAD

**Issue by MNI-BT** [nyaadevs/nyaa#302]
Hi,
When I upload some torrents, It'll automatically remove web seeds and some of trackers from torrent file,
Is there anyway to upload a torrent file without clipping out data from it?

Also thank you for your hard works.

**Comment by TheAMM** [comment]
We limit our trackers to 5 at most; more is not always better. Webseeds should survive our system, however take note that magnets in text-search results don't query the database for performance reasons.

**Comment by MNI-BT** [comment]
So that's the problem, at first I was thinking maybe it's some ban tracker system like tokyotosho, But just like you said, It was trackers limit, It'll be great If you can put some note on upload page about "any" limitation. 
I'll add some new torrents and check webseeds survivor tomorrow, hope you right about this matter. 
Thanks for help.

**Comment by TheAMM** [comment]
If your webseeds are according to [BEP-19](http://www.bittorrent.org/beps/bep_0019.html) they should be stored as trackers in our database. I'll close this issue tomorrow if you won't.
Most people don't  care about the trackers; those who do notice the list is simply cut in size, so we haven't bothered to add a note on that yet.

**Comment by MNI-BT** [comment]
I'm pretty sure that I setup my torrents with BEP-19 standards since my old torrents from old nyaa with  webseeds still working perfectly. 

To makes sure I test "webseeds removing by nyaa.si tracker" with two method:
First one with sixteen trackers and one webseed and second one with two trackers and three webseeds.

At first one as I told before most of trackers removed (that's not the really matter) and web seeds removed after uploading too. (that's why I opened this Issue).

At second one, tracker add three more trackers to torrents to makes sure every torrents have at least and at most five trackers no more and less, In this method webseeds removed too.

I'll appreciate any help with web seeding since my upload speeds is not that great.

**Comment by TheAMM** [comment]
Send the the .torrent through some pathway, I'll have a look at it. The site-served .torrent *should* contain the original trackers (site tracker + custom + site defaults, limited to total of five), but there may be something I'm missing.

**Comment by MNI-BT** [comment]
Okay, **Thank you for your help.**
Use these:

One of my old nyaa release which is still work with broken nyaa tracker: [Link](http://dl1.narutocentral.ir/[MNI][Dubbed]_Naruto_Shippuuden_-_D1&D2_[Usd][www.narutocentral.ir][2B5AFB37].mp4.torrent) ( It was Created with utorrent 1.8.5)

Recently release with 16 tracker and one web-seed: [Orginal File](
http://dl2.narutocentral.ir/[MNI][HDQ]_Netsuzou_TRap_-_NTR_-_01_[Persian_Farsi_Subtitle][480p][535D1419].mp4.torrent) Vs [Modified by tracker](https://nyaa.si/download/940149.torrent) (Created with Utorrent 2.2.1)

And latest file with 2 trackers and 3 web-seeds: [Orginal file](http://dl2.narutocentral.ir/[MNI][HDQ]_Netsuzou_TRap_-_NTR_-_02_[Persian_Farsi_Subtitle][480p][5AEBCF59].mp4.torrent) Vs [Modified by tracker
](https://nyaa.si/download/941441.torrent) (Created with qBittorrent 3.3.12 64bit)

**Comment by TheAMM** [comment]
Oh, riight, I misread a thing on BEP19. Webseeds *do not* survive our current system.
I can see a way to sorta hack them in without much pain, but we'll have to think about it a bit first. Stay tuned but don't hold your breath.

**Comment by MNI-BT** [comment]
Thanks again, sorry I know You have lot of thing to do but I looking forward for result and making better community.
