### ISSUE TITLE
"Secure Connection Failed"

### ISSUE THREAD

**Issue by zapzapzap1** [nyaadevs/nyaa#309]
> The connection to the server was reset while the page was loading.
> * The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> * Please contact the website owners to inform them of this problem.

Been popping up every time I visit the site today, usually solved with a few F5 presses, figured I'd bring up in case it's not just me.

**Comment by TheAMM** [comment]
Check your browser for any updates and make sure your time is correct. CF handles our public HTTPS, and while they're not infallible, it's out of our hands. Plus, not relevant to this repo.
