### ISSUE TITLE
Tracker not being detected on upload

### ISSUE THREAD

**Issue by toynbeeidea** [nyaadevs/nyaa#314]
Trying to upload a new torrent:  I get the message "Please include http://nyaa.tracker.wf:7777/announce in the trackers of the torrent."  Well, it is.  It isn't the first tracker, but it is included.  Can't include it any harder.

**Comment by sharkykh** [comment]
Perhaps it's not in its own tier?
Tiers are separated by an empty line.

**Comment by toynbeeidea** [comment]
OH CRAP - that's probably the exact issue.  I forgot to adjust that.  Please disregard, I am an idiot.
