### ISSUE TITLE
Torrent colors should be more vibrant

### ISSUE THREAD

**Issue by InsanityDevice** [nyaadevs/nyaa#318]
As opposed to the old Nyaa, the contrast between the colors, the background and the other colors is minimal, which makes it way too difficult to notice the color of a torrent at a glance. I can't even tell whether the color for raws is actually a color or if it's just grey, while the remakes and batches don't stand out at all.

To make it simple, the colors should be vibrant to create enough contrast to be distinguishable at a glance.

**Comment by InsanityDevice** [comment]
It's even worse in dark mode.

**Comment by Arylide** [comment]
http://makeapullrequest.com/
