### ISSUE TITLE
Malformed torrent metadata (url-list is not a list)

### ISSUE THREAD

**Issue by fapforfun** [nyaadevs/nyaa#319]
I'm a daily uploader. I didn't change anything from my daily uploads but got this error today on every torrents i try to upload. I can still upload on other sites include sukebei.pantsu.cat with no problems.

![snag-0163](https://user-images.githubusercontent.com/30563836/28750680-2039f4dc-751c-11e7-8d8e-82bc7173aef7.jpg)

**Comment by CounterPillow** [comment]
May be a regression of the change in https://github.com/nyaadevs/nyaa/pull/317

**Comment by mreweilk** [comment]
What client are you using? Please upload the torrent file in question somewhere so we can diagnose and prevent the error in the future.

**Comment by mreweilk** [comment]
Or rather, to help fix #317

**Comment by kovren** [comment]
Also getting that error on normal nyaa.
I used qBittorrent to make the torrent file:
http://fujiko.kittypla.net/~skr/[BuriBuri] Doraemon (2005) - 490 [720p][546141B7].torrent

**Comment by mreweilk** [comment]
Thank you very much! Will pass along this to the dev who added the support for webseeds and see about getting this fixed. Clearly the validation needs work.

**Comment by fapforfun** [comment]
I also using qBittorrent too.
https://sukebei.pantsu.cat/download/A535AD228B0B0B074C15C2B85FAE7402008AB93F

**Comment by TheAMM** [comment]
@kovren, @fapforfun, would you be able to make a torrent with a webseed (just any url, any file) using qBittorrent? It's going out of [spec](http://www.bittorrent.org/beps/bep_0019.html) when there are no webseeds and I want to make sure it doesn't go out of spec when *there are* webseeds.
