### ISSUE TITLE
Broken titles & descriptions on archived torrents

### ISSUE THREAD

**Issue by Nazonaze** [nyaadevs/nyaa#32]
Right now basically all HTML special characters are incorrectly stored for titles & descriptions of archived materials, eg. `"` shows up as `&#34;` in text, `&` shows up as `&#39;` etc.

BBCode should probably also be converted to markdown in descriptions.

**Comment by ReimuHakurei** [comment]
old descriptions did have their stuff converted to Markdown.

the ones you see bbcode in are where people used old scripts to do stuff.

htmlencoded stuff will be fixed soon.

**Comment by ReimuHakurei** [comment]
Fixed.
