### ISSUE TITLE
[Bug] Nyaa assigns default avatar on registration, does not retrieve new Gravatar if Nyaa account is older than Gravatar account

### ISSUE THREAD

**Issue by cecaniah** [nyaadevs/nyaa#320]
Apparently, clearing browser cache and following Gravatar's help section doesn't work to update the user's avatar.

Nyaa seems to assign a placeholder Gravatar key to all new members who used an email that does not have an existing Gravatar account. And since that key never changes after it's assigned, creating a Gravatar account with the same email doesn't reflect the new avatar despite clearing caches, logging in and out, switching emails and every other method mentioned in Gravatar's help section. 

Would like to have some way for Nyaa to recheck if the email used was given a new Gravatar key so that avatar changes will show up.

**Comment by CounterPillow** [comment]
Are you sure about this? I've created my gravatar account after the Nyaa account, and it worked no problems. Gravatar needs a few minutes to show the new avatar though.

**Comment by CounterPillow** [comment]
In particular, I just checked your account on the site and your avatar shows up fine.

**Comment by cecaniah** [comment]
I could have sworn it didn't work for hours when I tried it earlier and the
whole of yesterday. Might be a local bug with my browser or something. I'll
check again in about an hour and get back to you.

**Comment by TheAMM** [comment]
We currently use the Gravatar url directly in the images, no server side caching or such. Sounds like caching on Gravatar/browser side.

**Comment by cecaniah** [comment]
Just attempted to comment on my own torrent while using incognito mode
after clearing all cached content from "beginning of time". It's still not
showing up for some reason.​

**Comment by cecaniah** [comment]
Using 3 separate devices to access my profile and that torrent comment and
none are showing my Gravatar.

**Comment by TheAMM** [comment]
Check the url. `https://www.gravatar.com/avatar/f04da7aeb2cfc45ea8d4b9966ab91f4c?s=120&d=https%3A%2F%2Fnyaa.si%2Fstatic%2Fimg%2Favatar%2Fdefault.png&r=pg`

**Comment by ReimuHakurei** [comment]
Are you sure you assigned the image to that email on your Gravatar account?

**Comment by cecaniah** [comment]
I'm really just as baffled as you are because it directs to the default
avatar.

​and similarly...

​

**Comment by cecaniah** [comment]
I sincerely wish I was trolling but I'm very sure this avatar was assigned
since yesterday

​

**Comment by cecaniah** [comment]
I decided to just switch to a secondary email and the Gravatar updated
correctly. But still, this might be a strange issue to take note of in case
it surfaces some other time in the future...

Really, really, really appreciate how quickly you guys respond though.

**Comment by TheAMM** [comment]
Without you providing the assumed bad avatar url I can only assume this is user error.

**Comment by cecaniah** [comment]
Ah, I was replying via gmail and didn't realise my attached images don't
show up on GitHub. But thanks anyway.

**Comment by TheAMM** [comment]
I didn't want an image, I wanted the url you were served. If it was the same as the one I posted, then it's caching. If it's not, there's something weird going on.
