### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by mtcjayne** [nyaadevs/nyaa#327]
When trying to use Deluge with YaRSS2 I am unable to automatically get RSS entries for search results. I get the following error message in the YaRSS2 message log:
```
(2017-08-02T13:11:44): Manually running Subscription 'Catchall 2'
(2017-08-02T13:11:44): Update handler executed on RSS Feed 'Nyaa - horriblesubs boruto 1080p (nyaa.si)' (Update interval 120 min)
(2017-08-02T13:11:44): No items retrieved
(2017-08-02T13:11:44): Fetching subscription 'Catchall 2'.
(2017-08-02T13:11:44): Fetching RSS Feed: 'Nyaa - horriblesubs boruto 1080p' with Cookie: '{}' and User-agent: 'Deluge v1.3.10 YaRSS2 v1.4.3 Linux/4.5.7-docker-4'.
(2017-08-02T13:11:44): bozo_exception when parsing rssfeed: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ss.c:581)>
```
I'm under the distinct impression this is an issue with my system's Python version, but just in case I want to bring it up with you folks as well.

I set up a Docker image on a VC1S host at Scaleway, pulled Docker container from `jakexks/deluge-torrent-seedbox`, and added `https://nyaa.si/?page=rss&q=horriblesubs+boruto+1080p&c=0_0&f=0` as a feed with `.*` as a subscription (downloading everything in the feed.) Although I can see the items in the feed that mach that wildcard, for some reason when it comes to downloading them Deluge/YaRSS2 have issues.

I think if you included magnet links in the feeds this might be addressed, since those wouldn't rely on anything that could cause these SSL errors.

The Docker container uses Python 2.7.8, and I'm using Deluge 1.3.10 with YaRSS2 1.4.3 based on Python 2.7.

**Comment by sharkykh** [comment]
Python 2 before 2.7.9 and 2.7.10 had major issues with SSL as I recall.
Best course of action is to update the docker's Python version to the latest - 2.7.13.
If you can't do that, try installing pyOpenSSL in that docker using `pip install --user pyOpenSSL`

Then restart deluge & YARSS2 and try again.

**Comment by Arylide** [comment]
https://blog.cloudflare.com/sslv3-support-disabled-by-default-due-to-vulnerability/

Most of the Internet does not support SSLv3 due to known security issues. I recommend upgrading to a python version that can use TLS 1.2. As sharkkyh said, older python 2 version are known to have poor SSL and SNI support, both of which are required for many sites.

**Comment by mtcjayne** [comment]
I've now upgraded to a newer version of Python. I hadn't realized the Docker image had such an old version. Thanks for the responses!
