### ISSUE TITLE
HOW DID I PLAYED BACK.txt

### ISSUE THREAD

**Issue by OhNiice** [nyaadevs/nyaa#332]
- [x] It's not a bug :P

Hi!

Do you remember this little text file which was accessible from every torrent? I do :)

Could we get it back if it's not already and could it be maintained?

**Comment by TheAMM** [comment]
If you remember it, you should know how to play files already.
Not every torrent is a video file, and playback support is not our concern. Such things are easy enough to google.

**Comment by CounterPillow** [comment]
Many uploaders also leave a recommendation in the description. The software recommendations (lol vuze) of old nyaa were probably one of its worse parts.

**Comment by OhNiice** [comment]
"Google it, period" OK.

Thanks though.
