### ISSUE TITLE
[Suggestions] Increase character limit in comments and add #commentnumber

### ISSUE THREAD

**Issue by Adrenaline67** [nyaadevs/nyaa#335]
Hi,

Sorry if already suggested, couldn't find anything even in closed topics.
Character limitation is very annoying and to my mind contributes to spam, mostly on debates (nyaa is a great place to debate, right? Come on!).
https://nyaa.si/view/947012

Also it would be nice if you could implement the #number of the comment on each message so it can be easier to redirect someone to a specific comment using a permalink. It was a feature an old nyaa if I remember well.

Thanks!

**Comment by sharkykh** [comment]
> Also it would be nice if you could implement the #number of the comment on each message so it can be easier to redirect someone to a specific comment using a permalink. It was a feature an old nyaa if I remember well.

Permalinks are available, click the date and time of the comment and you'll get a permalink to it.

**Comment by CounterPillow** [comment]
I often find comments where people have to make two in series because of the char limit, so increasing it to something more sensible like 1000 would probably quell the rage some people express at this, and actually enable thoughtful discourse.

**Comment by TheAMM** [comment]
1024 in d5b8a3a2ae4cab43230906cdc50869485218146a.
