### ISSUE TITLE
Some issues so far

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#337]
I have 3 issues (2 that I already reported and got the cold shoulder type of reply) that really annoy me (I will be surpirse if they don't annoy any sane user honestly)

1. When I try to upload torrent I will keep getting the "Please include http://nyaa.tracker.wf:7777/announce in the trackers of the torrent" despite HAVING that tracker in the tracker list, I assume it happned because the site won't detect the tracker unless it the first one in the list, please fix it as it quite annoy for uploaders who want to make things share-able as easy as possible
![1](https://user-images.githubusercontent.com/14190834/29296189-5b67e32e-8161-11e7-9227-8a2c0ad28494.PNG)

2. Commit typing limit.... (One of the reasons I hate twitter), Old nyaa let us had sane number of letters before we reach the limit, here I get to it on the second line, please increase the limit to the point it won't feel like it there (or we just keep cut our commit.. a lot... which not that nice)

3. add subscribe button to uploaders, Yea I know you already told me you think about it in the future but it really that demanded, old nyaa added it quite late and had poor design, but it worked and help people so much.

Please consider do these stuff  as they more or less the only things (that and random down time of the site...) that keep the site from reaching perfection in terms of nyaa replacement.

**Comment by ReimuHakurei** [comment]
For the first issue there, you are probably not grouping trackers properly.
There should be a blank line between each tracker.

**Comment by egozi44** [comment]
I never had to do it before, even my torrent client add trackers this way, jusy one enter key between each tracker worked just fine.

**Comment by ReimuHakurei** [comment]
When you don't put a blank line between each tracker, you prevent torrent clients from actually using all of the trackers. They will instead pick one at random and only use that one.

**Comment by egozi44** [comment]
Alright, will try it, what about the other questions? (number 2 is the one that annoy me the most)

**Comment by CounterPillow** [comment]
Comment length was increased from 255 to 1024

**Comment by egozi44** [comment]
Thanks
