### ISSUE TITLE
rss not working with utserver (utorrent server)

### ISSUE THREAD

**Issue by remlei** [nyaadevs/nyaa#339]
it returns with blank page if rss feed request was done by utserver.

**Comment by remlei** [comment]
btw, the rss feeds in other trackers works just fine (eg, horriblesubs personal rss feed, nipponsei, etc....) only nyaa.si is not working

**Comment by deandmx** [comment]
Or Sonarr. Errors out with "Indexer feed is not supported: Feed contains releases without title."

**Comment by CounterPillow** [comment]
Could be a multitude of reasons:

1. Your SSL/TLS connection is failing because of an outdated system/software
2. You're exceeding some abuse protection rate limit
3. You're in an IP range that is getting a JS/CAPTCHA challenge by Cloudflare.

All of these would be related to the deployment, not really to the code.

**Comment by remlei** [comment]
1. It doesnt seems like a SSL related issue since I have 12 https RSS links and they do work fine.
2. Not sure about this but im sure its not being abused since rss works fine in browser and other torrent clients that is working under the same IP
3. same answer with #2

**Comment by Arylide** [comment]
The vast majority of people's issues have been SSL related. Due to cloudflare limitations we only support TLS1.2 and require SNI. You should ensure your clients support these standards. Failing this check if you are being issued a challenge by cloudflare.

**Comment by miflinak** [comment]
I have similar problem. But in my case CloudFlare asking me to enter CAPTCHA and of course there is no way torrent client will enter captcha.

Can nyaa.si disable captcha check for RSS feeds? Because well... RSS supposed to be downloaded by robots, not by people.

**Comment by TheAMM** [comment]
RSS endpoints already have loosened CF security.
