### ISSUE TITLE
rss feed not working with sonarr

### ISSUE THREAD

**Issue by tmathura** [nyaadevs/nyaa#34]
I get the error message in Sonarr, 'Indexer feed is not supported: Feed doesn't contain the release content size.'. Is it possible to add the content size to make it work, please.

**Comment by sharkykh** [comment]
I'm planning on adding `seeders`, `leechers`, `downloads`, `size` and `info-hash` attributes to items in the RSS feed.
Hopefully I'll get to it soon (I've yet to set up a dev environment)

**Comment by tmathura** [comment]
Thank you!

**Comment by ClArthur** [comment]
Not working with utorrent as well (no error message so I'm not sure if it's because of the same problem). I also tried qbittorrent, which actually seems to work just fine.

**Comment by sharkykh** [comment]
@ClArthur 
That's weird, the RSS feed (https://nyaa.si/?page=rss) works for me on uTorrent 3.4.9...
What's the issue? It doesn't load at all, or you can't download anything?

**Comment by ClArthur** [comment]
@sharkykh Oh sorry I forgot to address that I was using the Mac version of utorrent (1.8.7 build 43796). It does look like a bug on the utorrent side since this [ohys-raws feed](https://torrents.ohys.net/download/rss.php?dir=new) doesn't work with it either, so I just reported this bug to them. 

It doesn't say that the URL is invalid, but it just gives me an empty list and doesn't load the contents. (Although the old nyaa.se worked perfectly fine.)

**Comment by sharkykh** [comment]
@ClArthur I personally had the exact same issue with rarbg.com's feed (only in uTorrent) ever since Avast AV got its big yearly update.
Had to disable the "Web Shield" in order for it to be able to fetch the feed. So weird.
But obviously that's not the case if you're on OSX.

Still very weird.

**Comment by lilchancep** [comment]
I had this issue when adding RSS from HorribleSubs as well. Enabling "allow zero size" at the bottom of the page solved my problem. 
(Sorry I'm currently on mobile)
http://imgur.com/a/x2GMJ

**Comment by NMe84** [comment]
It does solve the acute problem but it's not ideal as you then lack some file size checks and you might end up downloading stuff that you don't want or not downloading stuff that you do. Also, chances of Sonarr's devs replacing the "old" preconfigured Nyaa with this one are higher if this searchable RSS feed includes all the info they need.
