### ISSUE TITLE
Cannot connect to nyaa.si because of CloudFlare DDos Protection.

### ISSUE THREAD

**Issue by NfernoFire** [nyaadevs/nyaa#345]
I am using Taiga with these rss feeds:
https://nyaa.si/rss?c=1_2&f=0
https://nyaa.si/rss?c=1_2&f=0&q=%title%
 However it won't work anymore because of CloudFlare.

**Comment by NfernoFire** [comment]
I fixed it by changing it to 
https://nyaa.si/?page=rss 
and 
https://nyaa.si/?page=rss&q=%title%

**Comment by TheAMM** [comment]
Not relevant to this repo.
