### ISSUE TITLE
setuptools integration

### ISSUE THREAD

**Issue by Neteov** [nyaadevs/nyaa#347]
Integrating setuptools into the project would help it in the following ways:

- **Packaging** - The entire application could be packaged into a single file (*.whl if using the _wheel_ library or source distributions) which can be deployed to the server instead of having to copy all the source files.

- **Dependency management** - a cleaner way to declare dependencies needed for development of the application and deployment (http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) rather than having one big requirements.txt file which contains both.

- **Ad-hoc scripts** - currently one-off scripts are stored at the root of the project and have to be referenced from there when the virtual environment is activated in order for them to work. Using console scripts (http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) would put them into the operating system's path when the virtual environment is activated or run the script in the virtual environment without having to activate it manually if they are referenced directly.

**Comment by TheAMM** [comment]
True, however in my opinion, unnecessary.
This project is not meant for quick short-lived deployments, nor is it finished enough for `pip` style installs (which is still kind of a weird case on non-library/commandline tools).
At worst the user will have to set up the database, ElasticSearch, and web server - optimizing away a `git clone` + `pip install` is a bit moot. It's a one-time setup, and yes, while quick and easy would be better for new contributors, the majority of the setup happens outside of this project.

**Comment by mreweilk** [comment]
This seems silly and pointless but the point about the scripts is one I've made before. Most of them need to be moved into the utils directory.
