### ISSUE TITLE
[Bug] Searching on mobile web page is broken

### ISSUE THREAD

**Issue by muizzsiddique** [nyaadevs/nyaa#35]
The amount of room we have to type in the search bar for mobile phones is almost nonexistant.

![screenshot_2017-05-13-21-27-54 1](https://cloud.githubusercontent.com/assets/23620568/26029138/ac632372-3825-11e7-97a7-ffad67d2ce7b.png)

Also, because of that (well, I think that's the reason), when searching for something the final search string that is used is completely jumbled up. I instead have to go into the URL and type my search query seperated with +s.

This was the result of searching for "hi hello": "llohelhhi h"

![screenshot_2017-05-13-21-40-10 2](https://cloud.githubusercontent.com/assets/23620568/26029139/ac64a5ee-3825-11e7-9594-5d0d36835d0b.png)

**Comment by nathancyam** [comment]
This issue may be addressed with this PR:

https://github.com/nyaadevs/nyaa/pull/80

Feel free to add any comments and suggestions.

**Comment by UnKnoWn-Consortium** [comment]
How about moving it out of the navbar and let it live as an independent component on top of the torrent list? 

Like this: 
![2017-05-17_055756](https://cloud.githubusercontent.com/assets/9733856/26130123/d8eaf2d8-3ac5-11e7-93bf-9c37c551aee0.png)

**Comment by nathancyam** [comment]
It would definitely make frontend easier, however it would remove the ability to search for torrents from any page. I don't particularly want to remove this useful feature for users. Since Elastic Search has been implemented, it would be shame not to utilise it.

**Comment by aldacron** [comment]
Fixed by #80
