### ISSUE TITLE
Receiving a "Bad Request" when sorting by either "Seeders", "Leechers" or "Completed"

### ISSUE THREAD

**Issue by verymuchwow** [nyaadevs/nyaa#350]
Hi Devs,

As per the description, I am receiving a "400 Bad Request - Teapot" message when attempting to sort by either of the following:

1. Seeders
2. Leechers
3. Completed

This functionality was working until now.

FYI - the filters used are:
1. Trusted only
2. Anime - English Translated

**Comment by mbankim** [comment]
@verymuchwow did you search for anything? I'm pretty sure this is caused by not entering keywords in the search field and trying to sort. I also noticed this error with other filters as well.

**Comment by Arylide** [comment]
This repo is for the software, not any website that may use it. You'll need to ask in the proper channel.
