### ISSUE TITLE
sort by seeders is giving "Bad Request  Teapot"

### ISSUE THREAD

**Issue by Theletha** [nyaadevs/nyaa#352]
you don't get this problem if you haven't added a category first the you can sort by seeders but if you i.e. Anime (or any other category) as a category and then sort by seeders you get the error in the title. 

this applies to:

sukebei.nyaa.si

Error:
https://i.gyazo.com/11b1a652057944efc9af496957355681.mp4

**Comment by Arylide** [comment]
#350
