### ISSUE TITLE
sukebei is down

### ISSUE THREAD

**Issue by momoe** [nyaadevs/nyaa#368]
While nyaa is recovering from disk failure, there's an issue with http://sukebei.nyaa.si/ is 502 as well.

**Comment by TheAMM** [comment]
This repo is not for or about any deployments of the code.

**Comment by ReimuHakurei** [comment]
The downtime is for both sites -- replacement server should hopefully be
provisioned tomorrow.

However, this repo is not for discussing the site, merely the codebase that
powers it.
