### ISSUE TITLE
When should nyaa site be OK?

### ISSUE THREAD

**Issue by cxwx** [nyaadevs/nyaa#370]
Site is currently in read-only maintenance mode.

**Comment by CounterPillow** [comment]
literally right now

**Comment by ReimuHakurei** [comment]
It's up now, but this is a repo for code, not the site.

**Comment by TheAMM** [comment]
Reading is overrated anyhow
![image](https://user-images.githubusercontent.com/6820963/30542129-c94c9d22-9c86-11e7-9c60-19634b69d936.png)
