### ISSUE TITLE
Allow for page setting in RSS feed

### ISSUE THREAD

**Issue by ardentsword** [nyaadevs/nyaa#371]
I would like to request a feature regarding the RSS feed. For archiving purpose (I missed some older torrents due my server downtime) I would like to select the page for my RSS feed.
For example, with normal pages you can do "nyaa.si/?u=HorribleSubs&**p=5**", I would like to be able to do: "nyaa.si/?u=HorribleSubs&**p=5**&_page=rss_" right now this will always return the first page.

**Comment by CounterPillow** [comment]
I think we used to have this functionality, but it was removed for performance reasons.

**Comment by Arylide** [comment]
What was said above, if 75 isn't enough for you then you will need to be more specific on your search. Read the help page for info on how to make better searches: https://nyaa.si/help#using-search
