### ISSUE TITLE
some feature request for to-do-list 

### ISSUE THREAD

**Issue by amayra** [nyaadevs/nyaa#373]
first thank you for you hard work we appreciate it 
i made some feature request i think this well make nyaaC better :
--- messages system for easy PM uploader
--- ability to tag user with @nyaadev 
--- comment history 
--- and it well be nice if we have notifications in the future
i hope you take my request into consideration

**Comment by Arylide** [comment]
1: Unlikely
2: Likely
3: Definitely not
4: Eventually when someone gets around to it. There is a PR but it needs work.
