### ISSUE TITLE
Feature Request: Please raise the number of returned items in a search RSS-Feed.

### ISSUE THREAD

**Issue by user1user** [nyaadevs/nyaa#375]
Only returning 10 items does not cover Episodes 1, 2 and maybe 3 with most 12/13-episode series, if I want to download a series on a later date.

I tried to find out how Nyaa handled this before its untimely demise and it seemed like it returned 100 items on search results per page (covering most series except long runners). The number seemed to be 105 items on RSS searches.

P.S.:
Maybe you could also implement a way to standardize common search-feeds and to make them more cache-able (by reducing the number of different versions of the same search) to ease the strain. (Group name + Series (without the episode number and the Hash, but maybe with resolution) seems quite the common target. )

Basically suggested search feeds per Group/Series/Resolution. This could also be limited to High-Volume Groups/Series, though it might be useful even for less-downloaded series.

P.P.S:
* Do popular clients support if-modified-since/etags? (Though the CDN will probably support this easily.)
Seems cloudflare adds cache-control:max-age=300 and a Date-field automatically?
* Seems a very popular client sets its update interval on the ttl in the RSS-Feed, while it uses 15min as default. https://validator.w3.org/feed/docs/rss2.html#ltttlgtSubelementOfLtchannelgt
I'd suggest increasing the TTL-Field to a day if there has not been an update to the search-result for a few months (newest item older than x months).
* Low item-counts in RSS-Feeds increase the amount of necessary updates to avoid missing stuff.

**Comment by user1user** [comment]
Correction: Sorry Google Chrome's RSS plugin seems to only show 10 items in the preview.

Actual Limit seems to be 75.

My suggestion about suggesting common search-feeds and adding a TTL-Field in specific cases still stands. Adding an Etag seems to be more tricky but could only apply to known feeds that where standardized, cloud-flare adds a Date-Header anyway (with max-age=5 min) so this might not even help that much except in giving CF the option to cache popular stuff for longer than that and ease system load on the back-end automatically even if clients don't support cache headers.

**Comment by Arylide** [comment]
We're looking into better caching at some point. The limit as you said is 75, we may raise it as needed in the future.
