### ISSUE TITLE
Add way for an admin to mark a user as trusted/mod/admin

### ISSUE THREAD

**Issue by mreweilk** [nyaadevs/nyaa#38]
Currently there is no way of setting this unless you go in the db directly. 

I suggest a selection box that appears on the user in question's profile if you are an admin that let's this be changed.

**Comment by TheAMM** [comment]
I'd add an `/user/<name>/edit` which will allow properly ranked users to adjust others.

**Comment by nathancyam** [comment]
I've got a mockup of what it could look like:

![admin-user-dashboard](https://cloud.githubusercontent.com/assets/2491442/26031918/0e7fc144-38c8-11e7-85ce-186ae01837a8.png)

I've decided to add a mass action checkbox to the side in case if comes in handy. Is this something that we may want to have for admin useres?

**Comment by chopraaa** [comment]
@nathancyam Yes, a checkbox next to the Username field would be great.

The rest looks fine.
