### ISSUE TITLE
debug code H5A799NJ

### ISSUE THREAD

**Issue by oosap** [nyaadevs/nyaa#383]
hey guys I got a debug code when trying to make a new account **H5A799NJ** any help would be great.

**Comment by TheAMM** [comment]
Could you come to the IRC? This is not the place for tech support.

**Comment by Arylide** [comment]
You are Muzzle right? You put a comma in your email instead of a dot.

**Comment by oosap** [comment]
yeah haha just noticed sorry was going to delete this post but you beat me to it, I'll contact using IRC in the future
