### ISSUE TITLE
Dropdown menu not working on mobile

### ISSUE THREAD

**Issue by mateusmlo** [nyaadevs/nyaa#386]
I like to watch and download anime on my phone, but there's a problem with the menu as it won't open when I click the hambaga button, thus making it impossible for me to access the search. Don't know if I'm the only one with this problem here, and for reference my mobile browser is Opera.

**Comment by ReimuHakurei** [comment]
Which Opera? Normal Opera or Opera Mini? What platform? (Android, iOS, etc)

I know Opera Mini has issues with some websites just because of how it works.

Works fine for me on Firefox for Android.

**Comment by mateusmlo** [comment]
Normal Opera. I'll try another browser then, brb.
