### ISSUE TITLE
Add a proper torrent deletion option

### ISSUE THREAD

**Issue by mreweilk** [nyaadevs/nyaa#39]
Currently deleted torrents are just hidden. 
I suggest a real delete and a infohash blacklist that will prevent said torrent from being uploaded again and a real delete that will allow upload again. I'm not sure why we would need to delete a torrent while still allowing it to be uploaded again but it should be an option.

If we are worried about rouge mods in the future perhaps true delete/blacklist should be reserved for admins.

Uploaders should also be able to delete their own torrents but perhaps it would be best to transparently set these as hidden in case an account has been hacked, though such behavior might lead users into thinking they will be able to upload the same torrent again which would not work.

**Comment by aldacron** [comment]
We really need this

**Comment by TwinDragon** [comment]
I'll third the motion since the group I'm in would like to start completely fresh with torrents.
