### ISSUE TITLE
Search Enhancement Request

### ISSUE THREAD

**Issue by mitchellfranklin** [nyaadevs/nyaa#40]
Hi, If possible would like to see the search to be similar to the original i.e. be able to search with Hor Dragon Ball Super 480 which would return all Horrible Sub Dragon Ball Super [480p] results

**Comment by TheAMM** [comment]
Yes; search is in the works and the current version will be entirely gone.
Don't worry, we're not idiots! We know the search is bad at the moment, but please do look for duplicate issues first.
