### ISSUE TITLE
Main page comment hover.

### ISSUE THREAD

**Issue by Avostear** [nyaadevs/nyaa#401]
Add an effect hover effect to main search page to show some of the comments.
![untitled-1](https://user-images.githubusercontent.com/2817076/32407280-07b46fc2-c15d-11e7-9a43-eb42fa2bdd74.jpg)

**Comment by TheAMM** [comment]
The idea is to keep the listing efficient on database queries, but this could be done with XHR on-request, so only when needed.
Up for someone to implement, then.

**Comment by Nalapl3** [comment]
Which comments should it show? I think it should show the last ones. This would also have to much the website layout.

**Comment by Avostear** [comment]
To be honest, thats got me stumped; latest, up-vote system, random, etc. I mean in a perfect world it would only show comments that actually describe the A/V but thats a stretch. Just figured it would be cool.
