### ISSUE TITLE
Feature Request: Additional literature categories

### ISSUE THREAD

**Issue by SDMU** [nyaadevs/nyaa#402]
If possible please add a separate category for light novels and manga within Literature .

Literature >English Translated>Manga
Literature >English Translated>Light Novel

**Comment by TheAMM** [comment]
There is more to English translated literature than just manga and LNs, but I agree that it would be nice to split manga into its own category.
Nice, but *for now* we'll stick with the classic categories.

**Comment by Arylide** [comment]
What AMM said. At the moment we're likely to keep the categories the same. We may expand them in the future though, it is a good idea.

**Comment by MarchWorks** [comment]
I was just going to open a new issue for this if Github hasn't shown this in the "Similar issues".

It's quite annoying  to get all these mangas when searching for a novel to read and having to visit each link (generally) just to know if it's a manga or a novel
