### ISSUE TITLE
Category mistake

### ISSUE THREAD

**Issue by mistydjflsjfojo** [nyaadevs/nyaa#404]
https://nyaa.si/user/harley0726?f=0&c=3_3&q=
Submitter：harley0726

ex.
https://nyaa.si/view/976009
https://nyaa.si/view/976008
https://nyaa.si/view/976007

×    Japanese（Literature - Raw）
◯  Chinese（Literature - Non-English-translated）

**Comment by CounterPillow** [comment]
Use the report button on the site to report torrents, don't open a github issue for this for fuck's sake.

**Comment by TheAMM** [comment]
...

**Comment by TheRoaringLion** [comment]
o god this funny stuffs :P
