### ISSUE TITLE
Request: Split Subbed and Dubbed translations

### ISSUE THREAD

**Issue by tsukari** [nyaadevs/nyaa#41]
With simuldubs beign so common now there's pretty legitiamte reasoning to split releases that are dub only.

**Comment by TheAMM** [comment]
We discussed this and adding language tags for audio/subtitles.
Simply adding a new category is... problematic, as we have the old archived torrents. We'd need a sure way to figure out which are dubbed, or leave them as is which is just lazy. (Tbh this applies for the language tags as well)

**Comment by sciguyryan** [comment]
Would it be possible to look for the words "dub" and "dubbed" and whatnot in the titles of the torrents to give an indicator as to which should be reclassified?

If there a report mechanism then that could also be leveraged to reclassify existing torrents, let the users do some of the work as it were.
