### ISSUE TITLE
 Feature Request: Private RSS

### ISSUE THREAD

**Issue by M9k** [nyaadevs/nyaa#416]
I think a user's private rss can be useful for people who use seedbox or want to add somethink in download when they are far from home, mostly for ova and films.
For reference look at Shana Project.

**Comment by CounterPillow** [comment]
I don't think it should be nyaa's job to provide you with a way to control your jank-ass seedbox setup where you somehow have access to your nyaa account but not to your seedbox.

**Comment by Arylide** [comment]
Use shanaproject.
