### ISSUE TITLE
It is possible to allow other trackers on top?

### ISSUE THREAD

**Issue by Rick74crx** [nyaadevs/nyaa#42]
<img width="532" alt="screen" src="https://cloud.githubusercontent.com/assets/10237870/26030237/27f1ed76-384d-11e7-976c-1e766478a07f.png">

From: https://beatrice-raws.org/release/occulticnine-1080p#comments

Raws are IMHO a pretty valuable asset for this kind of website, could something be made in this sense?

**Comment by aldacron** [comment]
I believe requiring the Nyaa.si tracker is the exact same behavior as NyaaTorrents, is that incorrect?

**Comment by HitmanJ** [comment]
@aldacron I think some torrents didn't even use nyaa's tracker at all.

**Comment by toynbeeidea** [comment]
How about don't enforce any trackers at all?  Old Nyaa blocked tons of completely valid trackers, and it was really stupid.

**Comment by aldacron** [comment]
This is fixed, but we do require our tracker for stats.

**Comment by TheAMM** [comment]
We aren't blocking any trackers, but Nyaa.si is a combination of an index and a tracker. Naturally we want to ensure there's at least one tracker we can always count on, and that's ours. Subject to change in the future, but currently our stats are tied to the tracker and we want to make sure the initial seed is in the pool as well.
