### ISSUE TITLE
Feature request: Automatically tag uploads

### ISSUE THREAD

**Issue by JohnDoee** [nyaadevs/nyaa#424]
Have you ever tried to find the anime [K](https://myanimelist.net/anime/14467/K)? Go try, see how easy it is.

This, and other situations can be improved by auto-tagging everything with something like guessit.

It'd work like this:

    >>> pprint(dict(guessit('[CBM] K (K-Project) 1-13 Complete (Dual Audio) [BDRip-1080p-8bit-FLAC]')))
    {'audio_codec': 'FLAC',
     'episode': 13,
     'episode_title': '1',
     'format': 'BluRay',
     'other': ['Complete', 'DualAudio'],
     'release_group': 'CBM',
     'screen_size': '1080p',
     'title': 'K',
     'type': 'episode',
     'video_profile': '8bit'}

where each of these are turned into tags like `title:K`, `release_group:CBM` that can be queried exactly.

Another example is:

    >>> pprint(dict(guessit('[Erai-raws] Ballroom e Youkoso - 01~24 [1080p AVC-YUV444P10][E-AC3]')))
    {'audio_codec': 'AC3',
    'episode': [1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24],
    'release_group': 'YUV444P10][E',
    'screen_size': '1080p',
    'title': 'Ballroom e Youkoso',
    'type': 'episode',
    'video_codec': 'h264'}

where you can search for `episode:7` and `title:Ballroom e Youkoso` and get a list of torrents plus batches that contains said episode.

It'll organize and index the site in a new way so isn't just a bunch of torrents.

I can develop the feature myself so I guess it's more of a "feature proposal" than "request". It can also plug into other features like #408 because tags can be streamlined/merged.

**Comment by Arylide** [comment]
And what of everything that isn't an anime? The site isn't just for video mediums.

**Comment by JohnDoee** [comment]
To have this feature in all categories from the initial get-go does not feel like a requirement to me.

You'll have to elaborate on the "not our problem" part because being unable to find stuff on a site designed(?) to find stuff feels a bit like an issue to me.

Sure, it can be outside the scope of that the site tries to accomplish, which is fine, then just close the ticket and move on.

**Comment by xiaoyu0519** [comment]
good

**Comment by ReimuHakurei** [comment]
I feel that issues finding something (like K) is an issue with the search settings, and we can fine tune those.

Something like metadata, if it is done, should be done by matching to AniDB releases imo.

**Comment by Arylide** [comment]
>To have this feature in all categories from the initial get-go does not feel like a requirement to me.

To me it doesn't make much sense to have a feature for one category.

>You'll have to elaborate on the "not our problem" part because being unable to find stuff on a site designed(?) to find stuff feels a bit like an issue to me.

This repo is about the software, however it isn't "designed" to find things especially, but rather to serve as a repository of metadata, my expectation is that you already have an idea what you want in terms of release from external sources. Such as anidb in this case.

**Comment by JohnDoee** [comment]
> Something like metadata, if it is done, should be done by matching to AniDB releases imo.

How would you do that? As far as I'm aware there's two ways to search AniDB, titles and CRCs. With both things you're back at what I proposed here where the workflow is:
extract info from various titles -> use info to resolve external data sources
e.g. tag `title:K` is used to resolve an additional tag `anidb:9043`

My guess is that any exploration and extraction of data on the site will result in something similar to the tag system.


> To me it doesn't make much sense to have a feature for one category.

Expanding a `guessit`-like piece of software to additional categories wouldn't be that much work if this would provide enough value to video. The variety in fields and type of fields seem smaller too for the missing categories.
