### ISSUE TITLE
searching for 1080 doesnt match 1080p torrents

### ISSUE THREAD

**Issue by Tensorr** [nyaadevs/nyaa#43]
Searching for 1080 like so: https://nyaa.si/?q=1080&f=2&c=1_2  currently returns 1 match (an .ass sub file)

while searching for 1080p https://nyaa.si/?q=1080p&f=2&c=1_2 returns over 8 pages worth of results.

**Comment by Tensorr** [comment]
it seems to be a problem with all partial words. as searching for 'horrible' wont match any HorribleSubs torrent.

**Comment by Sn0wCrack** [comment]
Yes, currently search is being worked on, search only works for full words currently rather than partial.
