### ISSUE TITLE
FRQ: Language content tag

### ISSUE THREAD

**Issue by c933103** [nyaadevs/nyaa#435]
Currently, content on the site are separated into three main categories: raw, english translated, and non-english translated
It would probably be better if these language categories can be superseded by language tag that label the language.

For instance, for a regular video, the system could allow user tag the languages that are available in audio track as well as subtitle.
This way, non-English users on the site can more easily search for content in their languages
And it would also be easier to search for sub vs dub content

Using tags instead of categories also have an advantage that it can clearly mark files that are have included or are available in multiple language versions.

**Comment by TheAMM** [comment]
#388
I have no comment on the feature for now.
