### ISSUE TITLE
Resend Account Activation Email Request

### ISSUE THREAD

**Issue by Soulinks** [nyaadevs/nyaa#437]
It should be made possible for an account activation mail to be resent in times where it seems to fail the first time.
If you sign up, you are asked to activate your account via the Email. However, as found in my case, no email has made it to my email address. I have waited over an hour and scoured through my inbox and spam box, to no avail.
Upon trying to login regardless, you are met with the request to activate your account via the email it sent... You cannot trigger an email resend by trying to sign up again either as the email address is already (and quite correct to point out) in use.
Ultimately, you are left with a paradox. Please someone, for the love of all things kawaii, add an Activation Email resend request button... thingy...
Yoroshikuonegaishimasu!

**Comment by CounterPillow** [comment]
Should probably be added, yeah, but needs rate-limiting for sure. (We wouldn't want people to spam activation e-mails). Maybe we should use flask-limiter for that.

In the meantime, feel free to contact us on IRC to manually activate the account.

**Comment by TheAMM** [comment]
We have yet to see a case where resending the email would help. Your email (assuming you're `Soulinks` on the site as well) is a `live.co.uk` email, which we explicitly warn about on the registration page. Microsoft discards our emails, any emails with a link in them, and the process of getting whitelisted and maintaining that status is so terribly tedious it's easier to tell users the emails simply won't work.

**Comment by CounterPillow** [comment]
Guess we should add `live.co.uk` to our e-mail blacklist then.

**Comment by Soulinks** [comment]
Ah, was not aware live.co.uk fell into Outlook/Microsoft accounts... I've had this email account since live.co.uk was available I think so that's slipped past me. On the registration page, it may be easier to list the domains that don't like Nyaa and yeah, blacklist it so it cannot be entered in the Registration Page if such is the case.
@TheAMM if it is possible to manually activate my account on this such occasion, I would be humbly grateful, as I don't have any other email address 😢

**Comment by TheAMM** [comment]
@Soulinks There are over 60 Microsoft email domains. We have most of them blacklisted, but either `.co.uk` slipped past or it was recent-ishly created.

As CounterPillow already said:
> In the meantime, feel free to contact us on IRC to manually activate the account.

**Comment by Suminsky** [comment]
Yeah what a great logic, I didnt receive any activation email, and cant reuse the email to register another account since the account already exist. An account that cant be used cause it will never be activated.
gmail btw

**Comment by CounterPillow** [comment]
99% of cases why you'd not receive an activation e-mail are explained by a big red message during registration, namely that your IP is banned and needs to be manually activated by a moderator. If you were capable of actually reading, which you apparently are not, you'd have figured this out already.

**Comment by cleaders51688** [comment]
I have contacted the administrator. How long can I get a reply

**Comment by cleaders51688** [comment]
@

> 在注册过程中，一条红色的大消息解释了为什么您没有收到激活电子邮件的99％情况，即您的IP被禁止，需要由主持人手动激活。如果您能够实际阅读，而您显然没有阅读能力，那么您已经知道了。



I have contacted the administrator. How long can I get a reply
