### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by bittebitte** [nyaadevs/nyaa#44]
There doesn't seem to be a way to recover passwords via email.

**Comment by aldacron** [comment]
Feel free to go into IRC and ask about recovering/resetting your account for the time being!

**Comment by Ketho** [comment]
I asked on IRC and they responded it wasn't not possible sadly

![](https://i.imgur.com/TPKyrcL.png)

**Comment by Ketho** [comment]
I don't know why my previous comment was deleted (uncontributive or image), but just want to say it did help to ask on IRC
