### ISSUE TITLE
App

### ISSUE THREAD

**Issue by tom2411** [nyaadevs/nyaa#445]
Hello I wanted to know if you will do a mobile application of nyaa ??
It could be a big imprivement for the people that use nyaa on their phones.

**Comment by CounterPillow** [comment]
Not as of now, but the site should work fine in your mobile browser. If it doesn't, please let us know.

**Comment by TheAMM** [comment]
Websites are meant to work on multiple platforms. There is nothing crucial an app could do that the website couldn't. It's better to focus efforts on the site than split it up.

We've had at least two people tell us they're going to make one, but we haven't really heard of them.

**Comment by tom2411** [comment]
Ok thank you.
