### ISSUE TITLE
Feature request: Option to hide comments by default

### ISSUE THREAD

**Issue by veniuprua** [nyaadevs/nyaa#447]
Reading a torrent's description is currently impossible without seeing the comment section, and therefore the user is susceptible to potential spoilers (before they are removed, that is).

It would be nice to have an option that makes the comments visible _only_ when you click a button below the torrent description. Also, I wouldn't mind if this was only available for registered users.

**Comment by ReimuHakurei** [comment]
For this issue, the setting should be on a yet-unmade user settings page. We'll need a new table in the database to store these settings. Probably want the layout of columns to be something like this:

- id
- reference to user ID
- setting_name (text)
- setting_data (text)

But there are other ways it could be done.

User Settings page/table would be useful for later much-requested user settings.

**Comment by such-doge** [comment]
#515 adds this.
