### ISSUE TITLE
Feature request: RSS feeds for comments?

### ISSUE THREAD

**Issue by adrianiainlam** [nyaadevs/nyaa#449]
It would be nice to have RSS feeds for torrent comments so that we can be aware of new comments, and can "subscribe to" a torrent's comments, whether our own, or other people's.

I hope it shouldn't be too difficult to implement? It's pretty much the same as loading a torrent page, just presented in a different way.

**Comment by Arylide** [comment]
This would be handled by #167 and #397 eventually.

**Comment by adrianiainlam** [comment]
I hope you don't mind me leaving this here in case for the time being someone wants to be notified for comments as well.
<https://nyaacomments.tk>
