### ISSUE TITLE
Flexget - broken or invalid torrent file received

### ISSUE THREAD

**Issue by daysnights** [nyaadevs/nyaa#45]
Currently use [Flexget](https://github.com/Flexget/Flexget) to get the .torrent files from the RSS feed. With the old Nyaa it worked, with new Nyaa I get a "broken or invalid torrent file received" error.

````2017-05-14 07:03 VERBOSE  task          task linux         REJECTED: `Totally_legal_linux_iso.iso` by retry_failed plugin because has already failed 6 times in the past. (failure reason: trailing junk - broken or invalid torrent file received)````

I suspect this might be related to your download links for .torrent files. I tested this by doing a:

````# wget https://nyaa.si/view/legal_linux_iso/torrent````

for one of the download links provided and it downloaded a file called "torrent", not the expected "legal_linux_iso.torrent" file.

Possibly whatever fancy redirect is going on is breaking on downloaders.

**Comment by Sn0wCrack** [comment]
This may have something to do with files being marked in the Content-Disposition as "inline" rather than "attachment".

**Comment by TheAMM** [comment]
The inline is for adding the filename; it does not affect the downloading. However, it's possible UTF8 filenames can break parsers (because there's not really a real standard for them).
Pop by the irc or otherwise message me (us) the id so we can look closer.

**Comment by Sn0wCrack** [comment]
The content disposition will affect the way in which the file is handled on an application basis, attachment seems the more common for forcing the download of the file it seems.

**Comment by TheAMM** [comment]
Content-*Type* will affect how applications (should) consider the data: Content-Disposition *should* not matter. But we'll see.

**Comment by daysnights** [comment]
@TheAMM messaged you in IRC.

Also tested with curl and it did the same thing. My current assumptions are as follows:

1. Wget, Curl, and whatever Flexget uses all end up downloading a file simply called "torrent". However the site is naming the file or telling the browser/downloading agent to name the file is either not correct, not respected, or not understood. When testing the "torrent" file with http://torrenteditor.com it reads the file correctly, which reinforces that the file contents might be fine, it's just a naming issue.

2. Flexget rejects the "torrent" file because it's not an expected "file_name.torrent" file.

**Comment by TheAMM** [comment]
For posterity, the reason Flexget rejected the torrents was because they had an extra trailing 'e' from the patch-process involved in generating a bencode using the stored info_dict.

**Comment by daysnights** [comment]
Re-opening this issue as the second part about the torrent file name is still in issue.

I attempted to test Flexget with the RSS feed today and discovered this issue:

```2017-05-24 10:43 ERROR    entry         nyaa            Failed legal_linux_iso.iso (File `/home/daysnights/rtorrent/watch/torrent.torrent` already exists and is not identical.)```

What this means is that it downloads iso1.iso's torrent file as as "torrent.torrent" and throws it in the watch folder for rtorrent. It then attempts to download another file like iso2.iso and is told that its torrent file is also called "torrent.torrent", tries to place it in the watch folder, and discovers there's already a .torrent file with that name and errors out.

**Comment by nettosama** [comment]
Mine works, but I'm passing the torrent directly to transmission, without a watch folder.

I don't know what header Flexget checks to get the torrent filename, but browsers format the torrent with their corresponding name correctly.

**Comment by TheAMM** [comment]
FlexGet doesn't consider `filename*=UTF-8''` in `PluginDownload.filename_from_headers`, but they can't really be blamed since the `Content-Disposition` standards are different in every browser.

Pushing a fix with a failsafe now.
