### ISSUE TITLE
Refining By Date Internal Error

### ISSUE THREAD

**Issue by Taien** [nyaadevs/nyaa#452]
If you enter any date in the date refine fields and click Refine, you get an internal error.  For example:

![image](https://user-images.githubusercontent.com/1469026/36119416-82d8c4a4-1005-11e8-85b3-f56b332f5d8e.png)

![image](https://user-images.githubusercontent.com/1469026/36119514-c243334a-1005-11e8-8b0a-fd17a08dbd6b.png)

**Comment by Arylide** [comment]
Wrong repo.
