### ISSUE TITLE
Several torrents displaying underflowed seed counts (2147483647)

### ISSUE THREAD

**Issue by Azphreal** [nyaadevs/nyaa#454]
I'm not sure if this is my problem or the site's. Just noticed it passing by and thought it might be worth bringing to attention.

Several torrents have their seed counter underflowed (-1 as an unsigned 32-bit number). This is happening on some, but not all torrents, and doesn't seem to be differentiating between popular torrents (e.g., HorribleSubs release of Takagi-san) or new, unpopular torrents.

![image](https://user-images.githubusercontent.com/21125058/36137131-da3d761c-10e7-11e8-85dc-25611da440af.png)
![image](https://user-images.githubusercontent.com/21125058/36137136-e2aec404-10e7-11e8-98e0-08587e7d34ea.png)

**Comment by gavbn** [comment]
It's fixed now

**Comment by CounterPillow** [comment]
That's because @nyaadev decided to test in production.
