### ISSUE TITLE
Invalid magnet link in search results

### ISSUE THREAD

**Issue by Iapeto** [nyaadevs/nyaa#456]
Searching for any term and then clicking the magnet link for [this torrent](https://nyaa.si/view/1009691) (ex. [searching "franxx"](https://nyaa.si/?f=0&c=0_0&q=franxx)) will give an invalid magnet link on the search page.  The correct magnet link is given on the individual torrent page.  I believe this happens when 'QA' are the final 2 characters of the torrent hash, the search page then turns the final character into an '=' and invalidates the magnet link.

You can see the same happen to [this](https://nyaa.si/view/1009700) torrent when searching for it ([ex.](https://nyaa.si/?f=0&c=0_0&q=%5BAise-Delsubs%5D+Mahouka+Koukou+no+Rettousei+-+Hoshi+wo+Yobu+Shoujo))

**Comment by TheAMM** [comment]
Fix is now live and ES has been resynced.
