### ISSUE TITLE
Search filters are hidden/CSS error?

### ISSUE THREAD

**Issue by jrdp18** [nyaadevs/nyaa#464]
![](https://i.imgur.com/wBWPY5o.png)

**Comment by jrdp18** [comment]
I'm using Chrome on Windows 7, it's up to date. Screen resolution is 1366x768. I don't use anything that changes CSS, I even tried turning off all extensions. Javascript is enabled. Same problem with Firefox and IE.

When window is smaller, burger menu doesn't work.

**Comment by CounterPillow** [comment]
Works for me.

**Comment by jrdp18** [comment]
I checked it with Tor Browser and it loaded properly when JS is enabled. I wonder why it isn't showing properly in my normal browsers. I tried checking it with the family computer and it's also broke there. Can't be region blocked, is it?

**Comment by TheAMM** [comment]
Press F12 and see if any of the .js files fail to load.

**Comment by jrdp18** [comment]
![](https://i.imgur.com/zn1VNxo.png)

**Comment by TheAMM** [comment]
Haha, what.
What headers do you get when you open https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css in a new tab?

**Comment by CounterPillow** [comment]
Are you using some shitty "anti virus" software that happens to proxy every HTTPS request by installing some local certificates and then MITMing your browser? Because Cloudflare should most definitely send that header.

**Comment by jrdp18** [comment]
@TheAMM Is this what you're looking for? In the title bar
Access denied | cdnjs.cloudflare.com used Cloudflare to restrict access

Content:
The owner of this website (cdnjs.cloudflare.com) has banned your IP address

**Comment by ReimuHakurei** [comment]
Yeah, looks like you're banned from CDNJS somehow... How you would manage that, I have no idea.

We won't be the only site impacted by such a thing. You'll need to take that up with CDNJS or something.
