### ISSUE TITLE
No verification e-mail on GMAIL

### ISSUE THREAD

**Issue by FernandoGOT** [nyaadevs/nyaa#465]
I registered a few days ago using my GMAIL e-mail but I din'd receive the email (is the domain banned on gmail too?), and if I try to login using this account I just get a message that the account is not activated. I recomend a way of resend the verification e-mail and possible a way to change the e-mail (to not lose the user name).

**Comment by Arylide** [comment]
Did you check your spam? Did you misspell your email? Gmail does not block us as far as I've seen. Supply your username if you did check your spam and are sure you didn't misspell your email.

**Comment by Arylide** [comment]
I received this response from the site in question when I asked on your behalf: https://ghostbin.com/paste/pgxer

You should presumably follow up with them, as we here at the repo just handle code.
