### ISSUE TITLE
Searching with "text1"|"text2" doesn't show results anymore

### ISSUE THREAD

**Issue by sasukeskapa** [nyaadevs/nyaa#474]
Searching for "Movie"|"OVA" doesn't show results anymore.
Only if I exclude the " characters, but this makes searching for 2 multi word torrents impossible.
(This feature worked until a few days ago.)

**Comment by CounterPillow** [comment]
Regression from #473 @TheAMM

**Comment by sasukeskapa** [comment]
The feature doesn't work properly on sukebei.nyaa.si even after the fix.
(Example: https://sukebei.nyaa.si/?f=0&c=0_0&q=%22fakku%22%7C%22x3200%22%7C%22fappu%22
There are a lot of results that only appear if I only search for fakku.)

**Comment by TheAMM** [comment]
There are no results for `"fappu"` or `"x3200"` which is why you only get results for `"fakku"`. The new literal tokens are lowercased and split by whitespace, nothing else - there's no substringing (ie. `"foo"` won't find anything inside `bazfoobar`). Rethink your search terms.

**Comment by sasukeskapa** [comment]
Thank's for the information, I'll use it accordingly : )
