### ISSUE TITLE
Nyaa.......

### ISSUE THREAD

**Issue by hi5kba** [nyaadevs/nyaa#475]
hope this is Ok..... can any one provide a Pre-setup ISO?
(Edit I mean after the Initail Setup of Nyaa... before any content or Users are created..)

im having trouble setting up... Rarely use Linux...... :(

_if not feel free to close or remove_

**Comment by CounterPillow** [comment]
Just follow the instructions in the readme.

**Comment by hi5kba** [comment]
Help Required: Clarify Section 2 is Right.., [6A] - whats meant 2By substitute for your own config.py" do i have to edit a file in the Project?, and [7] where is this meant to be Ran?

Installed ubuntu-16.04.4


Opened Teminal (I'm guessing it doesn't have to be anywhere specific...) ( 1 to 6B all done in one Terminal)

1] - Install dependencies https://github.com/pyenv/pyenv/wiki/Common-build-problems

$ Sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev


2] - $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv (I'm doing this into $HOME/)

2A] - Define environment variable PYENV_ROOT to point to the path where pyenv repo is cloned and
 add $PYENV_ROOT/bin to your $PATH for access to the pyenv command-line utility.

$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
$ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile

( NOTE - it Says to use ~/.bashrc instead of ~/.bash_profile.... 
 "Ubuntu and Fedora note: Modify your ~/.bashrc file instead of ~/.bash_profile"
I ran as both just in case...)

2B] - Add pyenv init to your shell to enable shims and autocompletion.
 Please make sure eval "$(pyenv init -)" is placed toward the end of the shell configuration file since it manipulates PATH during the initialization.

$ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile

2C] - Restart your shell so the path changes take effect. You can now begin using pyenv.

$ exec "$SHELL"

2D] - Install Python versions into $(pyenv root)/versions. (UNecessary But I Did AnyWay)

$ pyenv install 2.7.8


3] - Install pyenv-virtualenv https://github.com/pyenv/pyenv-virtualenv/blob/master/README.md

3A] - Check out pyenv-virtualenv into plugin directory

$ git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv

3B] - Restart your shell to enable pyenv-virtualenv

$ exec "$SHELL"

4] - Install Python 3.6.1 with pyenv and create a virtualenv for the project:
$ pyenv install 3.6.1
$ pyenv virtualenv 3.6.1 nyaa
$ pyenv activate nyaa

5] - Install latest mariadb by following instructions here https://downloads.mariadb.org/mariadb/repositories/

6] -  Connect to DB
 $ mysql -u root -p -h localhost

6A] - Run the following commands logged in as your root db user (***substitute for your own config.py values if desired***):
CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123';
GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost';
FLUSH PRIVILEGES;
CREATE DATABASE nyaav2 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

7] - Finishing up (I'M Lost From Here..... Am i meant to of cd into the download of the "https://github.com/nyaadevs/nyaa.git")
Run python db_create.py to create the database and import categories
Follow the advice of db_create.py and run ./db_migrate.py stamp head to mark the database version for Alembic
Start the dev server with python run.py
When you are finished developing, deactivate your virtualenv with pyenv deactivate or source deactivate (or just close your shell session)
You're now ready for simple testing and development!

**Comment by hi5kba** [comment]
hiya again. how do copy Repositery files into "pyenv virtualenv 3.6.1 nyaa" im abit stuck... :(
