### ISSUE TITLE
Search: Nyaa returns 404 when search empty and page number too high (i.e. page 6/5)

### ISSUE THREAD

**Issue by SkyBeastMC** [nyaadevs/nyaa#482]
Hello (: 
I've recently found a bug in Nyaa.

The normal behaviour is: when you search with a keyword, if your page number is too high (for exemple page 6 when the last page is 5), you get a normal response but without content.
https://nyaa.si/user/HorribleSubs?f=0&c=1_2&q=youjo%20senki&p=999

But when you search without keyword, you get a nice 404 error : 
https://nyaa.si/user/HorribleSubs?f=0&c=1_2&q=&p=999

I'm using an unofficial node api to scrap the torrents from nyaa and that messes the whole code :<
I know this bug is quite subtle but i need this particular case to work :x

**Comment by ReimuHakurei** [comment]
Searches with a query and without a query are handled differently.

**Comment by ReimuHakurei** [comment]
Er, hit submit too early. 
This is not a bug. We don't officially support any scraping. You won't encounter this condition in normal usage.
