### ISSUE TITLE
Add an interface for mass editing of torrents.

### ISSUE THREAD

**Issue by Naine** [nyaadevs/nyaa#49]
It should be available at a user's own user page, eg. https://nyaa.si/user/Naine

Something similar to what mods had on NT would be ideal. i.e. a checkbox on every torrent entry, and a menu at the top with some common edit actions, such as hide, unhide, move to category, mark/unmark as remake, delete (once this is implemented), etc.

Mods may find it useful if this interface is made available on every page with a torrent listing, along with some additional actions mods have access to, such as move to account.

**Comment by nathancyam** [comment]
This particular feature request may be addressed in this pull request: https://github.com/nyaadevs/nyaa/pull/121/

**Comment by nathancyam** [comment]
This can be closed as it has been addressed by https://github.com/nyaadevs/nyaa/pull/121

**Comment by Naine** [comment]
Looks good. Thanks Nathan.
