### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Frizz925** [nyaadevs/nyaa#490]
Is it possible to have some sort of Docker support? It can make life more easier for people trying to set it up both for development and production use, especially for those who are trying to work using Windows platform.

**Comment by ReimuHakurei** [comment]
Windows is not a supported platform for this software. Ubuntu Linux is the only supported platform. 

Docker is also of limited usefulness for this software, as rapid deployment is not really a priority.

**Comment by Frizz925** [comment]
Docker on Windows actually runs on top of Linux VM so there is nothing to deal with the Windows platform itself. I personally use both macOS and Windows back and forth so some sort of containerization would be nice to set up everything for development environment.

Then again I could just create my own repository for it so it can be separated from the main development.

**Comment by CounterPillow** [comment]
I don't see the point of having multiple gigabyte binary blobs with outdated vulnerable software contained within.
