### ISSUE TITLE
RSS - specific uploaders or categories

### ISSUE THREAD

**Issue by bluefiberbread** [nyaadevs/nyaa#493]
So, there's a group constantly uploading malware under the guise of random shows,, and using filters doesn't work. Can we have RSS for trusted uploaders or something?

**Comment by Phr33d0m** [comment]
Done. You can close this issue now.

**Comment by Nalapl3** [comment]
Except you can already do it. Go to their profile, type what you want in search/select category, click RSS and done. 
eg. https://nyaa.si/?page=rss&q=Nanatsu&c=0_0&f=0&u=Chyuu

**Comment by Phr33d0m** [comment]
Also, if you use a relatively decent torrent client (like qBittorrent) you can just subscribe to the user's RSS (go to their profile -> click the RSS button) and you can filter the shows from that user (or feed) from within the torrent client...

![image](https://user-images.githubusercontent.com/1591486/40142776-ecdeccb6-5959-11e8-8916-bdb57e32a6cc.png)

**Comment by CounterPillow** [comment]
As others have said, this is literally already implemented, and the site even tells you about it if you search for a user.

**Comment by Phr33d0m** [comment]
- Use regular expressions (without it the filter will ignore the order of the filtered words)
- Must contain: "- 01" or "01 [720p]" (if you put only 01 it will match with entries containing 2018)
- RSS: http://horriblesubs.info/rss.php?res=720

![image](https://user-images.githubusercontent.com/1591486/40201543-a517ea4a-5a1f-11e8-884d-12c128d9cb1e.png)

**Comment by bluefiberbread** [comment]
ty, it used to grab 2018 for me before as well
