### ISSUE TITLE
"Blacklisted email provider" error when signing up

### ISSUE THREAD

**Issue by FreezyChan** [nyaadevs/nyaa#504]
I tried to sign up at nyaa and it showed up "Blacklisted email provider" error and I have no idea what is wrong.

**Comment by i-cant-git** [comment]
Why is Hotmail (@live) blacklisted?

**Comment by ReimuHakurei** [comment]
Hotmail rejects the activation emails, so if you sign up with Hotmail it is impossible to activate your account. We blocked then to prevent this. 

This is a common problem and is the same reason many other websites (namely tons of Internet forums) say not to sign up with a Hotmail email address.

**Comment by New1997** [comment]
Umm, I still can receive activation email (not nyaa) in hotmail so.. (normally it either went to junk box or else in the inbox there are "focus" and "other" option which is why not all email is shown). It is also because hotmail is the email I reserved only for registrations so it would help me a lot if you would unbanned it please.
Thanks

**Comment by ReimuHakurei** [comment]
Hotmail does not deliver OUR activation emails, so if we didn't block them, you'd be registering an account you could never use. 

Use another email account to register.

**Comment by ilko-k** [comment]
Does the site still accepts new accounts ? I've tried dozen of emails and they are all blacklisted, even temporary email... this is too much, really.

**Comment by ReimuHakurei** [comment]
All Microsoft-provided email addresses (Outlook/Hotmail/etc) are blacklisted because they block our activation emails.

All known temporary/disposable email providers are blacklisted to prevent spam.

As far as I am aware, all other email address should be fine to use.
