### ISSUE TITLE
Separate categories for translated and RAW releases in sukebei?

### ISSUE THREAD

**Issue by GitHubUserer** [nyaadevs/nyaa#505]
Can there be separate categories for the translated releases in sukebei like in the normal nyaa?

**Comment by Arylide** [comment]
This repo is about the software, not any implementation of it.

**Comment by GitHubUserer** [comment]
How is this request an implementation of the software and not the software itself?

How is it different to other feature requests?

**Comment by Arylide** [comment]
We don't control any site that uses the software, we could add a category like that to the software sure, but whether any site you want to influence also adds it is up to them. If this request is for your own use of the software adding a new category is fairy simple by looking at the existing ones.

**Comment by GitHubUserer** [comment]
You are saying that sukebei.nyaa.si website and its features are programmed by someone else/somewhere else and not in this repo?
