### ISSUE TITLE
RSS feed update refused

### ISSUE THREAD

**Issue by fluffymiyo** [nyaadevs/nyaa#510]
Since a few hours ago, RSS feed updates have stopped working in uTorrent 3.x versions.  uTorrent 2.x versions still work and Deluge works as well. Feeds from other websites work.

uTorrent 3.1.2 reports: 
Unable to download "Overlord S3|https://nyaa.si/?page=rss&q=overlord+iii+720&c=0_0&f=0&u=HorribleSubs": connection closed by peer

Manually adding torrents works and I can download them without problems

Was uTorrent 3.x blacklisted for RSS somehow?

**Comment by TheAMM** [comment]
```
IMPORTANT: only submit issues that are relevant to the code. We do not offer support for any deployments of the project here; make your way to the IRC channel in such cases.
```
Please do not ignore the issue template.
