### ISSUE TITLE
Compatibility with uncommon browsers

### ISSUE THREAD

**Issue by lanodan** [nyaadevs/nyaa#511]
Currently nyaa got few issues on the following browsers, listed by their type.

- Graphicals: netsurf, dillo
- Textual: links

Here is a list of the issues I’ve uncounted so far:

- all: there is no icon for the magnet/download (could probably be fixed by having Unicode) in the table view, meaning you have to click on the torrent’s page each time
- Graphicals: the file list isn’t expanded by default, and they lack interactive rendering for expanding them
- netsurf: the navbar is in hidden/mobile but there is a lack of interactive rendering
- dillo: the filters menu seems to be empty, the navbar is wider than the viewport

I’ll probably give it a try at fixing it in upcoming pull request(s), but no big promise here as I don’t have much knowledge in frontend stuff.

**Comment by CounterPillow** [comment]
Sounds like a fun project to get started contributing on the nyaa codebase. I think it's not really going to have much impact on real world usage, as you're likely the first and only person to ever use the site in those browsers, but as long as supporting them doesn't interfere with existing site functionality or require ridiculously ugly hacks I have no qualms about this. (Though, I will also not make any efforts to support them from my side.)
