### ISSUE TITLE
[BUG] uTorrent RSS Broken?!

### ISSUE THREAD

**Issue by misakitchi** [nyaadevs/nyaa#512]
Hi!

Since 14 or 15/07/2018 the RSS with uTorrent is not working anymore... :(
Maybe this change?: "nyaa 	torrents: Clean up magnet URI quotation (a day ago)"

I have uT v3.3.1 and Windows 7 x64

Please Help! :)

**Comment by CounterPillow** [comment]
This is likely an issue with TLS and therefore unrelated to this repository

**Comment by misakitchi** [comment]
Before 14/7 RSS and uT was working fine so what did you change?

**Comment by ReimuHakurei** [comment]
This repository is for the codebase, which is completely unrelated to the current SSL/TLS configuration.

The appropriate place to ask questions about our SSL/TLS configuration would be on IRC, in #nyaa-help on irc.rizon.net.

**Comment by misakitchi** [comment]
OK thanks for your response Reimu :)

**Comment by misakitchi** [comment]
Find a Fix! :)
https://support.cybersource.com/s/article/How-do-I-enable-TLS-1-2-on-Windows-7
