### ISSUE TITLE
Double quotes in search

### ISSUE THREAD

**Issue by Jendrej** [nyaadevs/nyaa#517]
How double quotes should work: I type `"rec"` and get the results that contain this word, in this case, the anime that has this name.
How it works: I had to type `"rec" -receive -records -precure -resurrection -recruiting` to filter out the things I didn't want. That is not the intended behavior.

**Comment by CounterPillow** [comment]
I'd say that pretty much is what you'd expect from a search. Consider `"rec "`. At any rate, "fixing" this would break other people's intended behaviour for searches.

**Comment by TheAMM** [comment]
Double quotes work as a substring match and the current behavior is the intended behavior of a substring match. It's really hard to make a search engine that suits everyone's expectations, but the current character-matching literal search is much more powerful than the previous word-matching literal search.
If you're worried that `"rec "` won't find stuff with `rec_` or `rec.`, you can use `"rec "|"rec_"|"rec."` as explained in the search documentation. It's all about how you use the tool.
