### ISSUE TITLE
how to edit ?

### ISSUE THREAD

**Issue by ted423** [nyaadevs/nyaa#521]
Describe your issue/feature request here (you can remove all this text). Describe well and include images, if relevant!

Please make sure to skim through the existing issues, your issue/request/etc may have already been noted!

IMPORTANT: only submit issues that are relevant to the code. We do not offer support for any deployments of the project here; make your way to the IRC channel in such cases.

I want to edit https://nyaa.si/view/1069627
remove the 01

**Comment by ReimuHakurei** [comment]
This is not the place for support.

For support, go [here](https://qchat.rizon.net/?channels=nyaa-help).

**Comment by ted423** [comment]
I find where to click edit, sorry.
maybe add some text or put after tittle  is better
