### ISSUE TITLE
Torrent seeds/peers/completions counting problems

### ISSUE THREAD

**Issue by LALADevil** [nyaadevs/nyaa#522]
Sorry, my English is not very good.

I turned on ENABLE_SHOW_STATS = True in config.py

But the counter doesn't work:

![2018-09-13_17-17-07](https://user-images.githubusercontent.com/33951857/45479483-33a24b00-b779-11e8-90d6-722a90c51100.png)

Any suggestions? Thank you

**Comment by Arylide** [comment]
You need to use a compatible external tracker to handle the stats. We used to maintain one for that purpose, however it no longer works. We will publish a new one soon.
