### ISSUE TITLE
Docker infrastructure doesn't work

### ISSUE THREAD

**Issue by fisherwei** [nyaadevs/nyaa#548]
elasticsearch report two error:
`ERROR: [2] bootstrap checks failed
[1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
[2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

Ubuntu 18.04
Docker 18.06.1-ce

resolving:
[1]: need a patched full-stack.yml
```
diff --git a/.docker/full-stack.yml b/.docker/full-stack.yml
index 4de5bb1..131cd84 100644
--- a/.docker/full-stack.yml
+++ b/.docker/full-stack.yml
@@ -54,6 +54,10 @@ services:
     image: elasticsearch:6.5.4
     volumes:
       - elasticsearch-data:/usr/share/elasticsearch/data
+    ulimits:
+      nofile:
+        soft: 65536
+        hard: 65536
     depends_on:
       - mariadb
```

[2]: need change sysctl
`sysctl -w vm.max_map_count=262144` or modify sysctl.conf.

**Comment by CounterPillow** [comment]
cc @aheadley

**Comment by xNinjaKittyx** [comment]
I figure I'd point out that the Dockerfile for me required to add libssl-dev as one of the apt packages, otherwise when pip installing mysqlclient, it fails with something like could not find `-l lssl` and `-l lcrypto`
