### ISSUE TITLE
uploader team page and rss

### ISSUE THREAD

**Issue by mo2n** [nyaadevs/nyaa#552]
Hi 2 all !!!
How about to add a team/crew page, so the team that upload the work have a personal link/index to the tracker ?

**Comment by CounterPillow** [comment]
Could you elaborate what you mean by that?

**Comment by mo2n** [comment]
sorry for my english !! is like a team page (user-detail-torrent + team logo + rss)

**Comment by such-doge** [comment]
That already exists at /user/username. The RSS link on that page has the username as a filter. The only thing it doesn't have is a logo.

**Comment by rmrhz** [comment]
why is there such need of a logo when the description already exists for this?

**Comment by such-doge** [comment]
There is no need.
