### ISSUE TITLE
Dark Mode bootstrap 404

### ISSUE THREAD

**Issue by Arsobbiak** [nyaadevs/nyaa#56]
After reload page in Dark theme its try to download:

`https://nyaa.si/static/css/bootstrap.min.css.map`

but this is not exist.

**Comment by EduenSarceno** [comment]
I confirm this, when dark mode is on, the list of http requests is:


![captura de pantalla de 2017-05-14 07-55-37](https://cloud.githubusercontent.com/assets/18363635/26034510/f67afe12-387a-11e7-9477-61ccde65133d.png)

![captura de pantalla de 2017-05-14 07-53-19](https://cloud.githubusercontent.com/assets/18363635/26034486/75cbd476-387a-11e7-93e3-23c60c4d4d61.png)

**Comment by aldacron** [comment]
Fixed
