### ISSUE TITLE
Feature Request - Delete account

### ISSUE THREAD

**Issue by GauthierPLM** [nyaadevs/nyaa#561]
A button to delete an account would be useful. Account are used mostly to index torrents created by the same uploader and don't have any ratio/control purpose. Users that wish to delete their account should be permitted to do so.

**Comment by CounterPillow** [comment]
What would happen to their uploads or their comments?

**Comment by GauthierPLM** [comment]
Uploads can be set to anonymous uploader and comment could be the same or deleted depending on user choice.

**Comment by CounterPillow** [comment]
If all the data is kept, i.e. comments and uploads, then there doesn't seem to be that much of a point to deleting one's account. I'd actually see it as annoying once moody teens start repeatedly deleting and re-creating their accounts.

**Comment by Nalapl3** [comment]
While you can't delete old comments, you can delete your uploads manually now, so if somebody is determinated to remove their torrents, they can already do it now. I don't see a reason why wouldn't you be allowed to just remove the content as well.

**Comment by Arylide** [comment]
Even if this feature was added it would never be used on the site. If you don't want to use the site anymore just abandon your account.
