### ISSUE TITLE
Add info about how to update torrents.

### ISSUE THREAD

**Issue by MitsukaSouji** [nyaadevs/nyaa#565]
Please, add info in info section about how to update torrents (when you change contents in torrent).

**Comment by DJATOM** [comment]
Simply by uploading new ones and deleting the outdated versions? Or even leaving old torrents as is?

**Comment by CounterPillow** [comment]
The site does not allow you to update a torrent, as the info hash would change, and the info hash is assumed to be unchanging for any particular upload.

You can edit the description and information field as well as the title though.
