### ISSUE TITLE
DDOS-GUARD blocks access to RSS

### ISSUE THREAD

**Issue by endrin** [nyaadevs/nyaa#566]
Currently it's impossible to access any RSS feed due to (apparently) new DDoS protection provider

Steps to reproduce:
`wget "https://nyaa.si/?page=rss&u=Erai-raws"`

Expected result:
(contents of RSS feed)

Actual result:
```
Resolving nyaa.si (nyaa.si)... 185.178.208.182
Connecting to nyaa.si (nyaa.si)|185.178.208.182|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
ERROR 403: Forbidden.
```

if you launch same wget query with `--debug` flag you'll get a wall of javascript ending with "DDoS protection by DDoS-GUARD". So I would blame it.

**Comment by ReimuHakurei** [comment]
This is the wrong place to report such problems. The correct place is here: https://qchat.rizon.net/?channels=nyaa-help

Either way, problem should be resolved.
