### ISSUE TITLE
Feature request: Add a filter option is search

### ISSUE THREAD

**Issue by tlzydude** [nyaadevs/nyaa#569]
Can you add a special filter in search similar to Refine in Pantsu https://snag.gy/XZF1P0.jpg. So that users can choose a specific quality (like SD, HD,1080p, HEVC, MP4, 8bit,10bit, FLAC etc..).

**Comment by ReimuHakurei** [comment]
This would be pointless, because we don't actually store any metadata for things like that.

You can search for such qualities by putting in relevant terms into the search box. ie: if you search "1080p", it will show you results that have "1080p" in the torrent title.
