### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by owner** [nyaadevs/nyaa#571]
Hello!
 
I need to follow to RSS feed by one releaser. But, RSS limited to 75 from unlim.
Do you have a additional argument in URL link for follow to all feed?

Thanks!

**Comment by ReimuHakurei** [comment]
No. The RSS feed function is intended to allow you to have your BitTorrent client automatically download new releases as they are posted. The current limit of 75 results on the RSS feed is more than sufficient for this purpose.

**Comment by owner** [comment]
RSS Feed have a argument for view more torrent files?

**Comment by CounterPillow** [comment]
No, because people were abusing it to scrape the entire site which killed the server, negatively impacting the experience of other users.

Refine your search if what you want isn't within 75 results.
