### ISSUE TITLE
Add ability to change username

### ISSUE THREAD

**Issue by GiacomoLaw** [nyaadevs/nyaa#574]
Hi there, thanks for the awesome tool. I was looking around the profile, and can't find a way to change the username. I also searched the issues on Github.

https://github.com/nyaadevs/nyaa/blob/8365894268fc5f8d983cd6fc06d75a1a239c5567/nyaa/views/account.py#L85-L92

I assume it would be more complex than an email change as comment/torrent uploads would have to be updated with the new name.

Would it be possible to consider this option?

Thanks! 😄

**Comment by such-doge** [comment]
Thanks for the suggestion, but this would break a lot of things. Usernames are used in user profile page URLs, RSS feed URLs, and the moderator log. Allowing username changes would break people's bookmarks, RSS feeds, and the usefulness of the moderator log.

**Comment by GiacomoLaw** [comment]
Makes sense. Thanks for the site!
