### ISSUE TITLE
Nyaasi.xyz

### ISSUE THREAD

**Issue by sizzlingkenny** [nyaadevs/nyaa#578]
i was searching nyaa alternative because nyaa does not work in my country and i recently found this 
https://nyaasi.xyz/recent
it has lots of new torrents including .torrent files can any body tell me what is the difference using nyaa and nyaasi ?

**Comment by CounterPillow** [comment]
this is unrelated to the software, stop opening off-topic issues, and stop using shitty scrapers that inject malware ads
