### ISSUE TITLE
i really need your help！

### ISSUE THREAD

**Issue by batista777** [nyaadevs/nyaa#580]
this torrent break the rule,
this film is made by photographer zell ching in taiwan,
but M3ngxln use it and without consent and insult him ,involving criminal.
so i hope to delete it,
i do my  very best but invain,
so very need your help.

sukebei.nyaa.si/view/2777839
https://sukebei.nyaa.si/view/2777838
https://sukebei.nyaa.si/view/2768466
https://sukebei.nyaa.si/view/2768464
https://sukebei.nyaa.si/view/2768457
https://sukebei.nyaa.si/view/2768445
https://sukebei.nyaa.si/view/2768441
https://sukebei.nyaa.si/view/2768434
https://sukebei.nyaa.si/view/2768432
https://sukebei.nyaa.si/view/2768428

no matter you delete or not please send me a message 
thank you.

**Comment by ReimuHakurei** [comment]
This repository and issue tracker is for the nyaav2 software package. If you have an issue with any websites that may use this software, please contact that website's administrators.
