### ISSUE TITLE
My account creating was refused

### ISSUE THREAD

**Issue by nikin78** [nyaadevs/nyaa#582]
Before a few minutes, I just tried to make a new account with my own gmail but it was refused due to IP ban.

It was my first time I entered on Nyaa website and made account.

Because of my IP was shown as from south Korea?

I still can't guess why I was banned and couldn't create an account.
 
So I tried it again but it was rejected with a message that 'my account is not activated'.

It seems like that my account was already created but can't be accessed due to some reason.

Can you guys tell me what's going on my account?

**Comment by CounterPillow** [comment]
This repository is for issues pertaining to code, not support questions of any deployments of the code as we are not the people running those.
