### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by 7sevenseven** [nyaadevs/nyaa#586]
When I registered with xxx mailbox, the system showed that Email was already in use by another account. I thought I could log in. When I tried to log in, the system displayed Login failed! Account is not activated. When I clicked the forgot password, the system displays The response parameter. Is missing. But I didn't receive the message in my mailbox. Changed a mailbox and tried the system still failed to register

**Comment by ReimuHakurei** [comment]
When you register an account, you are sent an account activation email. You must click the link in the email in order to activate your account. Please read the Help pages for more information.
