### ISSUE TITLE
Platform Upgrade to use more modern development stacks

### ISSUE THREAD

**Issue by abdatta** [nyaadevs/nyaa#597]
Hi

I was looking through the code and it looks like a lot of it uses old practices and uses less modern stacks like flask, and simple server side renders for frontend, that were configured almost 3-4 years back.
Maybe we can consider upgrading it to more modern stacks for eg. using MERN/MEAN stacks (Node.js and React/Angular) for more modern and efficient site performance as well as better development cycles.

I would be glad to help build this if you consider it. I have good experience in building full stack websites using nodejs and angular/react.

Regards!

**Comment by ibnuda** [comment]
lol.

**Comment by abdatta** [comment]
A **LOT** of feature requests can be integrated as well in this rewrite of the site. I see a huge number of reasonable feature requests in issues and many of them have been closed without any resolve.

**Comment by CounterPillow** [comment]
>Node.js and React/Angular

fuck right off with that
