### ISSUE TITLE
specific rss feed empty

### ISSUE THREAD

**Issue by Draic** [nyaadevs/nyaa#6]
rss feed with search content (example: https://nyaa.si/?page=rss&q=damedesuyo+eromanga&c=1_2&f=2) has no results.

**Comment by erengy** [comment]
From what I understand, magnet-only releases (i.e. anything before 2017-05-12) are not included in the RSS feed at the moment. The feed title reads:

> Nyaa Torrent File RSS (No magnets)

**Comment by TheAMM** [comment]
The RSS feeds only display torrents with actual .torrent files - magnets are variably problematic in clients.
You're not-seeing archived torrents, but we still have some dumps to import; stay tuned.

**Comment by FichteFoll** [comment]
Some clients do support magnets, so it might be worth including them either directly or in a separate page (e.g. with `?page=rss&magnets=yes`).

Not that I need it, but some might want to download an entire series and feeding an RSS feed as some sort of API would be useful even for old imported torrents.

**Comment by TheAMM** [comment]
Magnets added in a3422ce0682e1261c64ea6efe67f1bdcd851109e.
