### ISSUE TITLE
after run my heroku app getting error

### ISSUE THREAD

**Issue by todokku** [nyaadevs/nyaa#603]
im adding db to string below :
mysql://d6rqxtxbnsr87ob5:w8mrvccopimpf7fa@z1ntn1zv0f1qbh8u.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/zbhbobs3zgmln74a
1.after run my heroku app getting error , here : https://irantorrent.herokuapp.com/
please tell me how to change default db name from 'nyaav2' ti anithing in all program without problem
& if its possible make app.json to nyaa repository for easy deploy to heroku

**Comment by ReimuHakurei** [comment]
Heroku is not a supported platform for this software. 

It must be run on a dedicated Linux machine running Ubuntu Server 16.04 or 18.04. 

This software will perform extremely poorly on a remote database. The database server must be installed on the same system as the rest of the software, as per installation instructions. 

Detailed installation instructions are in this repository. If you can't figure out that, then you have no hope using the rest of the software. 

Also, if you're from Iran, you're subject to an embargo and should not be using this software at all. And stop bombing our military bases, thanks.
