### ISSUE TITLE
Overlapping text in filelist

### ISSUE THREAD

**Issue by Silver-Fullbuster** [nyaadevs/nyaa#607]
As can be seen from the image, the text overlaps when we go deep enough in the folders.
Strangely doesn't have the issue on other folders in the same depth.
(Nyaa ID:1217352)

Firefox 72.0.2 (64 bit) using Windows 10 v1909

EDIT: Refreshed the web-page and the bug vanished. Might have been a random bug. Closing it.
![image](https://user-images.githubusercontent.com/22327220/73609511-61996100-45f4-11ea-82ff-8de733782349.png)

**Comment by CounterPillow** [comment]
I've seen this happen in Firefox before too, but never found a way to reliably reproduce it unfortunately.
