### ISSUE TITLE
Older browser problem

### ISSUE THREAD

**Issue by Hiei12** [nyaadevs/nyaa#61]
This is mostly only a problem with older browsers, It does affect me dues to me have more than one browser installed but i thought i would post about it just incase others have this problem. 

![untitled](https://cloud.githubusercontent.com/assets/28691050/26036927/f8ae89ca-389c-11e7-8875-2fd9409f060a.jpg)

in this picture i linked everything you click in the red box is https://nyaa.si/?s=downloads&o=desc or https://nyaa.si/?s=downloads&o=asc you cant click anything else

 Once you scroll down past the red line it works normally and every other part of the site also works normally its just that top square when searching where you cant click anything due to what i said.

**Comment by TheAMM** [comment]
That looks like disabled javascript (or an error in it) - check the debug console for any output.
We're not really planning on supporting *outdated* versions of Firefox, however. If this happens on recent Firefox versions, do tell.

**Comment by Hiei12** [comment]
O i know you most likely support older versions i thought i would just post about it just incase. I only use this for addons that aren't supported on new versions. 

Now dont know if im doing this right but the only errors i could find are

Error: $ is undefined
Source File: https://nyaa.si/static/js/bootstrap-select.js
Line: 16

Error: Bootstrap's JavaScript requires jQuery
Source File: https://nyaa.si/static/js/bootstrap.min.js
Line: 6

Again i just wanted to post about this just to let it be known, If you want to close this ticket you can.
 Thanks for the response

**Comment by TheAMM** [comment]
It seems like jQuery fails in some way or another, but to be frank we're not that eager to start fixing jQuery or something to support old browsers.
Thanks for noting it, though
