### ISSUE TITLE
Feature Request & Enhancement: Add Reseed Request

### ISSUE THREAD

**Issue by sinnx3** [nyaadevs/nyaa#612]
Add a reseed request icon to torrents that have 0 seeds but at least 1 active leecher.
And maybe send a email notification to the original poster requesting a reseed.

Sorta like what anidex does. Example Below.

![brave_je8O6jPERm](https://user-images.githubusercontent.com/3137441/75865740-a0742f80-5dc9-11ea-97b9-c242450713a7.png)

**Comment by ReimuHakurei** [comment]
This isn't really a standard public tracker feature. Any function that would send a notification would almost certainly just end up getting abused for spamming.
