### ISSUE TITLE
issue:search engine word tail, probaby regex issue 

### ISSUE THREAD

**Issue by ravarage** [nyaadevs/nyaa#615]
Dear nyaa team

not sure if this is bug or feature, but when I search for fairy tail, instead of searching to fairy tail, it search for upload made by user fairy that contain word tail, so I tried using other uploader user name like judas tail, it show torrent contain word tail uploaded by judas, searching for "fairy tail" inside quot or double quot will fix the issue, I don't think many people know that.

kind regards

**Comment by ReimuHakurei** [comment]
The website will, upon searching for such a query, offer to instead perform such a search, but it does not do so unless you click the link at the top to change the search.

Tested and confirmed that this supposed issue does not occur.
