### ISSUE TITLE
Add screenshot to Readme

### ISSUE THREAD

**Issue by asheraryam** [nyaadevs/nyaa#616]
I came across this repo and it looks super interesting, but there's no screenshots to look at, no binary under releases to try out, and the dev setup seems involved (python env + db setup + elastic search) which is not worth doing without even a feature list to know what one is getting into.

I'd like some screenshots please! Or if there is no UI yet then a list of (planned) features.

**Comment by marco262** [comment]
As far as I can tell, this is repo is not intended for general, open-source use. Rather, it's the source for the site being run at https://nyaa.si/

**Comment by txtsd** [comment]
Not sure if you're aware, but this is the stack for https://nyaa.si

**Comment by asheraryam** [comment]
@txtsd Thanks! I know of the site but I didn't make the connection.

I couldn't find the link in the readme, and googling "nyaa torrent software" didn't help much. :b

**Comment by ReimuHakurei** [comment]
This is pointless for the intended application of this codebase.
