### ISSUE TITLE
FLOSS/Privacy-friendly Captcha

### ISSUE THREAD

**Issue by EchedeyLR** [nyaadevs/nyaa#618]
I wanted to ask if would be possible to replace Google reCaptcha with a better privacy friendly/floss alternative proposing the suggestions in the following link:
* https://developers.reverseeagle.org/replace/google-recaptcha/

I checked to be sure if this was asked or reported before and am warned that the issues here are mostly related to help directly with the code and this is why I start it as a question.

**Comment by CounterPillow** [comment]
Both of these are hot garbage.

- the php thing is php and self-hosted which means more ops bullshit/load on server
- the crypto thing would not do anything for us because the compute challenge it presents is absolutely not enough to dissuade anyone from making spam accounts

If anything, replacing it with hCAPTCHA would be the way to go. It was already bikeshed to death in private though.

**Comment by EchedeyLR** [comment]
Sorry if I annoyed you in any sense with my propositions.

Maybe, hCatcha would be a good starting point.

**Comment by resynth1943** [comment]
@CounterPillow Are you an official maintainer of this project?

**Comment by CounterPillow** [comment]
@resynth1943 I am a contributor, as you can tell by the various commits I have in this repository

**Comment by resynth1943** [comment]
> And no worries EchedeyLR, you didn't annoy me, it's just the way I choose to talk about software (all software is bad).

Ahh. I may have misinterpreted your message :-)

> the crypto thing would not do anything for us because the compute challenge it presents is absolutely not enough to dissuade anyone from making spam accounts

Ehh. One could argue [reCAPTCHA](https://www.solverecaptcha.com/) [doesn't](https://antcpt.com/eng/home.html) [dissuade](https://2captcha.com/) [attackers](https://moneyconnexion.com/captcha-work.htm) [from](https://limeproxies.com/blog/how-to-solve-and-prevent-recaptcha/) [from](https://anti-captcha.com/) [creating](https://techwiser.com/bypass-google-recaptcha-verification/) [spam](https://humancoder.com/RecaptchaV2Api.aspx) [accounts](https://bestcaptchasolver.com/).

> Captcha Solving is a perfect online data entry jobs from home. There are around 10 best sites where you can join as a Captcha solver & earn around $0.5 to $2 for every 1000 captchas you solve.

The truth is, CAPTCHA's are a flawed concept. If someone wants to spam your project bad enough, they'll get around it. It's quite a challenge to differentiate robots from people, as *user agents are computers, too.*

**Comment by rmrhz** [comment]
I'm surprised no one mentioned. [hCaptcha](https://www.hcaptcha.com/)

**Comment by ReimuHakurei** [comment]
Really? Nobody mentioned it? Totally not in the first reply to this useless issue, right?

The staff have considered changing to hCaptcha already, however nobody can be bothered to actually switch over to it. It has been considered solely because reCAPTCHA is pretty much trash nowadays, and hCaptcha is supposedly better.

Nobody gives a shit about your objections to "muh privacy" because of reCAPTCHA/Google. Privacy, or being open source, or anything of that sort are in no way, shape, or form part of any consideration as to what CAPTCHA service is used, because we do not care in the slightest.

**Comment by resynth1943** [comment]
> Really? Nobody mentioned it? Totally not in the first reply to this useless issue, right?

Your attitude repulses me, and it terrifies me to think a maintainer of a FOSS project can be the antithesis of healthy collaboration.

> The staff have considered changing to hCaptcha already, however nobody can be bothered to actually switch over to it.

What are the outstanding issues with switching, please? I have heard it maintains rather OK compatibility with reCAPTCHA API's.

> Nobody gives a shit about your objections to "muh privacy" because of reCAPTCHA/Google.

Thank you for stating your opinion. Sadly, it's blatantly false. Thankfully, people like me do not follow your definition of privacy.

Using reCAPTCHA is fuelling Google's collection of data. They use techniques to match your activity with your other data, even with unauthenticated. That's called online profiling, and it's something you should be aware of prior to making crude remarks on a public forum.

> Privacy, or being open source, or anything of that sort are in no way, shape, or form part of any consideration as to what CAPTCHA service is used, because we do not care in the slightest.

No issues with that. In fact, I agree. You  have been shockingly rude to the person submitting this issue, and that makes me sad. Brushing off valid concerns as some sort of theoretical bullshit, when there are clear facts that say the opposite, is disappointing.

Many thanks,
Resynth

**Comment by ReimuHakurei** [comment]
> ...FOSS project...

This project was open-sourced simply to make some autists shut up. Virtually all of the third-party contributions we have received have been worthless garbage.

> Thank you for stating your opinion. Sadly, it's blatantly false. Thankfully, people like me do not follow your definition of privacy.

By "nobody" I mean nobody involved in the project.

> Using reCAPTCHA is fuelling Google's collection of data. They use techniques to match your activity with your other data, even when the user is not logged into Google.

I, for one, welcome our new Google overlords.

**Comment by CounterPillow** [comment]
>The truth is, CAPTCHA's are a flawed concept. If someone wants to spam your project bad enough, they'll get around it. It's quite a challenge to differentiate robots from people, as user agents are computers, too.

Works for us actually. That's why it was added in the first place.

Anyway these reddit tier responses are tiring and Reimu is also cringe af, maybe we'll hCAPTCHA one day.
