### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by krysstof** [nyaadevs/nyaa#62]
mainly cosmetic/ ergonomic
- page numbers at the top of the list instead of scrolling to  the bottom each time to to next/previous page, it's a PITA when the list is long

- the category browser/filter "old nyaa" was pretty nice to use (like when filtering on a specific user, you would get only the category he had posted), is there any plan to bring that back?

**Comment by snowfag** [comment]
> the category browser/filter "old nyaa" was pretty nice to use (like when filtering on a specific user, you would get only the category he had posted), is there any plan to bring that back?

Not sure what you mean

**Comment by sharkykh** [comment]
@snowfag 
I think he means that:
http://web.archive.org/web/20160411023818/http://www.nyaa.se:80/?cats=1_37&user=209171

Filter the user's torrents by category... 
The site supports this, it's just not implemented into the user interface.
For example: https://nyaa.si/?u=Ohys&c=1_2

**Comment by snowfag** [comment]
Huh works for me. You just use the filter by the search box while on a user page.  ![](https://i.lolicon.eu/1494833172.png)

**Comment by sharkykh** [comment]
Huh! Didn't think of that! :+1:

**Comment by Zabanya** [comment]
+1 for me as well, the reason i want this because I'd like to filter out non-engrish anime and books at the same time

**Comment by mreweilk** [comment]
I gotta say I tried this out and it looks odd. Pages have a max length anyways so I'm gonna close this.

Perhaps someday we can remove the message box and then this can be revisited.

![](https://i.gundam.eu/1499146187.png)
