### ISSUE TITLE
Support Webtorrent trackers

### ISSUE THREAD

**Issue by Banou26** [nyaadevs/nyaa#621]
[This PR](https://github.com/nyaadevs/nyaa/pull/620) would allow peers to support browser clients by adding WebTorrent capable trackers.

This is the related issue to talk about stuff if you are against supporting WebTorrent clients or against these specific trackers.

**Comment by CounterPillow** [comment]
>Being able to stream torrent files from a browser application would be pretty nice

No, browser are awful at video rendering

>or think of a network that blocks the udp:tcp bittorrent protocol

use a vpn

>so why not.

it needlessly splits the swarm by having a second incompatible transport, just because webshitters want to do everything inside of a browser window and shit and fart whenever they can't

>"Real" clients also generally only download torrent, they don't offer any easy integrations to do other things, but by being in the browser, you can build an application around being able to stream torrent files.

[libtorrent rasterbar](https://www.libtorrent.org/)

**Comment by Banou26** [comment]
> No, browser are awful at video rendering

Not that it's any relevant to this issue.

> use a vp

Such a cumbersome alternative

> it needlessly splits the swarm by having a second incompatible transport, just because webshitters want to do everything inside of a browser window and shit and fart whenever they can't

Does it really though, the biggest part of the swarm is and always will be udp/tcp clients and those clients will always be there, if they don't support wss trackers, it'll just ignore them, just like they are doing now, but if they do support them, it could allow them to get data from more peers than they'd have just with udp/tcp.

> libtorrent rasterbar. Has Google caused brainrot to the extent where people think you can only develop applications inside browsers now? What is going on?

That's also why i did say "easy", web technologies are really popular and have big communities attached to them.
With those communities, tools and new technos get made to ease the making of even more web supports.
One of its biggest advantages is the ease of use, just use a browser, go to this url and voila you can stream your torrent.
It certainly has its appeal, compared to the cumbersome software side of:

Which torrent software is the most recommended, which one doesn't crash when i do x or y, which one doesn't have an annoying update system.
Which software do i need to download to automatically track my series and automatically download the episodes.

But what am I even answering this for... From your tone alone I know you'll not change your mind on this, which is sad, I know browsers are trash, they're not efficient at anything they do and most websites are coded like shit, but it's not because some things are bad that we should completely ignore some other nice parts that we could do with it if it was done right.

The world sadly isn't perfect

**Comment by ReimuHakurei** [comment]
Uploaders are free to add WebTorrent trackers to their uploads if they want to, though I would imagine that the vast majority don't care, just like everyone on staff of this project.

**Comment by artemmolotov** [comment]
> why? just install a real client.

"Real client" does not have additional functionality that various applications or sites with p2p content may have. For example, search for user-generated content, comments, individual playlists, subscriptions, previews, likes.

Take a look at [PeerTube](https://peer.tube/) ([alt](https://open.tube/)), which tries to replace YouTube and uses WebTorrent + ActivityPub technology.

> just because webshitters want to do everything inside of a browser window and shit and fart whenever they can't

Installing unnecessary apps and jumping between multiple installed apps instead of navigating websites can also be unpleasant for humans when using a service for a short time.

P.S.: Not calling for any solution, but decided to post a comment.
