### ISSUE TITLE
Onion domain? Blockchain-dns domain?

### ISSUE THREAD

**Issue by POMATu** [nyaadevs/nyaa#622]
Hi, I dunno where to write feature request about the site (not the code) so I am writing here.

I am living in Russia. We are not having problems with p2p fines. We are having a bit of problems with censorship. Before I moved into the flat where ISP does not bother implementing proper DPI (without DPI I can bypass censorship easily) the only option I had is to visit nyaa.si via TOR. Well it is sorta fine unless I get some fail2banned node then I have to bruteforce exit nodes until I get to nyaa.si. And also its not convinient at all.

There are namecoin and emercoin domains available (.lib, .baazar, .bit, .emc) which are not controlled at all nowadays. To get to such webstie all you need is just install browser extension. You can also just switch your DNS to one of OPENNIC ones and for some reason it bypasses censorship as well even though it still falls into DNS hijacking DPI on ISP side. Their DPI just dont understand such zones exists. OpenNIC dns-over-https providers would do the job as well. And also DNScrypt openNIC resolvers would work just fine.

That basically means no any authority currently concerned about blockchain DNS. Russian torrent tracker "rutracker.org(rutracker.lib)" currently works nicely with that concept. I can easily access it from any PC anywhere (for example when visiting friends house) without any redundant VPNs or other stuff (once again p2p itself is uncontrolled at my location)

__I propose adding a blockchain dns mirror to nyaa.si and maybe as well onion mirror (if you are not scared of not being able to do fail2ban on onion mirrors).__

**Things you need to know about blockchain dns deployment**
1) You wont be able to use cloudflare CDN (it does not support such domains, other custom ones might work but I am not sure)
2) You need to use separate IP for such domain otherwise it makes no sense, because authorities ban both ip and domain, so original nyaa.si ips are already banned (if its not CDN)
3) You wont be able to have SSL on that domain. Nobody will issue SSL for such domain. Well you can put nyaa.si ssl cert there for users that are concerned about their passwords being transmitted in cleartext, but it will be red because of domain mismatch. So most blockchain-dns users will use plain http, that means there should not be any redirect to https
4) You need to poke that blockchain DNS domain in your wallet every 3 month or so, so it extends (depends on blockhain used for domain: namecoin/emercoin). The network fee for such operation is really small like less then a dollar.

Hope to see nyaa.si becoming more available to end-users soon!
~ROW ROW FIGHT THE POWER!~

**Comment by Arylide** [comment]
Apologies, this repository is only about this software, we don't have anything to do with any sites using it.
