### ISSUE TITLE
Torrents with alternate colors barely visible

### ISSUE THREAD

**Issue by DarkDullahan** [nyaadevs/nyaa#64]
While the style of the site is very nice and fluid, some of the theme's elements vary from the original Nyaa.se too greatly, i.e. rated torrent's colors. The green, blue, and red are too faint to be distinguishably noticeable from white on the light theme, which is causing some problems with colorblind users. 
Example on Nyaa.si:<img width="1138" alt="screenshot 2017-05-14 21 45 29" src="https://cloud.githubusercontent.com/assets/8221867/26040533/37c426ae-38f4-11e7-8248-c141978d8e03.png"> 
Reference from Nyaa.se:
<img width="1050" alt="screen shot 2017-04-16 at 23 05 25" src="https://cloud.githubusercontent.com/assets/8221867/26040542/518e5dca-38f4-11e7-9bed-da339b7b3b09.png">

While it's not a dire situation, I feel the colors should be more vibrant similarly to the original nyaa site.

**Comment by HitmanJ** [comment]
There's a discussion about that here https://github.com/nyaadevs/nyaa/issues/28

**Comment by DarkDullahan** [comment]
Thank you. Will close this issue and take it there.
