### ISSUE TITLE
Search broken when using hyphen "-"

### ISSUE THREAD

**Issue by nettosama** [nyaadevs/nyaa#70]
Example queries:

maid-sama: get results with shows named maid-sama plus shows with only maid.
"maid-sama": get results from shows with maid-sama.

k-on: no results.
"k-on": no results.

Could be more, those are just 2 examples.

**Comment by TheAMM** [comment]
As stated in the issue prefill and the main site, search is under progress. All points regarding it are moot, as it will be replaced entirely when the branch is ready (#67).
