### ISSUE TITLE
Please allow to filter search results by user id

### ISSUE THREAD

**Issue by josch** [nyaadevs/nyaa#78]
Hi,

nyaa.se had the feature of being able to limit search results by torrents from a specific user.

So for example to find only torrents by horrible subs I would go to:

    http://www.nyaa.se/?term=foobar&user=64513

But the `user` key does not seem to be understood by the backend. It would be nice if it were supported.

Thanks!

**Comment by sharkykh** [comment]
Use ?u=USERNAME

**Comment by josch** [comment]
Thanks, that works!

Feel free to close the issue.

One concern: are usernames guaranteed to be unique? If yes, what is the user id for? If not, then it would make more sense to have this be `?u=USERID` as it was with nyaa.se.

A suggestion: on nyaa.se I found the `?user=USERID` feature because the user page linked to it. Maybe it would make sense to do the same for nyaa.si. Currently the page that lists all torrents of a user is https://nyaa.si/user/USERNAME but since the `?u=USERNAME` search format exists it might make sense not to duplicate functionality and use the latter format instead or in addition.

**Comment by sharkykh** [comment]
@josch I can't close the issue, you can.

About the "duplicate functionality... I think ?q=USERNAME is for the RSS function.
Because you can actually use /user/USERNAME, and also searching from that page filters out torrents by that user.

**Comment by josch** [comment]
Oh, then there is even more duplicate functionality.

So in addition to

    ?u=HorribleSubs&q=foobar

there is also

    user/HorribleSubs?q=foobar

Anyways, thanks for supporting this functionality!
