### ISSUE TITLE
request more information in RSS page 

### ISSUE THREAD

**Issue by 8lbiasian** [nyaadevs/nyaa#82]
First of all thanks for fixing previous issue #12 but is it possible to force the magnet link to be for all not only for those who don`t have torrent files. 

second matter its to add some other details like for example here i have this 

error with using Sonarr 

Indexer feed is not supported: Feed doesn't contain the release content size.

if possible to add such information like this
`<item>
            <title>NAME OF TORRENT</title>
            <pubDate>PUBLISH DATE</pubDate>
            <category>CATEGORY NAME IF EXIST</category>
            <link>MAGNET LINK</link>
			<guid isPermaLink="true">TORRENT LINK</guid>
            <size>TORRENT SIZE</size>
            <seeders>NUMBER OF SEEDER</seeders>
            <leechers>NUMBER OF LEECHERS</leechers>
</item>`

thanks ^^

**Comment by sharkykh** [comment]
> second matter its to add some other details like for example here i have this
> 
> error with using Sonarr
> 
> Indexer feed is not supported: Feed doesn't contain the release content size.
> 
> if possible to add such information like this
> `<item> <title>NAME OF TORRENT</title> <pubDate>PUBLISH DATE</pubDate> <category>CATEGORY NAME IF EXIST</category> <link>MAGNET LINK</link> <guid isPermaLink="true">TORRENT LINK</guid> <size>TORRENT SIZE</size> <seeders>NUMBER OF SEEDER</seeders> <leechers>NUMBER OF LEECHERS</leechers> </item>`

There's already a pending pull request for this ( #51 ), and another issue about this ( #34 )

> First of all thanks for fixing previous issue #12 but is it possible to force the magnet link to be for all not only for those who don`t have torrent files.

Answer for this is in the pull request: https://github.com/nyaadevs/nyaa/pull/51#issuecomment-301296338
So maybe an option for the RSS link to show only magnets...

**Comment by 8lbiasian** [comment]
thanks for your reply, waiting for these to be implemented, i hope i can help actually i know python -_- but have some issues with working with git commands of how to submit request << i know how to work with my own project like pushing but other i need to learn so i can help with the developing this project ^^
