### ISSUE TITLE
Feature Request - Resize of columns

### ISSUE THREAD

**Issue by MrSupreme** [nyaadevs/nyaa#83]
Hi,

Could the columns please be able to be resized as some torrents have insanely long names and you cannot see the episode number.

Or perhaps a tool tip when the mouse hovers over it.

![image](https://cloud.githubusercontent.com/assets/21308829/26116907/09df1b46-3a65-11e7-9860-d63141ca7fd3.png)

Thanks

**Comment by TheAMM** [comment]
Already done in #81, pal
