### ISSUE TITLE
Make a discord group and link it in the blue box so we can talk to each other.

### ISSUE THREAD

**Issue by Darkmeep** [nyaadevs/nyaa#85]
Hey I think it would be nice if you started a discord group and liked the group join link at the top in the blue box. Talking to each other would be really nice. It would also give us a place to go and ask what's up every once in a while. I know #nyaa-dev@irc.rizon.net is a thing but irc is well it's not so user friendly without a tutorial so not very good for a average user type thing. It would also be a good way to start up the community without having to add comments. I know the server is already under huge load and comments would make it worse so having a discord group would be a good in between for the people wanting to comment since it doesn't put a load on your server.

**Comment by nonamethanks** [comment]
>irc is well it's not so user friendly without a tutorial so not very good for a average user type thing
If you can't use google you deserve to eat shit with the pigs.
