### ISSUE TITLE
Can't view full name of file from grid

### ISSUE THREAD

**Issue by antoniosv** [nyaadevs/nyaa#86]
Basically, the full text of the filename is not rendered in the grid.  
This is very inconvenient, as filenames are usually very long, and I need to see all of it to decide if it's the file I want.

**Comment by Ricardo1991** [comment]
A potential fix has been merged on #81 
It will allow you to read the full title on the label displayed on mouse hover

**Comment by TheAMM** [comment]
The commit is now live as well.
