### ISSUE TITLE
search function in sukebei.nyaa.si does not support searching in Japanese

### ISSUE THREAD

**Issue by zerobikappa** [nyaadevs/nyaa#87]
I can search the title on www.nyaa.si using the keywords in Japanese. However, it seems doesn't work in sukebei.nyaa.si.

**Comment by aldacron** [comment]
what keywords are you searching?

**Comment by zerobikappa** [comment]
Now I found that not only sukebei.nyaa.si, the www.nyaa.si would has this bug as well:

for example, the most recent file in sukebei.nyaa.si is this one:
+++ ATOM-282 俺たち！魁！！いたずら塾

if I search "俺たち" ( kanji + hiragana), the result would include this file;
if I search "俺" ( one kanji only), the result would show all files no matter it includes the keyword or not;
if I search "たち" ( hiragana only), the result would show all files including "たち", but the file "+++ ATOM-282 俺たち！魁！！いたずら塾" is not in the result.

I am not sure how to exactly describe this...

**Comment by TheAMM** [comment]
This should now be fixed, ES is up and running.
