### ISSUE TITLE
Seeders/Leechers counters stuck at "0"

### ISSUE THREAD

**Issue by mbartelsm** [nyaadevs/nyaa#89]
![untitled](https://cloud.githubusercontent.com/assets/5376208/26122880/4753ddea-3a79-11e7-8f3d-0b1c27b78cdb.png)
The counters for seeders and leechers display "0" for all torrents. Sorting appears to be broken as well.

**Comment by Darkmeep** [comment]
They switched trackers. All the torrents still work and it's the same tracker name you use when making a torrent but the numbers are broken because they switched to something that doesn t support it.

**Comment by aldacron** [comment]
This is fixed.
