### ISSUE TITLE
User IDs

### ISSUE THREAD

**Issue by Nalapl3** [nyaadevs/nyaa#9]
My idea is to show your user ID on the profile.

**Comment by FichteFoll** [comment]
Probably also allow access to a user's profile via ID. Not as the primary way, since the user name is superior in that regard, but IDs are still useful for when people or admins rename their account for some reason.

**Comment by nyaadev** [comment]
Account renaming is currently not a thing.
We changed from user id to user name in the last minutes before launch, we didn't want people to go through all the users or care about low user id elite status.
So as long as people can't change their user name this should not be an issue.
If some group changes their name and wants their user name to be changed we can think about something...

**Comment by Nazonaze** [comment]
If we want to avoid enumeration there are other ways to approach the issue as well, like we could use some sort of ID hashes (eg. 10 letters matching `[0-9a-z]`).

We could also free display names entirely. This would require changing login to be e-mail only, but we could allow users to change their names freely and we wouldn't need to worry about duplicates either. Things like the Trusted system should prevent most of the potential abuse from this as well (eg. hard to pretend to be someone else if the real one's name is green and yours isn't).

**Comment by rizenfrmtheashes** [comment]
instead of enumerated IDs, you could use UUIDs as public facing unique IDs and then internally keep integer IDs as the database primary key.

**Comment by Nazonaze** [comment]
UUIDs would certainly work but they're pretty long and ugly, which is why I didn't didn't mention them in my previous comment.

**Comment by uro** [comment]
@Nazonaze Even that Uuid's are only one good way to avoid feature problems with scalability and HA database

**Comment by Nalapl3** [comment]
I just wanted muh e-peen.

**Comment by rizenfrmtheashes** [comment]
I would actually contribute a ton more if we were in Django ORM land.  I have a ton of experience there.  I'm still reading up on the codebase and seeing where I can contribute.

**Comment by martstern** [comment]
@Nalapl3 you can now see your own id now on the profile, but it is not available for others to see unless they are admins. With this e-peen, as with real peen, we don't want it showing in public, but you can see it for yourself, and I suppose you can go out of your way to show it off to your friends (in person or with a picture), if you really want. As was mentioned, it is not desirable to allow users to be browsed by their id, so that is not and will not be allowed.
