### ISSUE TITLE
[ES] Map '_' to ' '

### ISSUE THREAD

**Issue by TheAMM** [nyaadevs/nyaa#96]
Currently to search for torrents with spaces replaced with underscores (eg `[finFAGs]_Frame_Arms_Girl_06_(1280x720_TV_AAC)_[6E227A8B].mkv`),
you have to search for `_frame*` as plain `frame` will not include them in the results.
Mapping `_` to ` ` (space) in [es_mapping.yml](https://github.com/nyaadevs/nyaa/blob/291789445cec7d18213a5a20daf81db787535a8d/es_mapping.yml#L31) will fix this.

*Edit:* Seems like mapping `.` to space would be useful as well.

**Comment by snowfag** [comment]
Fixed. 6b4d487314162c8afefad4db770c8c6df48a0dc2
